"""molrs — Rust-backed molecular simulation primitives.

Top-level re-exports cover core data structures, I/O, regions, conformer generation,
force fields, and the SMILES front-end. **Analysis lives under**
:mod:`molrs.compute`, one subpackage per ``molrs::compute`` domain:

* :mod:`~molrs.compute.density` — RDF, GaussianDensity, LocalDensity, SpatialDistribution
* :mod:`~molrs.compute.order` — Steinhardt, Nematic, Hexatic, SolidLiquid, LegendreReorientation
* :mod:`~molrs.compute.environment` — BondOrder
* :mod:`~molrs.compute.pmft` — PMFTXY
* :mod:`~molrs.compute.diffraction` — StaticStructureFactorDebye
* :mod:`~molrs.compute.cluster` — Cluster, ClusterProperties, gyration / inertia / COM
* :mod:`~molrs.compute.msd` — MSD
* :mod:`~molrs.compute.ml` — PCA, K-means, descriptor rows
* :mod:`~molrs.compute.transport` — VACF, Green-Kubo / Einstein diffusion and conductivity, Debye relaxation + fit
* :mod:`~molrs.compute.dielectric` — raw dielectric observables
* :mod:`~molrs.compute.spectroscopy` — power / IR / Raman / VCD / ROA / dielectric spectra + their consistency checks
* :mod:`~molrs.compute.fitting` — generic curve fits: LinearFit, CumulativeTrapezoid, Plateau
* :mod:`~molrs.compute.distribution` — bond / angle / dihedral distributions
* :mod:`~molrs.compute.dynamics` — VanHove
* :mod:`~molrs.compute.hbond` — HBonds
* :mod:`~molrs.compute.voronoi` — RadicalVoronoi and integration

Analysis classes are reachable as ``molrs.<Class>`` too, because PyO3 declares
``module = "molrs"``, but that spelling is plumbing and is not in ``__all__``.
``molrs.compute.<domain>`` is the documented path.
"""

from ._lib import (
    # Public exceptions
    BlockDtypeError,
    UnitsError,
    # SimBox + neighbors
    Box,
    LinkedCell,
    NeighborQuery,
    NeighborList,
    # Block + Frame
    Block,
    MetaValue,
    Frame,
    FRAME_SCHEMA_VERSION,
    Unit,
    Quantity,
    UnitRegistry,
    Trajectory,
    ScalarObservable,
    VectorObservable,
    # I/O
    read_pdb,
    read_pdb_trajectory,
    read_xyz,
    read_xyz_trajectory,
    XYZTrajReader,
    read_lammps,
    read_lammps_traj,
    LAMMPSTrajReader,
    read_dcd,
    DCDTrajReader,
    read_trr,
    TRRTrajReader,
    read_xtc,
    XTCTrajReader,
    read_gro,
    read_chgcar_file,
    read_cube_file,
    write_cube_file,
    write_pdb,
    write_pdb_trajectory,
    write_xyz,
    write_gro,
    write_lammps,
    write_lammps_traj,
    write_dcd,
    write_trr,
    write_xtc,
    parse_smiles,
    SmilesIR,
    # Regions
    Sphere,
    HollowSphere,
    Cuboid,
    Parallelepiped,
    Region,
    # Molecular graph hierarchy
    Element,
    Graph,
    Atomistic,
    CoarseGrain,
    ExtractedSubgraph,
    SmartsMatch,
    SmartsPattern,
    Reaction,
    # Systems (module-level free functions over a graph)
    translate,
    rotate,
    scale,
    align_direction,
    perceive_aromaticity,
    add_hydrogens,
    find_rings,
    compute_gasteiger_charges,
    # Chemical perception (builder: graph in / graph out, non-mutating)
    Perceive,
    # Conformer generation
    Conformer,
    ConformerReport,
    ConformerStageReport,
    # Force field
    Typifier,
    MMFF94Typifier,
    MMFF94STypifier,
    OPLSAATypifier,
    AtdTypifier,
    # Charge models (native AM1-BCC / ABCG2 / Mulliken / Gasteiger)
    BccModel,
    MullikenModel,
    GasteigerModel,
    ForceField,
    Potentials,
    OptReport,
    LBFGS,
    read_forcefield_xml,
    read_forcefield_xml_str,
    read_opls_xml,
    read_opls_xml_str,
    read_lammps_forcefield,
    read_lammps_forcefield_str,
    write_lammps_forcefield,
    write_lammps_forcefield_str,
    intramolecular_pairs,
    extract_coords,
    FragmentScaling,
    compute_k_ij,
    fragment_scaling_data,
    scale_lj,
    # Field-name convention submodule
    keys,
    # Signal processing (low-level FFT helpers)
    signal_acf_fft,
    signal_apply_window,
    signal_frequency_grid,
    # Raw-compute + explicit-fit classes (compute/fit repoint). Raw computes
    # return ONLY a raw curve (no fitted sigma/D); the fit classes consume that
    # curve and yield the derived coefficient/spectrum.
    VACF,
    GreenKuboDiffusion,
    EinsteinDiffusion,
    EinsteinConductivity,
    GreenKuboConductivity,
    DebyeRelaxation,
    LinearFit,
    CumulativeTrapezoid,
    Plateau,
    DebyeFit,
    PowerSpectrum,
    IRSpectrum,
    RamanSpectrum,
    EinsteinHelfandSpectrum,
    GreenKuboSpectrum,
    # analysis-parity computes (geometric distributions, Van Hove, reorientation,
    # hydrogen bonds, spatial distribution, radical Voronoi, chiral spectra).
    AngleDistribution,
    DihedralDistribution,
    DistanceDistribution,
    DistributionResult,
    CombinedDistribution,
    CombinedDistributionResult,
    VanHove,
    VanHoveResult,
    LegendreReorientation,
    LegendreReorientationResult,
    HBondCriterion,
    HBonds,
    HBondsResult,
    SpatialDistribution,
    SpatialDistributionResult,
    RadicalVoronoi,
    VoronoiCells,
    voronoi_domains,
    voronoi_voids,
    DensityGrid,
    MolecularMoments,
    VoronoiIntegration,
    polarizability_finite_field,
    VcdSpectrum,
    RoaSpectrum,
    ResonanceRamanSpectrum,
    # Freud-style analysis — preferred public path is molrs.compute.*. Bound as
    # package attributes (not listed in ``__all__``) so PyO3 ``module = "molrs"``
    # stays honest for griffe: ``molrs.compute.density.RDF`` resolves to ``molrs.RDF``.
    RDF,
    RDFResult,
    GaussianDensity,
    LocalDensity,
    Steinhardt,
    Nematic,
    Hexatic,
    SolidLiquid,
    BondOrder,
    PMFTXY,
    StaticStructureFactorDebye,
    Cluster,
    ClusterResult,
    ClusterCenters,
    ClusterCentersResult,
    ClusterProperties,
    CenterOfMass,
    CenterOfMassResult,
    GyrationTensor,
    InertiaTensor,
    RadiusOfGyration,
    MSD,
    MSDResult,
    MSDTimeSeries,
    DescriptorRow,
    Pca2,
    PcaResult,
    KMeans,
    KMeansResult,
)

from . import ff  # molrs.ff.potential.soft parameter interface

# Rich Python Frame/Block layer (pandas-style API; CSV engine in Rust on the
# core Block). These subclass the bare PyO3 cores and SHADOW the top-level
# ``molrs.Block`` / ``molrs.Frame`` as the canonical types — every public API
# (io readers, etc.) yields these. The shadow is safe now that molpy re-exports
# them instead of subclassing the bare core (chain spec 04). Internal modules
# that need the raw cores import them from ``._lib`` directly.
from . import frame  # noqa: F401
from .frame import Block, Frame

# Chainable, object-style force-field layer (Style/Type handle views over the
# Rust ForceField). Shadows the bare PyO3 ``ForceField`` with the subclass that
# adds ``def_*style`` factories; ``def_type``/``types``/``to_potentials`` are
# inherited from the core. Raw core stays importable from ``._lib``.
from . import forcefield  # noqa: F401
from .forcefield import (  # noqa: F401
    AngleHarmonicStyle,
    AngleStyle,
    AngleType,
    AtomStyle,
    AtomType,
    BondHarmonicStyle,
    BondStyle,
    BondType,
    DihedralOPLSStyle,
    DihedralStyle,
    DihedralType,
    ForceField,
    ImproperStyle,
    ImproperType,
    PairCoulLongStyle,
    PairLJ126CoulCutStyle,
    PairLJ126CoulLongStyle,
    PairLJ126Style,
    PairStyle,
    PairType,
    Parameters,
    Style,
    Type,
    # readers re-wrapped to yield the Python ForceField (shadow the raw ones)
    read_forcefield_xml,
    read_forcefield_xml_str,
    read_opls_xml,
    read_opls_xml_str,
    read_lammps_forcefield,
    read_lammps_forcefield_str,
    write_lammps_forcefield,
    write_lammps_forcefield_str,
)

from . import io  # molpy-compatible I/O facade (read_lammps_data, …)
from . import compute  # analysis subpackage — one module per molrs::compute domain
from . import signal
from . import typifier
from .views import (
    Angle,
    Atom,
    Atomistic,
    Bead,
    Bond,
    CGBond,
    CoarseGrain,
    Dihedral,
    DrudeParticle,
    Entities,
    Entity,
    GraphViews,
    Improper,
    Link,
    MasslessSite,
    NodeRef,
    Refs,
    RelationRef,
    VirtualSite,
)

__all__ = [
    "io",
    "compute",
    "signal",
    "typifier",
    "BlockDtypeError",
    "UnitsError",
    "Box",
    "LinkedCell",
    "NeighborQuery",
    "NeighborList",
    "Block",
    "MetaValue",
    "Frame",
    "FRAME_SCHEMA_VERSION",
    "Unit",
    "Quantity",
    "UnitRegistry",
    "Trajectory",
    "ScalarObservable",
    "VectorObservable",
    "read_pdb",
    "read_pdb_trajectory",
    "read_xyz",
    "read_xyz_trajectory",
    "XYZTrajReader",
    "read_lammps",
    "read_lammps_traj",
    "LAMMPSTrajReader",
    "read_dcd",
    "DCDTrajReader",
    "read_trr",
    "TRRTrajReader",
    "read_xtc",
    "XTCTrajReader",
    "read_gro",
    "read_chgcar_file",
    "read_cube_file",
    "write_cube_file",
    "write_pdb",
    "write_pdb_trajectory",
    "write_xyz",
    "write_gro",
    "write_lammps",
    "write_lammps_traj",
    "write_dcd",
    "write_trr",
    "write_xtc",
    "parse_smiles",
    "SmilesIR",
    "Sphere",
    "HollowSphere",
    "Cuboid",
    "Parallelepiped",
    "Region",
    "Element",
    "Graph",
    "Atomistic",
    "CoarseGrain",
    "ExtractedSubgraph",
    "SmartsMatch",
    "SmartsPattern",
    "Reaction",
    "NodeRef",
    "RelationRef",
    "Refs",
    "GraphViews",
    "Entity",
    "Link",
    "Entities",
    "Atom",
    "VirtualSite",
    "DrudeParticle",
    "MasslessSite",
    "Bond",
    "Angle",
    "Dihedral",
    "Improper",
    "Bead",
    "CGBond",
    "translate",
    "rotate",
    "scale",
    "align_direction",
    "perceive_aromaticity",
    "add_hydrogens",
    "find_rings",
    "compute_gasteiger_charges",
    "Perceive",
    "keys",
    "Conformer",
    "ConformerReport",
    "ConformerStageReport",
    "Typifier",
    "MMFF94Typifier",
    "MMFF94STypifier",
    "OPLSAATypifier",
    "AtdTypifier",
    "BccModel",
    "MullikenModel",
    "GasteigerModel",
    "ForceField",
    "Style",
    "AtomStyle",
    "BondStyle",
    "AngleStyle",
    "DihedralStyle",
    "ImproperStyle",
    "PairStyle",
    "Type",
    "AtomType",
    "BondType",
    "AngleType",
    "DihedralType",
    "ImproperType",
    "PairType",
    "Parameters",
    "Potentials",
    "OptReport",
    "LBFGS",
    "read_forcefield_xml",
    "read_forcefield_xml_str",
    "read_opls_xml",
    "read_opls_xml_str",
    "read_lammps_forcefield",
    "read_lammps_forcefield_str",
    "write_lammps_forcefield",
    "write_lammps_forcefield_str",
    "intramolecular_pairs",
    "extract_coords",
    "FragmentScaling",
    "compute_k_ij",
    "fragment_scaling_data",
    "scale_lj",
    "signal_acf_fft",
    "signal_apply_window",
    "signal_frequency_grid",
    # Analysis classes are NOT listed here: their public path is
    # molrs.compute.<domain>. They stay importable as molrs.<Class>
    # because PyO3 declares module = "molrs", but that is plumbing.
]
