"""Type stubs for molrs Python bindings.

Hand-maintained. Keep in sync with the PyO3 source in `molrs-python/src/**.rs`
on every PR that touches `#[pyfunction]` or `#[pyclass]`. The docs CI runs a
freshness guard that asserts every export in `src/lib.rs` is declared here.
"""

from typing import (
    Any,
    Dict,
    Generic,
    List,
    Literal,
    Optional,
    Protocol,
    Sequence,
    Tuple,
    TypeVar,
    Union,
    overload,
)
import numpy as np
import numpy.typing as npt

# Type aliases — `F = f64` is invariant in molrs-core; Python side must match.
ArrayF = npt.NDArray[np.float64]
ArrayBool = npt.NDArray[np.bool_]
ArrayU8 = npt.NDArray[np.uint8]
ArrayU32 = npt.NDArray[np.uint32]
ArrayI64 = npt.NDArray[np.int64]
TGraph = TypeVar("TGraph", bound="Graph")

FRAME_SCHEMA_VERSION: int

def _ffi_abi_token() -> tuple[str, str, str, str]:
    """FFI ABI handshake: (abi_line, version, frameref_name, forcefield_name)."""

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class BlockDtypeError(TypeError):
    """Raised by ``Block.insert`` for a non-numpy-representable column.

    The Rust Store holds only float / int / bool / str columns. Object-dtype,
    None-bearing, and ragged/mixed arrays are rejected fail-fast; the message
    names the column and the detected dtype. Subclasses ``TypeError``.
    """

# ---------------------------------------------------------------------------
# Simulation box
# ---------------------------------------------------------------------------

class Box:
    """Simulation box with periodic boundary conditions."""

    def __init__(
        self,
        h: ArrayF,
        origin: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> None: ...
    @staticmethod
    def cube(
        a: float,
        origin: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> Box: ...
    @staticmethod
    def ortho(
        lengths: ArrayF,
        origin: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> Box: ...
    @staticmethod
    def from_bounds(points: ArrayF, padding: ArrayF, pbc: Optional[ArrayBool] = None) -> Box: ...
    def volume(self) -> float: ...
    def lattice(self, index: int) -> ArrayF: ...
    @property
    def h(self) -> ArrayF: ...
    @property
    def inverse(self) -> ArrayF: ...
    @property
    def origin(self) -> ArrayF: ...
    @property
    def pbc(self) -> ArrayBool: ...
    @property
    def lengths(self) -> ArrayF: ...
    @property
    def angles(self) -> ArrayF: ...
    @staticmethod
    def matrix_from_lengths_angles(lengths: ArrayF, angles: ArrayF) -> ArrayF: ...
    @staticmethod
    def matrix_from_lengths_tilts(lengths: ArrayF, tilts: ArrayF) -> ArrayF: ...
    @staticmethod
    def restricted_matrix(matrix: ArrayF) -> ArrayF: ...
    @property
    def nearest_plane_distance(self) -> ArrayF: ...
    @property
    def bounds(self) -> ArrayF: ...
    def corners(self) -> ArrayF: ...
    def shortest_vector(self, r1: ArrayF, r2: ArrayF) -> ArrayF: ...
    def distance_squared(self, r1: ArrayF, r2: ArrayF) -> float: ...
    def distance(self, r1: ArrayF, r2: ArrayF) -> float: ...
    def to_frac(self, xyz: ArrayF) -> ArrayF: ...
    def to_cart(self, xyzs: ArrayF) -> ArrayF: ...
    def wrap(self, xyzu: ArrayF) -> ArrayF: ...
    def images(self, xyz: ArrayF) -> ArrayI64: ...
    def unwrap(self, xyz: ArrayF, images: ArrayI64) -> ArrayF: ...
    def delta(
        self, xyzu1: ArrayF, xyzu2: ArrayF, minimum_image: bool = False
    ) -> ArrayF: ...
    def distances(self, points1: ArrayF, points2: ArrayF) -> ArrayF: ...
    def pairwise_delta(self, points1: ArrayF, points2: ArrayF) -> ArrayF: ...
    def pairwise_distances(self, points1: ArrayF, points2: ArrayF) -> ArrayF: ...
    def transformed(self, transformation: ArrayF) -> Box: ...
    def isin(self, xyz: ArrayF) -> ArrayBool: ...

# ---------------------------------------------------------------------------
# Neighbor search
# ---------------------------------------------------------------------------

class NeighborList:
    """Neighbor-search engine: index coordinates, then materialize pairs.

    ``build`` / ``update`` index and enumerate nothing; ``neighbors`` returns
    the pair table. A self search is half-shell (each unordered pair once,
    ``i < j``).
    """

    def __init__(self, cutoff: float) -> None: ...
    @staticmethod
    def brute_force(cutoff: float) -> NeighborList: ...
    @property
    def cutoff(self) -> float: ...
    def build(self, points: ArrayF, box: Box) -> None: ...
    def update(self, points: ArrayF) -> None: ...
    def neighbors(self, dist_sq: bool = ..., disp: bool = ...) -> Neighbors: ...

class Neighbors:
    """Materialized pair table — read-only columns, one row per pair.

    ``dist_sq`` and ``disp`` are opt-in: a column the search was told not to
    store reads back as ``None``, never as a fabricated zero array.
    """

    def query_point_indices(self) -> ArrayU32: ...
    def point_indices(self) -> ArrayU32: ...
    def dist_sq(self) -> ArrayF | None: ...
    def disp(self) -> ArrayF | None: ...
    @property
    def n_pairs(self) -> int: ...
    @property
    def num_points(self) -> int: ...
    @property
    def num_query_points(self) -> int: ...
    @property
    def is_self_query(self) -> bool: ...

class NeighborQuery:
    """Cross-query against a fixed reference point set (directed)."""

    def __init__(self, box: Box, points: ArrayF, cutoff: float) -> None: ...
    @staticmethod
    def free(points: ArrayF, cutoff: float) -> NeighborQuery: ...
    def query(self, query_points: ArrayF) -> Neighbors: ...
    def query_self(self) -> Neighbors: ...

class VerletSkin:
    """A ``NeighborList`` with Verlet skin, for the MD integrators.

    ``neighbors`` must be an engine built with cutoff ``cutoff + skin``; it is
    **moved** into this object, and passing the skin into an integrator moves
    it again (afterwards every access raises "has already been moved").
    """

    def __init__(
        self,
        neighbors: NeighborList,
        cutoff: float,
        positions: ArrayF,
        box: Box,
        *,
        skin: float = 0.0,
        every: int = 1,
        delay: int = 0,
        check: bool = True,
    ) -> None: ...
    @property
    def cutoff(self) -> float: ...
    @property
    def skin(self) -> float: ...
    @property
    def num_edges(self) -> int: ...
    @property
    def rebuild_count(self) -> int: ...
    @property
    def ago(self) -> int: ...
    def update(self, positions: ArrayF) -> bool: ...
    def rebuild(self, positions: ArrayF) -> None: ...

# ---------------------------------------------------------------------------
# Block / Frame
# ---------------------------------------------------------------------------

class Block:
    """Heterogeneous column store (dict of typed numpy arrays)."""

    def __init__(self) -> None: ...
    def insert(self, key: str, array: npt.NDArray | Sequence[str]) -> None:
        """Store a column. Raises ``BlockDtypeError`` for object/None/ragged."""
        ...
    def view(self, key: str) -> npt.NDArray | list[str]: ...
    def __getitem__(self, key: str) -> npt.NDArray | list[str]: ...
    def __setitem__(self, key: str, array: npt.NDArray | Sequence[str]) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    @property
    def nrows(self) -> Optional[int]: ...
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    def __contains__(self, key: str) -> bool: ...
    def remove(self, key: str) -> None: ...
    def dtype(self, key: str) -> str: ...
    def has_f32(self, key: str) -> bool: ...
    def has_f64(self, key: str) -> bool: ...
    def has_int(self, key: str) -> bool: ...
    def has_uint(self, key: str) -> bool: ...
    def has_string(self, key: str) -> bool: ...

class MetaValue:
    """Exact-dtype frame metadata value."""

    def __init__(self, dtype: str, value: Any) -> None: ...
    @property
    def dtype(self) -> str: ...
    @property
    def value(self) -> bool | int | float | str | list[bool | int | float]: ...

class Frame:
    """Dictionary of Blocks with optional ``box`` and typed ``meta``."""

    def __init__(self) -> None: ...
    @staticmethod
    def from_dict(data: dict[str, Any]) -> "Frame": ...
    def __getitem__(self, key: str) -> Block: ...
    def __setitem__(self, key: str, value: Block) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    @property
    def box(self) -> Optional[Box]: ...
    @box.setter
    def box(self, value: Optional[Box]) -> None: ...
    @property
    def meta(self) -> dict[str, MetaValue]: ...
    @meta.setter
    def meta(self, value: dict[str, MetaValue]) -> None: ...
    def validate(self) -> None: ...

# ---------------------------------------------------------------------------
# Live Frame streaming (molrs::stream)
# ---------------------------------------------------------------------------

class ControlCommand:
    """A control message from a streaming viewer back to the producer."""

    @staticmethod
    def pause() -> "ControlCommand": ...
    @staticmethod
    def resume() -> "ControlCommand": ...
    @staticmethod
    def set_frame_rate(hz: float) -> "ControlCommand": ...
    @staticmethod
    def set_subset(atom_ids: Sequence[int]) -> "ControlCommand": ...
    @staticmethod
    def request_key_frame() -> "ControlCommand": ...
    @property
    def kind(
        self,
    ) -> Literal["pause", "resume", "set_frame_rate", "set_subset", "request_key_frame"]: ...
    @property
    def hz(self) -> Optional[float]: ...
    @property
    def atom_ids(self) -> Optional[List[int]]: ...
    def to_bytes(self, format: Literal["json", "msgpack"] = "json") -> bytes: ...
    @staticmethod
    def from_bytes(
        data: bytes, format: Literal["json", "msgpack"] = "json"
    ) -> "ControlCommand": ...

class Publisher:
    """WebSocket server broadcasting frames to connected viewers.

    Native-only: a Pyodide build compiles `molrs::stream::publisher` out, so this
    class is absent there.
    """

    def __init__(
        self,
        address: str = "127.0.0.1:0",
        *,
        format: Literal["msgpack", "json"] = "msgpack",
        buffer_size: int = 4,
        token: Optional[str] = None,
    ) -> None: ...
    @property
    def address(self) -> str: ...
    @property
    def client_count(self) -> int: ...
    def send(self, frame: Frame) -> None: ...
    def recv_command(self, timeout: float = 0.0) -> Optional[ControlCommand]: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Publisher": ...
    def __exit__(self, *exc: Any) -> bool: ...

# ---------------------------------------------------------------------------
# Regions (boolean compositions of primitive shapes)
# ---------------------------------------------------------------------------

class Sphere:
    """Solid sphere region."""

    def __init__(self, center: ArrayF, radius: float) -> None: ...
    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def __and__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __or__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __invert__(self) -> Region: ...

class HollowSphere:
    """Hollow sphere (spherical shell) region."""

    def __init__(
        self, center: ArrayF, inner_radius: float, outer_radius: float
    ) -> None: ...
    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def __and__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __or__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __invert__(self) -> Region: ...

class Cuboid:
    """Axis-aligned cuboid (box) region, exposed to Python as `molrs.Cuboid`.

    A point is inside when `origin[d] <= p[d] <= origin[d] + lengths[d]` on
    every axis. Supports `&` / `|` / `~` composition like the other regions.
    """

    def __init__(self, origin: ArrayF, lengths: ArrayF) -> None: ...
    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def __and__(
        self, other: Sphere | HollowSphere | Cuboid | Parallelepiped | Region
    ) -> Region: ...
    def __or__(
        self, other: Sphere | HollowSphere | Cuboid | Parallelepiped | Region
    ) -> Region: ...
    def __invert__(self) -> Region: ...

class Parallelepiped:
    """General parallelepiped (oblique box) geometric region.

    Pure containment — not a periodic ``SimBox``. Columns of ``h`` are the
    three edge vectors; fractional coordinates must lie in ``[0, 1)³``.
    """

    def __init__(self, h: ArrayF, origin: ArrayF) -> None: ...
    @staticmethod
    def ortho(lengths: ArrayF, origin: ArrayF) -> Parallelepiped: ...
    @staticmethod
    def cube(a: float, origin: ArrayF) -> Parallelepiped: ...
    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def volume(self) -> float: ...
    def __and__(
        self, other: Sphere | HollowSphere | Cuboid | Parallelepiped | Region
    ) -> Region: ...
    def __or__(
        self, other: Sphere | HollowSphere | Cuboid | Parallelepiped | Region
    ) -> Region: ...
    def __invert__(self) -> Region: ...

class Region:
    """Composed geometric region (result of &, |, ~ operators)."""

    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def __and__(
        self, other: Sphere | HollowSphere | Cuboid | Parallelepiped | Region
    ) -> Region: ...
    def __or__(
        self, other: Sphere | HollowSphere | Cuboid | Parallelepiped | Region
    ) -> Region: ...
    def __invert__(self) -> Region: ...

# ---------------------------------------------------------------------------
# Molecular graph
# ---------------------------------------------------------------------------

class Element:
    """Immutable chemical-element record backed by the Rust periodic table."""

    def __init__(self, identifier: str | int) -> None: ...
    @property
    def number(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def symbol(self) -> str: ...
    @property
    def mass(self) -> float: ...
    @property
    def vdw(self) -> float: ...
    @property
    def covalent(self) -> float: ...
    @classmethod
    def get_symbols(cls, identifiers: Iterable[str | int]) -> List[str]: ...
    @classmethod
    def get_atomic_number(cls, identifier: str | int) -> int: ...

class UnitsError(ValueError): ...

class Unit:
    @property
    def dimension(self) -> tuple[int, int, int, int, int, int, int]: ...
    @property
    def dimensionality(self) -> tuple[int, int, int, int, int, int, int]: ...
    def is_affine(self) -> bool: ...
    def factor_to(self, other: "Unit") -> float: ...
    def __rmul__(self, value: float) -> "Quantity": ...
    def __mul__(self, value: float) -> "Quantity": ...

class Quantity:
    @property
    def magnitude(self) -> float: ...
    @property
    def value(self) -> float: ...
    @property
    def units(self) -> Unit: ...
    @property
    def unit(self) -> Unit: ...
    def to(self, target: Unit | str) -> "Quantity": ...
    def to_base_units(self) -> "Quantity": ...
    def __add__(self, rhs: "Quantity") -> "Quantity": ...
    def __sub__(self, rhs: "Quantity") -> "Quantity": ...
    def __mul__(self, rhs: "Quantity" | float) -> "Quantity": ...
    def __rmul__(self, lhs: float) -> "Quantity": ...
    def __truediv__(self, rhs: "Quantity" | float) -> "Quantity": ...

class UnitPreset:
    def __init__(self, name: str) -> None: ...
    @staticmethod
    def real() -> UnitPreset: ...
    @property
    def name(self) -> str: ...
    def boltzmann(self) -> float: ...
    def coulomb(self) -> float: ...
    def mass(self) -> str: ...
    def length(self) -> str: ...
    def time(self) -> str: ...
    def energy(self) -> str: ...
    def temperature(self) -> str: ...
    def charge(self) -> str: ...
    def pressure(self) -> str: ...
    def velocity(self) -> str: ...
    def force(self) -> str: ...
    def density(self) -> str: ...

class UnitRegistry:
    def __init__(self, *, empty: bool = False) -> None: ...
    def parse(self, expression: str) -> Unit: ...
    def Unit(self, expression: str) -> Unit: ...
    def quantity(self, value: float, expression: str) -> Quantity: ...
    def Quantity(self, value: float, expression: str) -> Quantity: ...
    def define(
        self,
        name: str,
        factor: float,
        dimension: tuple[int, int, int, int, int, int, int],
        *,
        aliases: list[str] = ...,
        symbol: str | None = None,
        offset: float = 0.0,
        prefixable: bool = False,
    ) -> None: ...
    def define_lj_units(
        self, mass: Quantity, sigma: Quantity, epsilon: Quantity
    ) -> None: ...

class FragmentScaling:
    def __init__(
        self,
        name: str,
        q: float,
        mu: float,
        alpha: float,
        polarizable: bool = False,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def q(self) -> float: ...
    @property
    def mu(self) -> float: ...
    @property
    def alpha(self) -> float: ...
    @property
    def polarizable(self) -> bool: ...

def compute_k_ij(fr_i: FragmentScaling, fr_j: FragmentScaling, r: float) -> float: ...
def fragment_scaling_data() -> dict[str, FragmentScaling]: ...
def scale_lj(
    ff: ForceField,
    fragments: dict[
        str, tuple[list[str], list[tuple[float, float, float]], list[float]]
    ],
    frag_data: dict[str, FragmentScaling] | None = None,
    scale_sigma: bool = False,
) -> ForceField: ...
class Graph:
    """Domain-agnostic ECS *world*. Base of the hierarchy.

    Entities are stable opaque ``int`` handles (generational slotmap keys);
    removing one entity never invalidates another and a stale handle raises.
    Components live in aligned columns addressed by convention keys (see
    :data:`keys`); ``column`` exposes a zero-copy numpy view. Topology is a
    kind-tagged relation API (``register_kind`` / ``add_relation`` / …).

    Algorithms are **module-level free functions** (``translate`` / ``rotate`` /
    ``perceive_aromaticity`` / …), not methods. Chemistry vocabulary
    (``add_atom`` / ``add_bond`` / ``add_bead``) lives on the :class:`Atomistic`
    / :class:`CoarseGrain` leaves.

    Subclassable from Python — ``__new__`` accepts and ignores
    ``*args``/``**kwargs``.
    """

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    # --- entities ---
    def spawn(self) -> int: ...
    def despawn(self, h: int) -> None: ...
    def entities(self) -> List[int]: ...
    def has_entity(self, h: int) -> bool: ...
    @property
    def n_nodes(self) -> int: ...
    # --- components (convention keys; typed; missing/type-mismatch raises) ---
    def get(self, h: int, key: str) -> Union[int, float, str, None]: ...
    def set(self, h: int, key: str, value: Union[int, float, str]) -> None: ...
    def has(self, h: int, key: str) -> bool: ...
    def delete(self, h: int, key: str) -> None: ...
    def node_keys(self, h: int) -> List[str]: ...
    def column(self, key: str) -> ArrayF: ...
    def validity(self, key: str) -> ArrayBool: ...
    # --- relations (generic, kind-tagged) ---
    def register_kind(self, kind: str, arity: int) -> None: ...
    def kinds(self) -> List[str]: ...
    def add_relation(self, kind: str, nodes: List[int]) -> int: ...
    def relation_nodes(self, kind: str, rh: int) -> List[int]: ...
    def incident_relations(self, nh: int, kind: str) -> List[Tuple[int, int]]: ...
    def get_relation_prop(
        self, kind: str, rh: int, key: str
    ) -> Union[int, float, str, None]: ...
    def set_relation_prop(
        self, kind: str, rh: int, key: str, value: Union[int, float, str]
    ) -> None: ...
    def relation_keys(self, kind: str, rh: int) -> List[str]: ...
    def delete_relation_prop(self, kind: str, rh: int, key: str) -> None: ...
    def remove_relation(self, kind: str, rh: int) -> None: ...
    def n_relations(self, kind: str) -> int: ...
    def relation_ids(self, kind: str) -> List[int]: ...
    # --- adopt (zero-copy move) ---
    def adopt(self, other: "Graph") -> None: ...

class Atomistic(Graph):
    """All-atom leaf — holds a core ``Atomistic`` from construction.

    Registers the ``bonds``/``angles``/``dihedrals``/``impropers`` kinds and
    exposes the atom/bond/angle/dihedral/improper builders. The generic
    :class:`Graph` API operates on this leaf's own graph. Owns its
    :meth:`to_frame` / :meth:`from_frame` (domain conversions); it is never
    *converted* from a bare :class:`Graph`.
    """

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def add_atom(
        self,
        symbol: str,
        x: Optional[float] = None,
        y: Optional[float] = None,
        z: Optional[float] = None,
    ) -> int: ...
    def add_bond(self, a: int, b: int) -> int: ...
    def add_angle(self, i: int, j: int, k: int) -> int: ...
    def add_dihedral(self, i: int, j: int, k: int, l: int) -> int: ...
    def add_improper(self, i: int, j: int, k: int, l: int) -> int: ...
    def generate_topology(
        self,
        gen_angle: bool = True,
        gen_dihedral: bool = True,
        clear_existing: bool = False,
    ) -> tuple[int, int]: ...
    def topo_distances(
        self, source: int, max_hops: Optional[int] = None
    ) -> List[Tuple[int, int]]: ...
    @property
    def n_atoms(self) -> int: ...
    def max_ring_system_size(self) -> int: ...
    def to_frame(self) -> Frame: ...
    @staticmethod
    def from_frame(frame: Frame) -> "Atomistic": ...
    # --- graph-edit conveniences ---
    def remove_atom(self, handle: int) -> None: ...
    def remove_bond(self, handle: int) -> None: ...
    def set_bond_order(self, handle: int, order: float) -> None: ...
    def copy(self) -> "Atomistic": ...
    def merge(self, other: "Atomistic") -> Dict[int, int]: ...
    def replicate(self, n: int) -> "Atomistic": ...
    def induced_subgraph(
        self, nodes: List[int]
    ) -> Tuple["Atomistic", Dict[int, int]]: ...
    def extract_subgraph(
        self,
        centers: List[int],
        radius: int,
        *,
        regenerate_topology: bool = False,
        max_ring_size: int | None = None,
    ) -> "ExtractedSubgraph": ...
    # --- structural graph hash (Weisfeiler-Lehman) ---
    def structural_hash(self) -> int: ...
    def canonical_order(self) -> list[int]: ...
    def is_isomorphic(self, other: "Atomistic") -> bool: ...

class ExtractedSubgraph:
    """Result of :meth:`Atomistic.extract_subgraph` / :meth:`CoarseGrain.extract_subgraph`."""

    @property
    def graph(self) -> Union["Atomistic", "CoarseGrain"]: ...
    @property
    def boundary(self) -> List[int]: ...
    @property
    def parent_of(self) -> Dict[int, int]: ...
    @property
    def hops(self) -> Dict[int, int]: ...
    @property
    def node_map(self) -> Dict[int, int]: ...

class CoarseGrain(Graph):
    """Coarse-grained leaf — holds a core ``CoarseGrain`` from construction.

    ``add_bead`` writes ``bead_type``; registers the CG ``bonds`` kind. Owns its
    :meth:`to_frame` / :meth:`from_frame`.
    """

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def add_bead(
        self,
        bead_type: str,
        x: Optional[float] = None,
        y: Optional[float] = None,
        z: Optional[float] = None,
    ) -> int: ...
    def add_bond(self, a: int, b: int) -> int: ...
    @property
    def n_beads(self) -> int: ...
    def to_frame(self) -> Frame: ...
    @staticmethod
    def from_frame(frame: Frame) -> "CoarseGrain": ...
    def set_bead_members(self, bead: int, atoms: List[int]) -> None: ...
    def bead_members(self, bead: int) -> List[int]: ...
    def beads_of_atom(self, atom: int) -> List[int]: ...
    def copy(self) -> "CoarseGrain": ...
    def merge(self, other: "CoarseGrain") -> Dict[int, int]: ...
    def replicate(self, n: int) -> "CoarseGrain": ...
    def induced_subgraph(
        self, nodes: List[int]
    ) -> Tuple["CoarseGrain", Dict[int, int]]: ...
    def extract_subgraph(
        self, centers: List[int], radius: int
    ) -> "ExtractedSubgraph": ...
    # --- structural graph hash (Weisfeiler-Lehman) ---
    def structural_hash(self) -> int: ...
    def canonical_order(self) -> list[int]: ...
    def is_isomorphic(self, other: "CoarseGrain") -> bool: ...

class SmartsMatch:
    """One SMARTS embedding."""

    @property
    def atoms(self) -> list[int]: ...
    @property
    def mapping(self) -> dict[int, int]: ...
    def as_list(self) -> list[int]: ...
    def as_dict(self) -> dict[int, int]: ...

class SmartsPattern:
    """Compiled, atom-map-aware SMARTS query over an :class:`Atomistic`.

    Wraps the core Rust SMARTS engine (non-uniquified, RDKit
    ``uniquify=False``). Daylight atom maps (``[C:1]``) add no match constraint;
    pass ``mapped=True`` to :meth:`find_matches` for the legacy dict shortcut.
    """

    def __init__(self, smarts: str) -> None: ...
    def has_match(
        self,
        mol: Atomistic,
        *,
        labels: Optional[dict[int, str]] = None,
        root: Optional[int] = None,
    ) -> bool: ...
    @overload
    def find_matches(
        self,
        mol: Atomistic,
        *,
        labels: Optional[dict[int, str]] = None,
        root: Optional[int] = None,
        mapped: Literal[False] = False,
        limit: Optional[int] = None,
    ) -> List[SmartsMatch]: ...
    @overload
    def find_matches(
        self,
        mol: Atomistic,
        *,
        labels: Optional[dict[int, str]] = None,
        root: Optional[int] = None,
        mapped: Literal[True],
        limit: Optional[int] = None,
    ) -> List[dict[int, int]]: ...
    @property
    def num_query_atoms(self) -> int: ...
    def map_label(self, query_atom: int) -> Optional[int]: ...
    @property
    def max_bond_depth(self) -> int: ...
    @property
    def ring_primitives(self) -> List[Tuple[str, Optional[int]]]: ...

class Reaction:
    """Compiled Daylight reaction SMARTS (SMIRKS) transform.

    Parses ``reactants >> products`` (tolerating an ignored ``>agent>`` field),
    derives the graph edit from the atom-map diff, and applies it to one matched
    occurrence in place. Reacting atoms may carry SMARTS queries (RDKit-style);
    only concrete product atoms are addable.
    """

    def __init__(self, reaction_smarts: str) -> None: ...
    @property
    def reactant_patterns(self) -> List[SmartsPattern]: ...
    @property
    def forming_bonds(self) -> List[Tuple[int, int]]: ...
    def apply(
        self,
        mol: Atomistic,
        binding: dict[int, int],
        labels: Optional[dict[int, str]] = None,
        refresh: bool = True,
    ) -> List[int]: ...
    def apply_many(
        self,
        mol: Atomistic,
        bindings: list[dict[int, int]],
        labels: Optional[dict[int, str]] = None,
        refresh: bool = True,
    ) -> list[list[int]]: ...
    def apply_many_detailed(
        self,
        mol: Atomistic,
        bindings: list[dict[int, int]],
        labels: Optional[dict[int, str]] = None,
        refresh: bool = True,
    ) -> tuple[list[list[int]], list[list[int]]]: ...

# ---------------------------------------------------------------------------
# Systems — module-level free functions over a graph world
# ---------------------------------------------------------------------------

def translate(mol: Graph, delta: List[float]) -> None: ...
def rotate(
    mol: Graph, axis: List[float], angle: float, about: Optional[List[float]] = None
) -> None: ...
def scale(
    mol: Graph, factor: List[float], about: Optional[List[float]] = None
) -> None:
    """Scale node coordinates by a per-axis `factor` about an optional center
    (defaults to the origin). Pass `[s, s, s]` for a uniform scale. Generic
    geometry system."""
    ...
# ---------------------------------------------------------------------------
# Chemical perception — the builder (graph in / graph out, non-mutating)
# ---------------------------------------------------------------------------

class Perceive:
    """Chemical perception, as a builder.

    Every ``find_*`` clones the molecule, writes the perceived facts onto the clone
    as atom / bond props, and returns it — the input is never touched. Because the
    output is a graph, the finders compose.

    Props written: ``find_rings`` → ``is_in_ring`` / ``n_rings`` (atoms and bonds);
    ``find_aromaticity`` → ``is_aromatic`` on atoms, ``bond_type`` /
    ``bond_number`` on bonds; ``find_hydrogens`` → adds H atoms and bonds;
    ``find_stereo`` → ``stereo``; ``find_rotatable`` → ``is_rotatable``;
    ``find_bond_types`` → ``bcc_bond_type``; ``find_equivalence_classes`` →
    ``equiv_class``."""

    def __init__(self) -> None: ...
    def find_rings(self, mol: Atomistic) -> Atomistic: ...
    def find_aromaticity(self, mol: Atomistic) -> Atomistic: ...
    def find_hydrogens(self, mol: Atomistic) -> Atomistic: ...
    def find_stereo(self, mol: Atomistic) -> Atomistic: ...
    def find_rotatable(self, mol: Atomistic) -> Atomistic: ...
    def find_bond_types(self, mol: Atomistic) -> Atomistic: ...
    def find_equivalence_classes(self, mol: Atomistic) -> Atomistic: ...

# ---------------------------------------------------------------------------
# Field-name convention (mirrors molrs_core::keys)
# ---------------------------------------------------------------------------

class keys:
    """String constants for the component/field naming convention."""

    X: str
    Y: str
    Z: str
    COORDS: List[str]
    ELEMENT: str
    BEAD_TYPE: str
    CHARGE: str
    ORDER: str
    MASS: str
    TYPE: str
    ID: str
    MOL_ID: str
    SYMBOL: str
    NAME: str

# ---------------------------------------------------------------------------
# SMILES
# ---------------------------------------------------------------------------

class SmilesIR:
    """Intermediate representation of a parsed SMILES string."""

    @property
    def n_components(self) -> int: ...
    def to_atomistic(self) -> Atomistic: ...

# ---------------------------------------------------------------------------
# I/O — readers and writers
# ---------------------------------------------------------------------------

def read_block_csv(
    text: str, delimiter: str = ",", header: Optional[list[str]] = None
) -> Block: ...
def write_block_csv(
    block: Block, delimiter: str = ",", header: bool = True
) -> str: ...
def read_frame_bytes(
    data: bytes, format: Literal["msgpack", "json"] = "msgpack"
) -> Frame: ...
def write_frame_bytes(
    frame: Frame, format: Literal["msgpack", "json"] = "msgpack"
) -> bytes: ...
def read_pdb(path: str) -> Frame: ...
def read_pdb_trajectory(path: str) -> list[Frame]:
    """Read every MODEL of a PDB file as a trajectory (one Frame per MODEL)."""
    ...

def read_xyz(path: str) -> Frame: ...
def read_xyz_trajectory(path: str) -> list[Frame]: ...
def read_lammps(path: str) -> Frame: ...
def read_lammps_traj(path: str) -> list[Frame]: ...
def read_gro(path: str) -> list[Frame]: ...
def read_xsf(path: str) -> Frame: ...
def read_amber_inpcrd(path: str) -> Frame: ...
def read_inpcrd(path: str) -> Frame: ...
def read_amber_prmtop(path: str) -> Frame: ...
def read_prmtop(path: str) -> Frame: ...

class LAMMPSTrajReader:
    """Lazy, indexed reader for LAMMPS dump trajectory files.

    Frames are parsed on demand via byte-offset seeks; the index of
    ``ITEM: TIMESTEP`` markers is built on the first ``len()`` /
    ``__getitem__`` / ``read_frame`` call (or eagerly via ``build_index()``).

    Supports the molpy ``BaseTrajectoryReader`` surface: ``read_frame``,
    ``read_frames``, ``read_range``, ``read_all``, ``n_frames``, slicing,
    ``close()``, and use as a context manager.
    """

    def __init__(self, path: str) -> None: ...
    @property
    def n_frames(self) -> int: ...
    def build_index(self) -> None: ...
    def read_frame(self, index: int) -> Frame: ...
    def read_frames(self, indices: Sequence[int]) -> list[Frame]: ...
    def read_range(
        self, start: int = ..., stop: Optional[int] = ..., step: int = ...
    ) -> list[Frame]: ...
    def read_all(self) -> list[Frame]: ...
    def close(self) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: int) -> Frame: ...
    @overload
    def __getitem__(self, key: slice) -> list[Frame]: ...
    def __iter__(self) -> "LAMMPSTrajReader": ...
    def __next__(self) -> Frame: ...
    def __enter__(self) -> "LAMMPSTrajReader": ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...

def read_dcd(path: str) -> list[Frame]: ...

class DCDTrajReader:
    """Lazy, indexed reader for DCD trajectory files.

    Frames are parsed on demand via byte-offset seeks computed from the DCD
    header; the header is parsed on the first ``len()`` / ``__getitem__`` /
    ``read_step`` call (or eagerly via ``build_index()``).

    Supports the molpy ``BaseTrajectoryReader`` surface: ``read_frame``,
    ``read_frames``, ``read_range``, ``read_all``, ``n_frames``, slicing,
    ``close()``, and use as a context manager.
    """

    def __init__(self, path: str) -> None: ...
    @property
    def n_frames(self) -> int: ...
    def build_index(self) -> None: ...
    def read_frame(self, index: int) -> Frame: ...
    def read_frames(self, indices: Sequence[int]) -> list[Frame]: ...
    def read_range(
        self, start: int = ..., stop: Optional[int] = ..., step: int = ...
    ) -> list[Frame]: ...
    def read_all(self) -> list[Frame]: ...
    def close(self) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: int) -> Frame: ...
    @overload
    def __getitem__(self, key: slice) -> list[Frame]: ...
    def __iter__(self) -> "DCDTrajReader": ...
    def __next__(self) -> Frame: ...
    def __enter__(self) -> "DCDTrajReader": ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...

class XYZTrajReader:
    """Lazy, indexed reader for multi-frame XYZ trajectory files.

    The molrs-native counterpart to :func:`read_xyz_trajectory` (which eagerly
    returns ``list[Frame]``). Exposes the same molpy ``BaseTrajectoryReader``
    surface as :class:`DCDTrajReader`: ``read_frame``, ``read_frames``,
    ``read_range``, ``read_all``, ``n_frames``, slicing, ``close()``, and use
    as a context manager.
    """

    def __init__(self, path: str) -> None: ...
    @property
    def n_frames(self) -> int: ...
    def build_index(self) -> None: ...
    def read_frame(self, index: int) -> Frame: ...
    def read_frames(self, indices: Sequence[int]) -> list[Frame]: ...
    def read_range(
        self, start: int = ..., stop: Optional[int] = ..., step: int = ...
    ) -> list[Frame]: ...
    def read_all(self) -> list[Frame]: ...
    def close(self) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: int) -> Frame: ...
    @overload
    def __getitem__(self, key: slice) -> list[Frame]: ...
    def __iter__(self) -> "XYZTrajReader": ...
    def __next__(self) -> Frame: ...
    def __enter__(self) -> "XYZTrajReader": ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...

def read_chgcar_file(path: str) -> Frame: ...
def read_cube_file(path: str) -> Frame: ...
def write_cube_file(path: str, frame: Frame) -> None: ...
def write_pdb(path: str, frame: Frame) -> None: ...
def write_pdb_trajectory(path: str, frames: list[Frame]) -> None:
    """Write a list of Frames to a multi-MODEL PDB trajectory."""
    ...

def write_xyz(path: str, frame: Frame) -> None: ...
def write_lammps(path: str, frame: Frame) -> None: ...
def write_lammps_traj(path: str, frames: Sequence[Frame]) -> None: ...
def write_dcd(path: str, frames: Sequence[Frame]) -> None: ...
def write_gro(path: str, frame: Frame) -> None: ...
def write_xsf(path: str, frame: Frame) -> None: ...

# ---------------------------------------------------------------------------
# Signal processing
# ---------------------------------------------------------------------------

def signal_acf_fft(data: ArrayF, max_lag: int) -> ArrayF: ...
def signal_apply_window(data: ArrayF, window_type: str, axis: int = 0) -> ArrayF: ...
def signal_frequency_grid(n_fft: int, dt: float) -> ArrayF: ...

# ---------------------------------------------------------------------------
# Structure builders (molrs::builder)
# ---------------------------------------------------------------------------

class CarbonTubeBuilder:
    def __init__(
        self,
        n: int,
        m: int,
        *,
        length: Optional[float] = None,
        cells: Optional[int] = None,
        bond_length: float = 1.42,
        periodic: bool = False,
        vacuum: float = 10.0,
    ) -> None: ...
    def build(
        self, *, atom_type: Optional[str] = None, charge: float = 0.0
    ) -> Frame: ...
    def cell(self, *, vacuum: Optional[float] = None) -> Box: ...
    @property
    def n(self) -> int: ...
    @property
    def m(self) -> int: ...
    @property
    def cells(self) -> int: ...
    @property
    def bond_length(self) -> float: ...
    @property
    def periodic(self) -> bool: ...

class GrapheneBuilder:
    def __init__(
        self,
        nx: int,
        ny: int,
        *,
        bond_length: float = 1.42,
        vacuum: float = 10.0,
        periodic_xy: bool = True,
    ) -> None: ...
    def build(
        self, *, atom_type: Optional[str] = None, charge: float = 0.0
    ) -> Frame: ...
    def cell(self, *, vacuum: Optional[float] = None) -> Box: ...
    @property
    def nx(self) -> int: ...
    @property
    def ny(self) -> int: ...
    @property
    def bond_length(self) -> float: ...
    @property
    def periodic_xy(self) -> bool: ...

# ---------------------------------------------------------------------------
# 3D coordinate generation (embed)
# ---------------------------------------------------------------------------

class ConformerStageReport:
    """Per-stage report from the conformer generation pipeline."""

    @property
    def stage(self) -> str: ...
    @property
    def energy_before(self) -> Optional[float]: ...
    @property
    def energy_after(self) -> Optional[float]: ...
    @property
    def steps(self) -> int: ...
    @property
    def converged(self) -> bool: ...
    @property
    def elapsed_ms(self) -> int: ...

class ConformerReport:
    """Aggregate report from a conformer generation run."""

    @property
    def final_energy(self) -> Optional[float]: ...
    @property
    def warnings(self) -> list[str]: ...
    @property
    def stages(self) -> list[ConformerStageReport]: ...

class Conformer:
    """3D conformer generator.

    Construct with the desired generation parameters, then call
    :meth:`generate` to produce coordinates. Subclassable.
    """

    def __init__(
        self,
        speed: str = "medium",
        add_hydrogens: bool = True,
        seed: Optional[int] = None,
    ) -> None: ...
    def generate(self, mol: Atomistic) -> tuple[Atomistic, ConformerReport]: ...

def align_direction(
    mol: Graph,
    from_: Sequence[float],
    to: Sequence[float],
    from_dir: Optional[Sequence[float]] = None,
    to_dir: Optional[Sequence[float]] = None,
    flip: bool = False,
) -> None: ...

# ---------------------------------------------------------------------------
# Force field — Style / Type / Parameters model
#
# A ForceField owns category-keyed Styles; each Style owns named Types; each
# Type carries a Parameters view. The classes below are handle *views* over a
# parent ForceField — they read/write through to it rather than holding owned
# state.
# ---------------------------------------------------------------------------

class Parameters:
    """The parameter view of a :class:`Type` — keyword access plus the
    ``.kwargs`` mapping consumers read. The model is keyword-only, so ``.args``
    is always empty.
    """

    @property
    def args(self) -> list[Any]: ...
    @property
    def kwargs(self) -> dict[str, Any]: ...
    def get(self, key: str) -> Any: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Any]: ...
    def items(self) -> list[tuple[str, Any]]: ...

class Type:
    """Handle view of one force-field type over a :class:`ForceField`."""

    @property
    def name(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def endpoints(self) -> tuple["AtomType", ...]: ...
    @property
    def params(self) -> Parameters: ...
    def get(self, key: str) -> Any: ...
    def keys(self) -> list[str]: ...
    def items(self) -> list[tuple[str, Any]]: ...

class AtomType(Type):
    """A single atom type (endpoints only — no bonded arity)."""

class BondType(Type):
    """A bond type spanning two atom-type endpoints ``itom``-``jtom``."""

    @property
    def itom(self) -> AtomType: ...
    @property
    def jtom(self) -> AtomType: ...
    def matches(self, at1: str, at2: str) -> bool:
        """Test whether endpoint atom-type names ``at1``-``at2`` match this type."""
        ...

class AngleType(Type):
    """An angle type spanning three atom-type endpoints ``itom``-``jtom``-``ktom``."""

    @property
    def itom(self) -> AtomType: ...
    @property
    def jtom(self) -> AtomType: ...
    @property
    def ktom(self) -> AtomType: ...
    def matches(self, at1: str, at2: str, at3: str) -> bool:
        """Test whether endpoint atom-type names match this type."""
        ...

class DihedralType(Type):
    """A dihedral type spanning four atom-type endpoints ``itom``-``jtom``-``ktom``-``ltom``."""

    @property
    def itom(self) -> AtomType: ...
    @property
    def jtom(self) -> AtomType: ...
    @property
    def ktom(self) -> AtomType: ...
    @property
    def ltom(self) -> AtomType: ...
    def matches(self, at1: str, at2: str, at3: str, at4: str) -> bool:
        """Test whether endpoint atom-type names match this type."""
        ...

class ImproperType(Type):
    """An improper type spanning four atom-type endpoints ``itom``-``jtom``-``ktom``-``ltom``."""

    @property
    def itom(self) -> AtomType: ...
    @property
    def jtom(self) -> AtomType: ...
    @property
    def ktom(self) -> AtomType: ...
    @property
    def ltom(self) -> AtomType: ...
    def matches(self, at1: str, at2: str, at3: str, at4: str) -> bool:
        """Test whether endpoint atom-type names match this type."""
        ...

class PairType(Type):
    """A pair (non-bonded) type spanning two atom-type endpoints ``itom``-``jtom``."""

    @property
    def itom(self) -> AtomType: ...
    @property
    def jtom(self) -> AtomType: ...
    def matches(self, at1: str, at2: str) -> bool:
        """Test whether endpoint atom-type names ``at1``-``at2`` match this type."""
        ...

class Style:
    """Handle view of one style over a :class:`ForceField`."""

    @property
    def name(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def types(self) -> list[Type]: ...
    def get_types(self) -> list[Type]: ...
    def get_type_by_name(self, name: str) -> Optional[Type]: ...

class AtomStyle(Style):
    """Atom style — defines :class:`AtomType` entries.

    ``types`` / ``get_types`` / ``get_type_by_name`` are inherited from
    :class:`Style` and yield :class:`AtomType` instances at runtime.
    """

    def def_type(
        self, name: str, params: Optional[dict[str, Any]] = None
    ) -> AtomType: ...

class BondStyle(Style):
    """Bond style — defines :class:`BondType` entries.

    ``types`` / ``get_types`` / ``get_type_by_name`` are inherited from
    :class:`Style` and yield :class:`BondType` instances at runtime.
    """

    def def_type(
        self, itom: str, jtom: str, params: Optional[dict[str, Any]] = None
    ) -> BondType: ...

class AngleStyle(Style):
    """Angle style — defines :class:`AngleType` entries.

    ``types`` / ``get_types`` / ``get_type_by_name`` are inherited from
    :class:`Style` and yield :class:`AngleType` instances at runtime.
    """

    def def_type(
        self, itom: str, jtom: str, ktom: str, params: Optional[dict[str, Any]] = None
    ) -> AngleType: ...

class DihedralStyle(Style):
    """Dihedral style — defines :class:`DihedralType` entries.

    ``types`` / ``get_types`` / ``get_type_by_name`` are inherited from
    :class:`Style` and yield :class:`DihedralType` instances at runtime.
    """

    def def_type(
        self,
        itom: str,
        jtom: str,
        ktom: str,
        ltom: str,
        params: Optional[dict[str, Any]] = None,
    ) -> DihedralType: ...

class ImproperStyle(Style):
    """Improper style — defines :class:`ImproperType` entries.

    ``types`` / ``get_types`` / ``get_type_by_name`` are inherited from
    :class:`Style` and yield :class:`ImproperType` instances at runtime.
    """

    def def_type(
        self,
        itom: str,
        jtom: str,
        ktom: str,
        ltom: str,
        params: Optional[dict[str, Any]] = None,
    ) -> ImproperType: ...

class PairStyle(Style):
    """Pair (non-bonded) style — defines :class:`PairType` entries.

    ``types`` / ``get_types`` / ``get_type_by_name`` are inherited from
    :class:`Style` and yield :class:`PairType` instances at runtime.
    """

    def def_type(
        self,
        itom: str,
        jtom: Optional[str] = None,
        params: Optional[dict[str, Any]] = None,
    ) -> PairType: ...

class ForceField:
    @property
    def name(self) -> str: ...
    def style_names(self) -> list[str]: ...
    def to_potentials(self, frame: Frame) -> Potentials: ...

class OptReport:
    """Outcome of a geometry optimization (energy minimization)."""

    @property
    def converged(self) -> bool: ...
    @property
    def n_steps(self) -> int: ...
    @property
    def final_energy(self) -> float: ...
    @property
    def final_fmax(self) -> float: ...

class Potentials:
    """Composite of the one ``Potential`` concept — itself a potential.

    ``Potentials()`` is empty; ``push`` **moves** members in (an ``LJCut``,
    a ``md.Potential`` subclass instance, or another ``Potentials``).
    ``set_energy_scale`` applies a caller-computed numeric unit factor to the
    merged energy and forces (compute it with ``md.preset_energy_to_md`` /
    ``md.energy_to_md``); nothing applies it implicitly.
    """

    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def push(self, potential: Union["md.LJCut", "md.Potential", "Potentials"]) -> None: ...
    def set_energy_scale(self, scale: float) -> None: ...
    @property
    def energy_scale(self) -> float: ...
    def calc_energy_forces(
        self, arg: Union[Frame, ArrayF]
    ) -> tuple[float, ArrayF]: ...
    def calc_energy(self, arg: Union[Frame, ArrayF]) -> float: ...
    def calc_forces(self, arg: Union[Frame, ArrayF]) -> ArrayF: ...

class LBFGS:
    """L-BFGS geometry optimizer over a force-field Potential.

    Knobs live on ``__init__`` (no config object). Primary call is
    ``run(frame)``; array ranks dispatch single / batch coordinate paths.
    """

    def __init__(
        self,
        potentials: Potentials,
        *,
        fmax: float = 0.05,
        max_steps: int = 500,
        max_step: float = 0.2,
        memory: int = 8,
    ) -> None: ...
    @overload
    def run(self, frame: Frame) -> tuple[Frame, OptReport]: ...
    # (N, 3) or (3N,) -> single structure; (B, N, 3) -> homogeneous batch.
    @overload
    def run(self, coords: ArrayF) -> tuple[ArrayF, OptReport]: ...
    @overload
    def run(self, coords: ArrayF) -> tuple[ArrayF, list[OptReport]]: ...

class Typifier(Generic[TGraph]):
    def typify(self, mol: TGraph) -> TGraph: ...

class MMFF94Typifier(Typifier[Atomistic]):
    """MMFF94 (Halgren 1996) atom types, charges and bonded parameters.

    The variant is the class, never a flag. See ``MMFF94STypifier`` for the
    "static" parameter set.

    ``typify`` labels the graph; ``forcefield().to_potentials(frame)`` compiles
    it. There is no one-step ``build`` — MMFF walks the same route as every other
    force field."""

    def __init__(self) -> None: ...
    def typify(self, mol: Atomistic) -> Atomistic: ...
    def forcefield(self) -> ForceField: ...

class MMFF94STypifier(Typifier[Atomistic]):
    """MMFF94s (Halgren 1999) — the "static" set, for energy minimization.

    Differs from ``MMFF94Typifier`` only on delocalised trivalent nitrogen (MMFF
    numeric types 10 ``NC=O`` / 40 ``NC=C``): 11 out-of-plane rows and 42 torsion
    rows are re-parameterised so the nitrogen minimizes planar. ``typify`` bakes
    ``koop = +0.015`` (type 10) / ``+0.030`` (type 40) md*A*rad^-2 on those
    centres, where the improper kernel reads it as
    ``E_oop = 0.5 * 143.9325 * koop * chi**2`` (chi in radians). Every atom type
    and every bond / angle / stretch-bend / vdW / charge parameter is shared with
    MMFF94."""

    def __init__(self) -> None: ...
    def typify(self, mol: Atomistic) -> Atomistic: ...
    def forcefield(self) -> ForceField: ...

class OPLSAATypifier(Typifier[Atomistic]):
    def __init__(self, source: Any = None, *, strict: bool = True) -> None: ...
    def typify(self, mol: Atomistic) -> Atomistic: ...
    def forcefield(self) -> ForceField: ...

AtdParameterSet = Literal["bcc", "abcg2", "gas", "gaff", "gaff2", "amber", "sybyl"]

class AtdTypifier(Typifier[Atomistic]):
    """antechamber atom types — one rule engine over seven ``ATOMTYPE_*.DEF`` tables.

    ``parameter_set`` is the antechamber ``-at`` flag and is **required**: seven
    tables exist, they disagree, and there is no default. An atom no rule matches
    comes back labelled ``"DU"`` — the table's own catch-all row, not a fallback."""

    def __init__(self, *, parameter_set: AtdParameterSet) -> None: ...
    @property
    def parameter_set(self) -> AtdParameterSet: ...
    def typify(self, mol: Atomistic) -> Atomistic: ...

# ---------------------------------------------------------------------------
# Charge models — one trait, one calling convention
# ---------------------------------------------------------------------------

BccParameterSet = Literal["bcc", "abcg2"]

class ChargeModel(Protocol):
    """molecule (and optionally QM base charges) in, one float64 charge per atom out."""

    def needs_equivalencing(self) -> bool: ...
    def assign(self, mol: Atomistic, qm: Optional[ArrayF] = None) -> ArrayF: ...

class BccModel(ChargeModel):
    """AM1-BCC / ABCG2 bond-charge corrections.

    ``assign`` is the whole model: it averages the raw QM charges over the
    topological-equivalence classes (antechamber's ``-eq 1``) and then corrects
    them. ``correct`` is the correction stage alone, for base charges that are
    already equivalenced. The increments are pairwise antisymmetric, so the total
    charge is conserved to machine precision; nothing is renormalized."""

    def __init__(self, *, parameter_set: BccParameterSet) -> None: ...
    @property
    def parameter_set(self) -> BccParameterSet: ...
    def needs_equivalencing(self) -> bool: ...
    def assign(self, mol: Atomistic, qm: Optional[ArrayF] = None) -> ArrayF: ...
    def correct(self, mol: Atomistic, am1: ArrayF) -> ArrayF: ...

class MullikenModel(ChargeModel):
    """The pass-through: the QM charges it was handed, bit for bit."""

    def __init__(self) -> None: ...
    def needs_equivalencing(self) -> bool: ...
    def assign(self, mol: Atomistic, qm: Optional[ArrayF] = None) -> ArrayF: ...

class GasteigerModel(ChargeModel):
    """Gasteiger / PEOE charges (``antechamber -c gas``) — no QM input needed.

    ``qm`` is accepted and ignored, so that a caller holding an unknown model can
    call every model the same way."""

    def __init__(self) -> None: ...
    def needs_equivalencing(self) -> bool: ...
    def assign(self, mol: Atomistic, qm: Optional[ArrayF] = None) -> ArrayF: ...

def read_forcefield_xml(path: str) -> ForceField: ...
def read_forcefield_xml_str(xml: str) -> ForceField: ...
def read_opls_xml(path: str) -> ForceField: ...
def read_opls_xml_str(xml: str) -> ForceField: ...
def read_lammps_forcefield(path: str) -> ForceField: ...
def read_lammps_forcefield_str(text: str) -> ForceField: ...
def read_lammps_data_coeffs(
    coeffs_text: str,
    units: str = "real",
    atom_labels: dict[int, str] | None = None,
    bond_labels: dict[int, str] | None = None,
    angle_labels: dict[int, str] | None = None,
    dihedral_labels: dict[int, str] | None = None,
    improper_labels: dict[int, str] | None = None,
) -> ForceField: ...
def write_lammps_forcefield(
    path: str,
    forcefield: ForceField,
    precision: int = 6,
    skip_pair_style: bool = False,
    units: str = "real",
    atom_types: set[str] | None = None,
    bond_types: set[str] | None = None,
    angle_types: set[str] | None = None,
    dihedral_types: set[str] | None = None,
    improper_types: set[str] | None = None,
    type_ids: dict[str, int] | None = None,
) -> None: ...
def write_lammps_forcefield_str(
    forcefield: ForceField,
    precision: int = 6,
    skip_pair_style: bool = False,
    units: str = "real",
    atom_types: set[str] | None = None,
    bond_types: set[str] | None = None,
    angle_types: set[str] | None = None,
    dihedral_types: set[str] | None = None,
    improper_types: set[str] | None = None,
    type_ids: dict[str, int] | None = None,
) -> str: ...
def write_lammps_data_coeffs(
    forcefield: ForceField,
    precision: int = 6,
    units: str = "real",
    atom_types: set[str] | None = None,
    bond_types: set[str] | None = None,
    angle_types: set[str] | None = None,
    dihedral_types: set[str] | None = None,
    improper_types: set[str] | None = None,
    type_ids: dict[str, int] | None = None,
) -> str: ...
def intramolecular_pairs(frame: Frame) -> Block: ...
def extract_coords(frame: Frame) -> ArrayF: ...

# ---------------------------------------------------------------------------
# Record / Trajectory / Observables
# ---------------------------------------------------------------------------

class Trajectory:
    def __init__(
        self,
        frames: Sequence[Frame],
        step: Optional[ArrayI64] = None,
        time: Optional[ArrayF] = None,
    ) -> None: ...
    @staticmethod
    def from_frames(
        frames: Sequence[Frame],
        step: Optional[ArrayI64] = None,
        time: Optional[ArrayF] = None,
    ) -> Trajectory: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Frame: ...
    @property
    def frames(self) -> list[Frame]: ...
    @property
    def step(self) -> Optional[ArrayI64]: ...
    @property
    def time(self) -> Optional[ArrayF]: ...
    @staticmethod
    def read(path: str) -> Trajectory: ...
    def write(self, path: str) -> None: ...

_ObservableScalarData = npt.NDArray | float | int | bool | str | list[str]

class ScalarObservable:
    def __init__(
        self,
        name: str,
        data: _ObservableScalarData,
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def data(self) -> npt.NDArray | list[str] | str: ...
    @property
    def kind(self) -> str: ...

class VectorObservable:
    def __init__(
        self,
        name: str,
        data: _ObservableScalarData,
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def data(self) -> npt.NDArray | list[str] | str: ...
    @property
    def kind(self) -> str: ...

_AnyObservable = ScalarObservable | VectorObservable

class Observables:
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    def __contains__(self, name: str) -> bool: ...
    def get(self, name: str) -> Optional[_AnyObservable]: ...
    def add(self, observable: _AnyObservable) -> None: ...
    def add_scalar(
        self,
        name: str,
        data: _ObservableScalarData,
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
    ) -> ScalarObservable: ...
    def add_vector(
        self,
        name: str,
        data: _ObservableScalarData,
        description: str = "",
        unit: Optional[str] = None,
        axes: Optional[list[str]] = None,
        time_dependent: bool = False,
        sampling: Optional[str] = None,
        domain: Optional[str] = None,
        target: Optional[str] = None,
    ) -> VectorObservable: ...

_JsonDict = dict[str, Any]

class Record:
    """One record: `meta` plus at least one of `frame`, `system`, `status`.

    There is no record-root `parameters` section — scientific parameters belong
    under `system/parameters`, and method identity under `method`.
    """

    def __init__(self) -> None: ...
    def set_frame(self, frame: Frame) -> None: ...
    def set_system(self, frame: Frame) -> None: ...
    def add_frame(self, frame: Frame) -> None: ...
    def set_trajectory(self, trajectory: Trajectory) -> None: ...
    def set_forcefield(self, forcefield: ForceField) -> None: ...
    @staticmethod
    def read(path: str) -> Record: ...
    def write(self, path: str) -> None: ...
    def count_frames(self) -> int: ...
    @property
    def frame(self) -> Optional[Frame]: ...
    @property
    def system(self) -> Optional[Frame]: ...
    @property
    def trajectory(self) -> Optional[Trajectory]: ...
    @property
    def observables(self) -> Observables: ...
    @property
    def meta(self) -> _JsonDict: ...
    @meta.setter
    def meta(self, value: _JsonDict) -> None: ...
    @property
    def method(self) -> _JsonDict: ...
    @method.setter
    def method(self, value: _JsonDict) -> None: ...
    @property
    def status(self) -> _JsonDict: ...
    @status.setter
    def status(self, value: _JsonDict) -> None: ...
    @property
    def metrics(self) -> _JsonDict: ...
    @metrics.setter
    def metrics(self, value: _JsonDict) -> None: ...

# ---------------------------------------------------------------------------
# Analysis (compute)
#
# The Rust crate's unified `Compute` trait consumes batches of frames. Python
# wrappers accept either a single `Frame` or a `list[Frame]`; single-frame
# arguments return single results, lists return lists of results (aligned).
# ---------------------------------------------------------------------------

class RDFResult:
    """Radial distribution function g(r). Accumulated across all input frames."""

    @property
    def bin_centers(self) -> ArrayF: ...
    @property
    def rdf(self) -> ArrayF: ...
    @property
    def bin_edges(self) -> ArrayF: ...
    @property
    def n_r(self) -> ArrayF: ...
    @property
    def volume(self) -> float: ...
    @property
    def r_min(self) -> float: ...
    @property
    def n_points(self) -> int: ...
    @property
    def n_frames(self) -> int: ...

class Compute(Protocol):
    """The one analysis contract: ``compute(...)``. Presence-only (PEP 544)."""

    def compute(self, *args: Any, **kwargs: Any) -> Any: ...

class RDF:
    def __init__(self, n_bins: int, r_max: float, r_min: float = 0.0) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: Neighbors | Sequence[Neighbors],
    ) -> RDFResult: ...

class MSDResult:
    """MSD at a single time point."""

    @property
    def mean(self) -> float: ...
    @property
    def per_particle(self) -> ArrayF: ...

class MSDTimeSeries:
    """Time series of per-frame MSD values (frame 0 is the reference)."""

    @property
    def mean(self) -> ArrayF: ...
    @property
    def per_particle(self) -> ArrayF: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> MSDResult: ...

class MSD:
    def __init__(self) -> None: ...
    def compute(self, frames: Frame | Sequence[Frame]) -> MSDTimeSeries: ...

class ClusterResult:
    @property
    def num_clusters(self) -> int: ...
    @property
    def cluster_idx(self) -> ArrayI64: ...
    @property
    def cluster_sizes(self) -> list[int]: ...
    @property
    def cluster_keys(self) -> list[list[int]]: ...

class Cluster:
    def __init__(self, min_cluster_size: int) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: Neighbors | Sequence[Neighbors] | None = ...,
        keys: Sequence[int] | None = ...,
    ) -> ClusterResult | list[ClusterResult]: ...

class ClusterCentersResult:
    """Geometric cluster centers for one frame, shape `(num_clusters, 3)`."""

    @property
    def centers(self) -> ArrayF: ...
    def __len__(self) -> int: ...

class ClusterCenters:
    """Geometric (non-mass-weighted) cluster centers."""

    def __init__(self) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        clusters: ClusterResult | Sequence[ClusterResult],
    ) -> ClusterCentersResult | list[ClusterCentersResult]: ...

class CenterOfMassResult:
    @property
    def centers_of_mass(self) -> ArrayF: ...
    @property
    def cluster_masses(self) -> ArrayF: ...

class CenterOfMass:
    """Mass-weighted cluster centers."""

    def __init__(self, masses: Optional[ArrayF] = None) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        clusters: ClusterResult | Sequence[ClusterResult],
    ) -> CenterOfMassResult | list[CenterOfMassResult]: ...

class GyrationTensor:
    """Gyration tensor per cluster; requires geometric cluster centers."""

    def __init__(self) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        clusters: ClusterResult | Sequence[ClusterResult],
        centers: ClusterCentersResult | Sequence[ClusterCentersResult],
    ) -> ArrayF | list[ArrayF]: ...

class InertiaTensor:
    """Inertia tensor per cluster; requires COM results."""

    def __init__(self, masses: Optional[ArrayF] = None) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        clusters: ClusterResult | Sequence[ClusterResult],
        com: CenterOfMassResult | Sequence[CenterOfMassResult],
    ) -> ArrayF | list[ArrayF]: ...

class RadiusOfGyration:
    """Radius of gyration per cluster; requires COM results."""

    def __init__(self, masses: Optional[ArrayF] = None) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        clusters: ClusterResult | Sequence[ClusterResult],
        com: CenterOfMassResult | Sequence[CenterOfMassResult],
    ) -> ArrayF | list[ArrayF]: ...

class DescriptorRow:
    """1-D descriptor vector used as a PCA / k-means input row."""

    def __init__(self, values: ArrayF) -> None: ...
    def __len__(self) -> int: ...

class PcaResult:
    @property
    def coords(self) -> ArrayF: ...
    @property
    def variance(self) -> tuple[float, float]: ...

class Pca2:
    """Two-component PCA."""

    def __init__(self) -> None: ...
    def compute(self, rows: Sequence[DescriptorRow]) -> PcaResult: ...

class KMeansResult:
    @property
    def labels(self) -> npt.NDArray[np.int32]: ...
    def __len__(self) -> int: ...

class KMeans:
    """k-means over a PCA projection (2-D)."""

    def __init__(self, k: int, max_iter: int = 100, seed: int = 0) -> None: ...
    def compute(self, pca: PcaResult) -> KMeansResult: ...

# ---------------------------------------------------------------------------
# freud-ported analyzers (added in 0.0.17)
# ---------------------------------------------------------------------------

class Steinhardt:
    """Bond-orientational order parameters `q_ℓ` and `w_ℓ`."""

    def __init__(
        self,
        l: Sequence[int],
        average: bool = False,
        wl: bool = False,
        wl_normalize: bool = False,
    ) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: Neighbors | Sequence[Neighbors],
    ) -> list[dict]: ...

class Nematic:
    """Nematic order parameter via Q-tensor eigenvalue."""

    def __init__(self) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
    ) -> tuple[float, ArrayF, ArrayF, ArrayF]: ...

class Hexatic:
    """2-D hexatic order parameter `ψ_k`."""

    def __init__(self, k: int) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: Neighbors | Sequence[Neighbors],
    ) -> list[ArrayF]: ...

class SolidLiquid:
    """Frenkel-ten Wolde solid/liquid classifier."""

    def __init__(
        self, l: int, q_threshold: float = 0.7, n_threshold: int = 6
    ) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: Neighbors | Sequence[Neighbors],
    ) -> list[tuple[npt.NDArray[np.uint32], list[bool]]]: ...

class ClusterProperties:
    """Per-cluster size / center / gyration tensor aggregator."""

    def __init__(self) -> None: ...
    def with_masses(self, masses: Sequence[float]) -> ClusterProperties: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        clusters: Sequence[ClusterResult],
    ) -> list[dict]: ...

class LocalDensity:
    """Per-particle local number density in a sphere of radius r_max."""

    def __init__(self, r_max: float, diameter: float = 0.0) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: Neighbors | Sequence[Neighbors],
    ) -> list[tuple[ArrayF, ArrayF]]: ...

class GaussianDensity:
    """3-D Gaussian-smeared density grid."""

    def __init__(self, nx: int, ny: int, nz: int, sigma: float) -> None: ...
    def compute(self, frames: Frame | Sequence[Frame]) -> list[ArrayF]: ...

class BondOrder:
    """2-D (θ, φ) histogram of neighbor-bond vectors."""

    def __init__(self, n_theta: int, n_phi: int) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: Neighbors | Sequence[Neighbors],
    ) -> list[tuple[npt.NDArray[np.uint64], ArrayF, ArrayF, ArrayF]]: ...

class StaticStructureFactorDebye:
    """Closed-form Debye static structure factor S(k)."""

    def __init__(self, k_values: Sequence[float]) -> None: ...
    @staticmethod
    def linspace(k_min: float, k_max: float, n: int) -> StaticStructureFactorDebye: ...
    def compute(
        self, frames: Frame | Sequence[Frame]
    ) -> list[tuple[ArrayF, ArrayF, int]]: ...

class PMFTXY:
    """2-D (x, y) Pair Mode Fourier Transform."""

    def __init__(
        self, x_max: float, y_max: float, n_x: int, n_y: int
    ) -> None: ...
    def compute(
        self,
        frames: Frame | Sequence[Frame],
        nlists: Neighbors | Sequence[Neighbors],
    ) -> list[tuple[npt.NDArray[np.uint64], ArrayF, ArrayF]]: ...

# ---------------------------------------------------------------------------
# analysis-parity computes
# ---------------------------------------------------------------------------

class DistributionResult:
    """Geometric distribution result (ADF / DDF / distance-DF)."""

    @property
    def bin_centers(self) -> ArrayF: ...
    @property
    def bin_edges(self) -> ArrayF: ...
    @property
    def counts(self) -> ArrayF: ...
    @property
    def density(self) -> ArrayF: ...
    @property
    def density_sin_corrected(self) -> Optional[ArrayF]: ...
    @property
    def bin_width(self) -> float: ...
    @property
    def n_binned(self) -> float: ...
    @property
    def n_raw_samples(self) -> int: ...
    @property
    def n_frames(self) -> int: ...
    @property
    def angular(self) -> bool: ...

class AngleDistribution:
    """Angular distribution function (ADF) over `(i, j, k)` triplets."""

    def __init__(self, n_bins: int, min: float = 0.0, max: float = 180.0) -> None: ...
    def compute(self, frames: Frame | Sequence[Frame]) -> DistributionResult: ...

class DihedralDistribution:
    """Dihedral distribution function (DDF) over `(i, j, k, l)` quadruplets."""

    def __init__(
        self, n_bins: int, min: float = -180.0, max: float = 180.0
    ) -> None: ...
    def compute(self, frames: Frame | Sequence[Frame]) -> DistributionResult: ...

class DistanceDistribution:
    """Distance distribution function over `(i, j)` pairs."""

    def __init__(self, n_bins: int, min: float, max: float) -> None: ...
    def compute(self, frames: Frame | Sequence[Frame]) -> DistributionResult: ...

class VanHoveResult:
    """Van Hove correlation function G(r, t) (self + distinct)."""

    @property
    def r_edges(self) -> ArrayF: ...
    @property
    def r_centers(self) -> ArrayF: ...
    @property
    def lags(self) -> List[int]: ...
    @property
    def g_self(self) -> ArrayF: ...
    @property
    def g_distinct(self) -> ArrayF: ...
    @property
    def dr(self) -> float: ...
    @property
    def has_distinct(self) -> bool: ...

class AcfResult:
    """Autocorrelation curve, one entry per lag."""

    @property
    def lags(self) -> list[int]: ...
    @property
    def acf(self) -> npt.NDArray: ...

class Acf:
    """Time-autocorrelation of a vector series, averaged over all time origins.

    ``C(t) = 1/(N*(T-t)) * sum_i sum_tau v_i(tau).v_i(tau+t)`` — unbiased,
    Wiener-Khinchin (FFT). Not the same estimator as ``VACF``.
    """

    def __init__(self) -> None: ...
    def compute(self, series: npt.NDArray, max_lag: int) -> AcfResult: ...

class VanHove:
    """Van Hove correlation function G(r, t)."""

    def __init__(
        self, n_rbins: int, r_max: float, lags: Sequence[int], stride: int = 1
    ) -> None: ...
    def compute(self, frames: Frame | Sequence[Frame]) -> VanHoveResult: ...

class LegendreReorientationResult:
    """First/second Legendre reorientational TCFs C1(t), C2(t)."""

    @property
    def lags(self) -> List[int]: ...
    @property
    def c1(self) -> ArrayF: ...
    @property
    def c2(self) -> ArrayF: ...

class LegendreReorientation:
    """Legendre reorientational correlation of bond vectors."""

    def __init__(self, max_lag: int, stride: int = 1) -> None: ...
    def compute(
        self, frames: Frame | Sequence[Frame], pairs: ArrayI64
    ) -> LegendreReorientationResult: ...

class HBondCriterion:
    """Geometric hydrogen-bond criterion (Luzar–Chandler defaults)."""

    def __init__(
        self,
        dist_cutoff: float = 3.5,
        dist_kind: str = "donor_acceptor",
        angle_cutoff: float = 150.0,
    ) -> None: ...

class HBondsResult:
    """Per-frame hydrogen bonds."""

    @property
    def per_frame(self) -> List[List[Tuple[int, int, int, float, float]]]: ...
    @property
    def counts(self) -> List[int]: ...

class HBonds:
    """Detect hydrogen bonds per frame from explicit donors/acceptors."""

    def __init__(
        self,
        donors: ArrayI64,
        acceptors: ArrayI64,
        criterion: Optional[HBondCriterion] = None,
    ) -> None: ...
    def compute(self, frames: Frame | Sequence[Frame]) -> HBondsResult: ...

class SpatialDistributionResult:
    """Spatial distribution function on a body-fixed grid."""

    @property
    def counts(self) -> ArrayF: ...
    @property
    def density(self) -> ArrayF: ...
    @property
    def g_sdf(self) -> Optional[ArrayF]: ...
    @property
    def orientation(self) -> Optional[ArrayF]: ...
    @property
    def n(self) -> Tuple[int, int, int]: ...
    @property
    def extent(self) -> Tuple[float, float, float]: ...
    @property
    def voxel_volume(self) -> float: ...
    @property
    def n_frames(self) -> int: ...

class SpatialDistribution:
    """Spatial distribution function (SDF), Kabsch-aligned to a template."""

    def __init__(
        self,
        reference: Sequence[int],
        template: ArrayF,
        target: Sequence[int],
        n: Tuple[int, int, int],
        extent: Tuple[float, float, float],
        bulk_density: Optional[float] = None,
    ) -> None: ...
    def compute(
        self, frames: Frame | Sequence[Frame]
    ) -> SpatialDistributionResult: ...

class VoronoiCells:
    """Per-cell radical-Voronoi tessellation."""

    @property
    def volumes(self) -> ArrayF: ...
    @property
    def total_volume(self) -> float: ...
    def __len__(self) -> int: ...
    def neighbors(self, i: int) -> List[int]: ...

class RadicalVoronoi:
    """Radical (Laguerre) Voronoi tessellation — native periodic builder."""

    def __init__(self) -> None: ...
    def build(self, positions: ArrayF, radii: ArrayF, box: Box) -> VoronoiCells: ...

def voronoi_domains(
    cells: VoronoiCells, labels: Sequence[int]
) -> dict[str, Any]: ...
def voronoi_voids(
    cells: VoronoiCells, is_void: Sequence[bool], box_volume: float
) -> dict[str, Any]: ...

class VcdSpectrum:
    """Vibrational circular dichroism (VCD) spectrum transform."""

    def __init__(self) -> None: ...
    def fit(self, acf: ArrayF, dt_fs: float) -> dict[str, Any]: ...

class RoaSpectrum:
    """Raman optical activity (ROA) spectrum transform."""

    def __init__(
        self,
        incident_frequency_cm1: float = 0.0,
        temperature_k: float = 0.0,
        averaged: bool = False,
    ) -> None: ...
    def fit(
        self, acf_iso: ArrayF, acf_aniso: ArrayF, dt_fs: float
    ) -> dict[str, Any]: ...

class ResonanceRamanSpectrum:
    """Resonance-Raman spectrum transform."""

    def __init__(
        self,
        incident_frequency_cm1: float = 0.0,
        temperature_k: float = 0.0,
        averaged: bool = False,
    ) -> None: ...
    def fit(
        self, acf_iso: ArrayF, acf_aniso: ArrayF, dt_fs: float
    ) -> dict[str, Any]: ...

class CombinedDistributionResult:
    """Joint multi-axis distribution (flat row-major counts/density)."""

    @property
    def edges(self) -> List[ArrayF]: ...
    @property
    def centers(self) -> List[ArrayF]: ...
    @property
    def counts(self) -> ArrayF: ...
    @property
    def density(self) -> ArrayF: ...
    @property
    def binned(self) -> float: ...
    @property
    def n_raw_samples(self) -> int: ...
    @property
    def n_frames(self) -> int: ...
    @property
    def ndim(self) -> int: ...
    def flat_index(self, idx: Sequence[int]) -> int: ...
    def bin_width_product(self) -> float: ...

class CombinedDistribution:
    """Joint distribution over several geometric observables (combined-DF).

    Each axis is ``(kind, bins, min, max, sin_weight)`` where ``kind`` is
    ``"distance"`` / ``"angle"`` / ``"dihedral"``.
    """

    def __init__(
        self, axes: Sequence[Tuple[str, int, float, float, bool]]
    ) -> None: ...
    def compute(
        self, frames: Frame | Sequence[Frame]
    ) -> CombinedDistributionResult: ...

class DensityGrid:
    """Volumetric electron density on a voxel grid."""

    def __init__(
        self,
        origin: ArrayF,
        basis: ArrayF,
        dims: Tuple[int, int, int],
        density: ArrayF,
    ) -> None: ...

class MolecularMoments:
    """Per-molecule electromagnetic moments for one frame."""

    @property
    def charges(self) -> ArrayF: ...
    @property
    def dipoles(self) -> ArrayF: ...
    @property
    def references(self) -> ArrayF: ...

class VoronoiIntegration:
    """Integrate an electron density over radical-Voronoi cells into
    per-molecule charges + dipoles."""

    def __init__(self) -> None: ...
    def integrate(
        self,
        positions: ArrayF,
        radii: ArrayF,
        atomic_numbers: ArrayI64,
        atom_to_mol: ArrayI64,
        n_mol: int,
        grid: DensityGrid,
        box: Box,
    ) -> MolecularMoments: ...

def polarizability_finite_field(
    moments_zero: MolecularMoments,
    plus: MolecularMoments,
    minus: MolecularMoments,
    field: float,
) -> ArrayF: ...

# ---------------------------------------------------------------------------
# molrs.md — experimental in-process MD (mirrors molrs-python/src/md.rs).
# Submodule stubbed as a class namespace, following the `keys` precedent.
# ---------------------------------------------------------------------------

class md:
    """The ``_lib.md`` submodule: LJCut + NVE/Langevin integrators + the
    ``Potential`` base class.

    The engine is unit-agnostic — supply consistent units yourself. The
    conversion helpers target MD energy (amu·Å²/fs², :data:`MD_ENERGY`):
    ``energy_to_md`` converts an explicit unit string
    (``"kilocalorie_per_mole"``, ``"electron_volt"``, …),
    ``preset_energy_to_md`` a LAMMPS unit-style name (``"real"`` = kcal/mol),
    and ``kb_md()`` is Boltzmann's constant in MD units.
    """

    MD_ENERGY: str

    @staticmethod
    def kb_md() -> float: ...
    @staticmethod
    def energy_to_md(value: float, from_unit: str) -> float: ...
    @staticmethod
    def preset_energy_to_md(style: str) -> float: ...

    class MDState:
        """Dynamical state (pos/vel/forces ``(N, 3)`` float64 + potential energy).

        Fields are settable wholesale (``state.vel = v``; shape-validated).
        Getters return **copies**, so slice writes (``state.vel[:] = v``) are
        silently ineffective.
        """

        def __init__(
            self, pos: ArrayF, vel: ArrayF, forces: ArrayF, energy: float
        ) -> None: ...
        @property
        def pos(self) -> ArrayF: ...
        @pos.setter
        def pos(self, value: ArrayF) -> None: ...
        @property
        def vel(self) -> ArrayF: ...
        @vel.setter
        def vel(self, value: ArrayF) -> None: ...
        @property
        def forces(self) -> ArrayF: ...
        @forces.setter
        def forces(self, value: ArrayF) -> None: ...
        @property
        def energy(self) -> float: ...
        @energy.setter
        def energy(self, value: float) -> None: ...

    class LJCut:
        """LAMMPS ``pair_style lj/cut``: cut Lennard-Jones / Mie pair kernel
        (``n``/``m`` exponents), md's nonbond potential — the integrator loop
        feeds it the current neighbour pairs."""

        def __init__(
            self,
            epsilon: float,
            sigma: float,
            cutoff: float,
            *,
            n: int = 12,
            m: int = 6,
            shifted: bool = True,
            smeared: bool = False,
        ) -> None: ...
        @property
        def epsilon(self) -> float: ...
        @property
        def sigma(self) -> float: ...
        @property
        def cutoff(self) -> float: ...
        @property
        def n(self) -> int: ...
        @property
        def m(self) -> int: ...
        @property
        def shifted(self) -> bool: ...
        @property
        def smeared(self) -> bool: ...
        def pair_energy(
            self, r2: float, disp: Sequence[float]
        ) -> Optional[float]: ...
        def pair_force(
            self, r2: float, disp: Sequence[float]
        ) -> Optional[list[float]]: ...
        def pair_eval(
            self, r2: float, disp: Sequence[float]
        ) -> Optional[Tuple[float, list[float]]]: ...
        def eval(
            self, neighbors: VerletSkin, pos: ArrayF
        ) -> Tuple[float, ArrayF]: ...
        def eval_table(
            self, n_atoms: int, neighbors: Neighbors
        ) -> Tuple[float, ArrayF]: ...
        def eval_pairs(
            self,
            n_atoms: int,
            i: ArrayU32,
            j: ArrayU32,
            disp: ArrayF,
            dist_sq: Optional[ArrayF] = None,
        ) -> Tuple[float, ArrayF]: ...

    class Potential:
        """Abstract base class for user potentials: subclass it
        (``class MyPotential(molpy.md.Potential):``) and override
        ``calc_energy_forces``; molrs invokes the override under the GIL at
        every force evaluation (the NN/Torch seam). Return units must be
        consistent with everything else passed to the integrator. The base
        method raises ``NotImplementedError``."""

        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def calc_energy_forces(self, pos: ArrayF) -> Tuple[float, ArrayF]: ...

    class VelocityVerlet:
        """NVE velocity-Verlet. ``potential`` (``LJCut`` / ``Potentials`` /
        a ``Potential`` subclass) and ``neighbors`` (a ``VerletSkin``) are
        moved in; the loop feeds fresh pairs to the potential after each
        rebuild. ``LJCut`` requires ``neighbors=``."""

        def __init__(
            self,
            dt: float,
            *,
            potential: Union["md.LJCut", Potentials, "md.Potential"],
            neighbors: Optional[VerletSkin] = None,
            mass: Union[float, ArrayF],
        ) -> None: ...
        @property
        def dt(self) -> float: ...
        @property
        def removed_dof(self) -> int: ...
        @property
        def num_edges(self) -> Optional[int]: ...
        @property
        def rebuild_count(self) -> Optional[int]: ...
        @property
        def ago(self) -> Optional[int]: ...
        def initial(self, pos: ArrayF, vel: ArrayF) -> "md.MDState": ...
        def advance(self, state: Any) -> "md.MDState": ...
        def advance_n(self, state: Any, n_steps: int) -> "md.MDState": ...

    class Langevin:
        """BAOAB Langevin; ``kbt`` is an energy in your unit system
        (``kb_md() * T`` when integrating in MD units).

        ``advance`` draws noise from the internal seeded RNG; ``step`` takes
        the ``(N, 3)`` Gaussian draw explicitly."""

        def __init__(
            self,
            dt: float,
            *,
            gamma: float,
            kbt: float,
            potential: Union["md.LJCut", Potentials, "md.Potential"],
            neighbors: Optional[VerletSkin] = None,
            mass: Union[float, ArrayF],
            seed: int = 0,
        ) -> None: ...
        @property
        def dt(self) -> float: ...
        @property
        def gamma(self) -> float: ...
        @property
        def c1(self) -> float: ...
        @property
        def c2(self) -> float: ...
        @property
        def sigma(self) -> ArrayF: ...
        @property
        def inv_mass(self) -> ArrayF: ...
        @property
        def removed_dof(self) -> int: ...
        @property
        def num_edges(self) -> Optional[int]: ...
        @property
        def rebuild_count(self) -> Optional[int]: ...
        @property
        def ago(self) -> Optional[int]: ...
        def initial(self, pos: ArrayF, vel: ArrayF) -> "md.MDState": ...
        def step(self, state: Any, noise: ArrayF) -> "md.MDState": ...
        def advance(self, state: Any) -> "md.MDState": ...
        def advance_n(self, state: Any, n_steps: int) -> "md.MDState": ...
        def draw_noise(self, n_atoms: int) -> ArrayF: ...

    class MaxwellBoltzmann:
        """Velocity distribution at ``temperature`` K (optionally COM-free).

        A unit-dependent helper: K and amu in, Å/fs out (MD units via
        ``kb_md()``)."""

        def __init__(
            self, temperature: float, *, seed: int = 0, remove_com: bool = True
        ) -> None: ...
        @property
        def temperature(self) -> float: ...
        @property
        def seed(self) -> int: ...
        @property
        def remove_com(self) -> bool: ...
        def velocities(
            self, pos: ArrayF, mass: Union[float, ArrayF]
        ) -> ArrayF: ...
