"""Type stubs for molrs Python bindings."""

from typing import Optional, Sequence
import numpy as np
import numpy.typing as npt

# Type aliases
ArrayF = npt.NDArray[np.float32]
ArrayBool = npt.NDArray[np.bool_]
ArrayU8 = npt.NDArray[np.uint8]

class Box:
    """Simulation box with periodic boundary conditions."""

    def __init__(
        self,
        h: ArrayF,
        origin: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> None: ...
    @staticmethod
    def cube(
        a: float,
        origin: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> Box: ...
    @staticmethod
    def ortho(
        lengths: ArrayF,
        origin: Optional[ArrayF] = None,
        pbc: Optional[ArrayBool] = None,
    ) -> Box: ...
    def volume(self) -> float: ...
    def lattice(self, index: int) -> ArrayF: ...
    @property
    def h(self) -> ArrayF: ...
    @property
    def origin(self) -> ArrayF: ...
    @property
    def pbc(self) -> ArrayBool: ...
    def lengths(self) -> ArrayF: ...
    def to_frac(self, xyz: ArrayF) -> ArrayF: ...
    def to_cart(self, xyzs: ArrayF) -> ArrayF: ...
    def wrap(self, xyzu: ArrayF) -> ArrayF: ...
    def delta(
        self, xyzu1: ArrayF, xyzu2: ArrayF, minimum_image: bool = False
    ) -> ArrayF: ...
    def isin(self, xyz: ArrayF) -> ArrayBool: ...

class LinkedCell:
    """Linked-cell neighbor list for pairwise distance queries."""

    def __init__(self, points: ArrayF, cutoff: float, box: Box) -> None: ...
    def pairs(self) -> npt.NDArray[np.int64]: ...
    def update(self, points: ArrayF, box: Box) -> None: ...

class Block:
    """Heterogeneous column store (dict of typed numpy arrays)."""

    def __init__(self) -> None: ...
    def insert(self, key: str, array: npt.NDArray | Sequence[str]) -> None: ...
    def view(self, key: str) -> npt.NDArray | list[str]: ...
    @property
    def nrows(self) -> Optional[int]: ...
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    def __contains__(self, key: str) -> bool: ...
    def remove(self, key: str) -> None: ...
    def dtype(self, key: str) -> str: ...

class Frame:
    """Dictionary of Blocks with optional SimBox and metadata."""

    def __init__(self) -> None: ...
    def __getitem__(self, key: str) -> Block: ...
    def __setitem__(self, key: str, block: Block) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    @property
    def simbox(self) -> Optional[Box]: ...
    @simbox.setter
    def simbox(self, value: Optional[Box]) -> None: ...
    @property
    def meta(self) -> dict[str, str]: ...
    @meta.setter
    def meta(self, value: dict[str, str]) -> None: ...
    def validate(self) -> None: ...

def read_pdb(path: str) -> Frame: ...
def read_xyz(path: str) -> Frame: ...

class Sphere:
    """Solid sphere region."""

    def __init__(self, center: ArrayF, radius: float) -> None: ...
    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def __and__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __or__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __invert__(self) -> Region: ...

class HollowSphere:
    """Hollow sphere (spherical shell) region."""

    def __init__(
        self, center: ArrayF, inner_radius: float, outer_radius: float
    ) -> None: ...
    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def __and__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __or__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __invert__(self) -> Region: ...

class Region:
    """Composed geometric region (result of &, |, ~ operators)."""

    def contains(self, points: ArrayF) -> ArrayBool: ...
    def bounds(self) -> ArrayF: ...
    def __and__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __or__(self, other: Sphere | HollowSphere | Region) -> Region: ...
    def __invert__(self) -> Region: ...

class InsideBox:
    """Box constraint: atoms must be within a rectangular box."""

    def __init__(self, min: Sequence[float], max: Sequence[float]) -> None: ...
    def and_(
        self,
        other: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> MoleculeConstraint: ...

class InsideSphere:
    """Sphere constraint: atoms must be within a sphere."""

    def __init__(self, radius: float, center: Sequence[float]) -> None: ...
    def and_(
        self,
        other: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> MoleculeConstraint: ...

class OutsideSphere:
    """Outside sphere constraint."""

    def __init__(self, radius: float, center: Sequence[float]) -> None: ...
    def and_(
        self,
        other: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> MoleculeConstraint: ...

class AbovePlane:
    """Above plane constraint: n.x >= d."""

    def __init__(self, normal: Sequence[float], distance: float) -> None: ...
    def and_(
        self,
        other: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> MoleculeConstraint: ...

class BelowPlane:
    """Below plane constraint: n.x <= d."""

    def __init__(self, normal: Sequence[float], distance: float) -> None: ...
    def and_(
        self,
        other: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> MoleculeConstraint: ...

class MoleculeConstraint:
    """Composed constraint (result of .and_() operations)."""

    def and_(
        self,
        other: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> MoleculeConstraint: ...

class Target:
    """Describes one type of molecule to be packed."""

    def __init__(self, frame: Frame, count: int) -> None: ...
    @staticmethod
    def from_coords(
        positions: ArrayF, radii: ArrayF, count: int
    ) -> Target: ...
    def with_name(self, name: str) -> Target: ...
    def with_constraint(
        self,
        constraint: InsideBox | InsideSphere | OutsideSphere | AbovePlane | BelowPlane | MoleculeConstraint,
    ) -> Target: ...
    def with_maxmove(self, maxmove: int) -> Target: ...
    def with_center(self) -> Target: ...
    def without_centering(self) -> Target: ...
    def fixed_at(self, position: Sequence[float]) -> Target: ...
    @property
    def natoms(self) -> int: ...
    @property
    def count(self) -> int: ...
    @property
    def elements(self) -> list[str]: ...
    @property
    def is_fixed(self) -> bool: ...

class Packer:
    """Molecular packer (Packmol port)."""

    def __init__(
        self, tolerance: float = 2.0, precision: float = 0.01
    ) -> None: ...
    def with_tolerance(self, tolerance: float) -> Packer: ...
    def with_precision(self, precision: float) -> Packer: ...
    def with_maxit(self, maxit: int) -> Packer: ...
    def with_progress(self, enabled: bool) -> Packer: ...
    def pack(
        self,
        targets: list[Target],
        max_loops: int = 200,
        seed: Optional[int] = None,
    ) -> PackResult: ...

class PackResult:
    """Result of a packing run."""

    @property
    def positions(self) -> ArrayF: ...
    @property
    def elements(self) -> list[str]: ...
    @property
    def frame(self) -> Frame: ...
    @property
    def converged(self) -> bool: ...
    @property
    def fdist(self) -> float: ...
    @property
    def frest(self) -> float: ...
