//! CXX bridge exposing molrs to Atomiverse (C++).
//!
//! Stateless & raw-array: every call takes flat C++ buffers or a [`FrameRef`]
//! handle, and molrs does the work. The engine measures; molrs analyzes and
//! stores. One module per molrs owner:
//!
//! | Module    | molrs owner | Bridge surface |
//! |-----------|-------------|----------------|
//! | `frame`   | `store::Frame` (via `molrs_ffi::FrameRef`) | `FrameRef`, `frame_*` |
//! | `io`      | `io` | XYZ / ExtXYZ, `*.mrec` stores, `TrajectoryWriterRef` |
//! | `compute` | `compute` | `*Compute`, `*Accumulator` |
//! | `charge`  | `ff::charge` | `am1_bcc_assign_frame_from_base` |
//! | `region`  | `spatial::region` (via `molrs_ffi::RegionRef`) | `RegionRef`, `region_*` |
//!
//! The bridge declaration itself is generated by `build.rs` into
//! `src/bridge.rs`, which names every bridged item through the crate root.
//! The generated file is **committed** (and not ignored): Atomiverse's CMake
//! hands it to `corrosion_add_cxxbridge(... FILES bridge.rs)` and reads it at
//! configure time (`cmake/MolrsContract.cmake`, the WHAM surface probe),
//! before any cargo build has run on a fresh checkout. A build rewrites it
//! only when the generated text differs, so a stale copy shows up as a diff.

#[allow(clippy::too_many_arguments)]
mod bridge; // generated by build.rs

mod charge;
mod compute;
mod frame;
mod io;
mod region;

// The generated bridge resolves every item through `use super::*`.
use charge::*;
use compute::*;
use frame::*;
use io::*;
use region::*;

/// CXX capability bit: canonical block/meta/simbox Frame schema v2.
const CXX_CAP_FRAME_BLOCK_V2: u64 = 1 << 0;
/// CXX capability bit: canonical `molrs::core::Element` is exported at bridge root.
const CXX_CAP_ELEMENT: u64 = 1 << 1;
/// CXX capability bit: AM1 base-charge to BCC assignment is available.
const CXX_CAP_AM1_BCC: u64 = 1 << 2;
/// CXX capability bit: the streaming `*.mrec` trajectory writer is available.
const CXX_CAP_TRAJECTORY_WRITER: u64 = 1 << 3;
/// CXX capability bit: geometric regions (signed distance, membership, bounds,
/// boolean composition).
const CXX_CAP_REGION: u64 = 1 << 4;
const MOLRS_CXX_API_CAPABILITIES: u64 = CXX_CAP_FRAME_BLOCK_V2
    | CXX_CAP_ELEMENT
    | CXX_CAP_AM1_BCC
    | CXX_CAP_TRAJECTORY_WRITER
    | CXX_CAP_REGION;

/// Bitset of bridge surfaces present in this build.
fn cxx_api_capabilities() -> u64 {
    MOLRS_CXX_API_CAPABILITIES
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn capabilities_name_every_surface() {
        assert_eq!(
            cxx_api_capabilities(),
            CXX_CAP_FRAME_BLOCK_V2
                | CXX_CAP_ELEMENT
                | CXX_CAP_AM1_BCC
                | CXX_CAP_TRAJECTORY_WRITER
                | CXX_CAP_REGION
        );
    }
}
