//! CXX bridge exposing molrs I/O and analysis to Atomiverse (C++).
//!
//! Precision selected at compile time via `f64` Cargo feature,
//! matching Atomiverse's `ATV_REAL`.  build.rs generates `bridge.rs`
//! from `CXX_BRIDGE_SCHEMA`, substituting the concrete float type.

use std::fs::{File, OpenOptions};
use std::io::{BufWriter, Write};

use molrs::block::Block;
use molrs::frame::Frame;
use molrs::io::xyz::write_xyz_frame;
use molrs::region::simbox::SimBox;
use molrs::types::F;
use ndarray::{Array1, Array2, ArrayD};

// Generated by build.rs from CXX_BRIDGE_SCHEMA
mod bridge;

// ── Element lookup ───────────────────────────────────────────────────────────

fn symbol_for_z(z: i32) -> &'static str {
    match z {
        1 => "H",  2 => "He", 3 => "Li", 4 => "Be", 5 => "B",  6 => "C",
        7 => "N",  8 => "O",  9 => "F",  10 => "Ne", 11 => "Na", 12 => "Mg",
        13 => "Al", 14 => "Si", 15 => "P", 16 => "S", 17 => "Cl", 18 => "Ar",
        _ => "X",
    }
}

// ── AtvMolRec ────────────────────────────────────────────────────────────────

pub struct AtvMolRec {
    symbols: Vec<String>,
    x: Vec<F>, y: Vec<F>, z: Vec<F>,
    box_mat: [F; 9],
    fields: Vec<(String, Vec<F>)>,
    scalars: Vec<(String, f64)>,
    strings: Vec<(String, String)>,
    frames: Vec<Frame>,
}

impl AtvMolRec {
    fn new() -> Self {
        Self {
            symbols: Vec::new(),
            x: Vec::new(), y: Vec::new(), z: Vec::new(),
            box_mat: [0.0 as F; 9],
            fields: Vec::new(), scalars: Vec::new(), strings: Vec::new(),
            frames: Vec::new(),
        }
    }
    fn clear_staging(&mut self) {
        self.symbols.clear();
        self.x.clear(); self.y.clear(); self.z.clear();
        self.box_mat = [0.0 as F; 9];
        self.fields.clear(); self.scalars.clear(); self.strings.clear();
    }
    /// Build a molrs Frame by taking ownership of staging data (no clones).
    fn build_frame(&mut self) -> Frame {
        let mut atoms = Block::new();
        atoms.insert("element", Array1::from_vec(std::mem::take(&mut self.symbols)).into_dyn() as ArrayD<String>).unwrap();
        atoms.insert("x", Array1::from_vec(std::mem::take(&mut self.x)).into_dyn()).unwrap();
        atoms.insert("y", Array1::from_vec(std::mem::take(&mut self.y)).into_dyn()).unwrap();
        atoms.insert("z", Array1::from_vec(std::mem::take(&mut self.z)).into_dyn()).unwrap();
        for (name, vals) in self.fields.drain(..) {
            atoms.insert(name.as_str(), Array1::from_vec(vals).into_dyn()).unwrap();
        }
        let mut frame = Frame::new();
        frame.insert("atoms", atoms);
        let h = Array2::from_shape_vec((3, 3), self.box_mat.to_vec()).unwrap();
        if let Ok(sb) = SimBox::new(h, Array1::zeros(3), [true, true, true]) {
            frame.simbox = Some(sb);
        }
        for (k, v) in self.scalars.drain(..) { frame.meta.insert(k, format!("{}", v)); }
        for (k, v) in self.strings.drain(..) { frame.meta.insert(k, v); }
        frame
    }
}

// ── MolRec ───────────────────────────────────────────────────────────────────

fn molrec_new() -> Box<AtvMolRec> { Box::new(AtvMolRec::new()) }

fn molrec_set_geometry(rec: &mut AtvMolRec, type_id: &[i32],
    x: &[F], y: &[F], z: &[F], box_mat: &[F])
{
    let n = type_id.len();
    rec.symbols = type_id.iter().map(|&z| symbol_for_z(z).to_string()).collect();
    rec.x = x[..n].to_vec(); rec.y = y[..n].to_vec(); rec.z = z[..n].to_vec();
    if box_mat.len() >= 9 { rec.box_mat.copy_from_slice(&box_mat[..9]); }
}

fn molrec_add_field(rec: &mut AtvMolRec, name: &str, values: &[F]) {
    rec.fields.push((name.to_string(), values.to_vec()));
}
fn molrec_add_scalar(rec: &mut AtvMolRec, name: &str, value: f64) {
    rec.scalars.push((name.to_string(), value));
}
fn molrec_add_string(rec: &mut AtvMolRec, name: &str, value: &str) {
    rec.strings.push((name.to_string(), value.to_string()));
}
fn molrec_commit_frame(rec: &mut AtvMolRec) {
    let frame = rec.build_frame(); // takes ownership via mem::take/drain
    rec.frames.push(frame);
    rec.box_mat = [0.0 as F; 9];
}
fn molrec_clear(rec: &mut AtvMolRec) {
    rec.frames.clear(); rec.clear_staging();
}
fn molrec_n_frames(rec: &AtvMolRec) -> i32 { rec.frames.len() as i32 }

// ── XYZ I/O ──────────────────────────────────────────────────────────────────

fn xyz_write(path: &str, rec: &AtvMolRec) {
    let f = File::create(path).expect("xyz_write: create");
    let mut w = BufWriter::new(f);
    for frame in &rec.frames { write_xyz_frame(&mut w, frame).unwrap(); }
}
fn xyz_write_ext(path: &str, rec: &AtvMolRec) { xyz_write(path, rec); }
fn xyz_append(path: &str, rec: &AtvMolRec) {
    if rec.frames.is_empty() { return; }
    let f = OpenOptions::new().create(true).append(true).open(path).expect("xyz_append: open");
    let mut w = BufWriter::new(f);
    write_xyz_frame(&mut w, rec.frames.last().unwrap()).unwrap();
}
fn xyz_append_ext(path: &str, rec: &AtvMolRec) { xyz_append(path, rec); }

fn trajectory_append(path: &str, type_id: &[i32], x: &[F], y: &[F], z: &[F], step: i32) {
    let n = type_id.len();
    let f = OpenOptions::new().create(true).append(true).open(path).expect("traj: open");
    let mut w = BufWriter::new(f);
    writeln!(w, "{}", n).unwrap();
    writeln!(w, "Step {}", step).unwrap();
    for i in 0..n { writeln!(w, "{}  {:.6}  {:.6}  {:.6}", type_id[i], x[i], y[i], z[i]).unwrap(); }
}

fn molrec_print_summary(rec: &AtvMolRec) {
    if rec.frames.is_empty() { return; }
    let frame = rec.frames.last().unwrap();
    let meta = &frame.meta;
    let method = meta.get("method").map(|s| s.as_str()).unwrap_or("?");
    let energy: f64 = meta.get("energy").and_then(|s| s.parse().ok()).unwrap_or(0.0);
    let iters: i32 = meta.get("iterations").and_then(|s| s.parse().ok()).unwrap_or(0);
    let na: i32 = meta.get("n_alpha").and_then(|s| s.parse().ok()).unwrap_or(0);
    let nb: i32 = meta.get("n_beta").and_then(|s| s.parse().ok()).unwrap_or(0);
    let sc: f64 = meta.get("spin_contamination").and_then(|s| s.parse().ok()).unwrap_or(0.0);
    println!();
    println!("\u{2500}\u{2500}\u{2500} {} Molecular Record \u{2500}{}", method, "\u{2500}".repeat(39));
    println!("  Energy:         {:+.10} Hartree", energy);
    println!("  Iterations:     {}", iters);
    if method == "UHF" {
        println!("  Electrons:      {} alpha, {} beta  (2S+1 = {})", na, nb, na - nb + 1);
        println!("  Spin contam.:   {:.6}  (<S^2> - S*(S+1))", sc);
    } else {
        println!("  Electrons:      {}  (closed-shell)", na + nb);
    }
    if let Some(atoms) = frame.get("atoms") {
        if let Some(charges) = atoms.get_float("charge") {
            let spins = atoms.get_float("spin_density");
            let elems = atoms.get_string("element");
            println!("\n  Mulliken population analysis:");
            println!("  {:<4}  {:<4}  {:>10}  {:>10}", "Atom", "Sym", "Charge", "SpinDens");
            println!("  {:<4}  {:<4}  {:>10}  {:>10}", "----", "---", "----------", "----------");
            let mut tot = 0.0 as F;
            for a in 0..charges.len() {
                let sym = elems.and_then(|e| e.as_slice_memory_order())
                    .and_then(|s: &[String]| s.get(a)).map(|s| s.as_str()).unwrap_or("X");
                let q = charges[[a]]; let s = spins.map(|sv| sv[[a]]).unwrap_or(0.0 as F);
                println!("  {:<4}  {:<4}  {:+10.6}  {:+10.6}", a, sym, q, s);
                tot += q;
            }
            println!("  {:<4}  {:<4}  {:+10.6}", "Tot", "", tot);
        }
    }
    println!("{}\n", "\u{2500}".repeat(57));
}

// ── RDF — opaque handle wrapping molrs::compute::rdf::RDF ────────────────────

use molrs::compute::rdf::RDF as RdfCompute;

/// Opaque CXX handle.  Wraps molrs's `RDF` (bin config) plus a running
/// histogram for the accumulate-per-step pattern used by CUDA observers.
pub struct Rdf {
    inner: RdfCompute,
    histogram: Vec<i64>,
}

fn rdf_new(n_bins: i32, r_max: f64) -> Box<Rdf> {
    let n = n_bins as usize;
    let inner = RdfCompute::new(n, r_max as F);
    Box::new(Rdf { inner, histogram: vec![0i64; n] })
}

fn rdf_accumulate(rdf: &mut Rdf, distances: &[F], n_pairs: i32) {
    let bin_width = rdf.inner.bin_width();
    let n_bins = rdf.histogram.len();
    for i in 0..n_pairs as usize {
        let bin = (distances[i] / bin_width) as usize;
        if bin < n_bins { rdf.histogram[bin] += 1; }
    }
}

fn rdf_write(rdf: &Rdf, path: &str, n_samples: i32, n_atoms: i32, box_vol: f64) {
    let f = File::create(path).expect("rdf_write: create");
    let mut w = BufWriter::new(f);
    writeln!(w, "# r [Angstrom]   g(r)").unwrap();
    let n = n_atoms as f64;
    let rho = n / box_vol;
    let pi = std::f64::consts::PI;
    let bw = rdf.inner.bin_width() as f64;
    for i in 0..rdf.histogram.len() {
        let r = (i as f64 + 0.5) * bw;
        let r_lo = i as f64 * bw;
        let r_hi = (i as f64 + 1.0) * bw;
        let shell = (4.0 / 3.0) * pi * (r_hi.powi(3) - r_lo.powi(3));
        let ideal = n_samples as f64 * n * rho * shell;
        let gr = if ideal > 0.0 { 2.0 * rdf.histogram[i] as f64 / ideal } else { 0.0 };
        writeln!(w, "{:.6}  {:.6}", r, gr).unwrap();
    }
}
