//! AM1-BCC regression tests against AmberTools25 `antechamber -c bcc`.
//!
//! molrs owns the BCC half of AM1-BCC: bond-type perception, atom typing, and
//! the correction table. AM1 itself is Atomiverse's job, so every test here
//! FEEDS the AM1 base charges in and asserts only on what molrs must produce.
//!
//! *Feeding* them is now the whole API rather than a costume: the charges arrive
//! as a `&[f64]` argument to [`BccModel::correct`], not through a faked
//! `AM1ChargeBackend` whose `mol` parameter no implementor ever read. The three
//! implementors that existed were all constant-carriers, so the seam was on
//! backwards; this file is what it looked like from the test side, and the
//! `SuppliedAM1` shim it used to need is gone with the trait.
//!
//! The oracle (`antechamber_oracle.rs`) is generated by running the real
//! antechamber binary; see `scripts/gen_am1bcc_oracle.py`.
//!
//! The tests are layered so a failure localizes the broken stage:
//!
//!   L1 bond-type perception   (order, aromatic) -> BCC bond type 1/2/3/7/8/9
//!   L2 atom typing            + ATOMTYPE_BCC.DEF rules -> BCC atom type
//!   L3 correction application  am1 + types      -> final AM1-BCC charges
//!   L4 full pipeline           molecule + am1   -> final AM1-BCC charges
//!
//! L3 is the "table lookup is sound" test: it hands molrs antechamber's own
//! types, so it isolates the correction arithmetic from the perception.
//! L4 is the real gate: molrs perceives everything itself.
//!
//! The ABCG2 half of the same oracle, the `ChargeModel` trait the two families
//! share with Mulliken, and the charge-conservation contract live one module over
//! in `ff/charge/`, which is where the models now live.

use molrs::ff::charge::{BccModel, BccParameterSet};
use molrs::ff::typifier::am1bcc::{BCCAtomTypifier, BCCCorrectionTable, BCCCorrector};
use molrs::perceive::bond_type::BCC_BOND_TYPE;
use molrs::store::keys;
use molrs::{AtomId, Atomistic};

use super::antechamber_oracle::{AntechamberCase, CASES};

/// antechamber writes charges with 4 significant decimals; the BCC increments
/// in BCCPARM.DAT carry 4. Anything above 1e-4 is a real disagreement, not
/// formatting.
const CHARGE_TOL: f64 = 1.0e-4;

/// Build the molecule from the INPUT half of a case: element, coords, bond
/// order, aromatic flag. This is deliberately what a user has after reading a
/// mol2/SDF — not antechamber's answers.
fn build(case: &AntechamberCase) -> (Atomistic, Vec<AtomId>) {
    let mut mol = Atomistic::new();
    let ids: Vec<AtomId> = case
        .elements
        .iter()
        .zip(case.xyz)
        .map(|(el, [x, y, z])| mol.add_atom_xyz(el, *x, *y, *z))
        .collect();
    for (aid, fc) in ids.iter().zip(case.formal_charges) {
        mol.set_atom(*aid, "formal_charge", *fc)
            .expect("set formal_charge");
    }
    for (i, j, order, aromatic) in case.bonds {
        let bid = mol.add_bond(ids[*i], ids[*j]).expect("add bond");
        mol.set_bond_prop(bid, keys::ORDER, *order)
            .expect("set bond order");
        if *aromatic {
            mol.set_bond_prop(bid, "is_aromatic", true)
                .expect("set aromatic");
        }
    }
    (mol, ids)
}

/// Overlay antechamber's own BCC atom/bond types, bypassing molrs perception.
fn apply_reference_types(mol: &mut Atomistic, ids: &[AtomId], case: &AntechamberCase) {
    for (aid, t) in ids.iter().zip(case.bcc_atom_types) {
        mol.set_atom(*aid, keys::TYPE, *t)
            .expect("set bcc atom type");
    }
    let by_pair: std::collections::HashMap<(usize, usize), i32> = case
        .bcc_bond_types
        .iter()
        .map(|(i, j, t)| ((*i.min(j), *i.max(j)), *t))
        .collect();
    let bond_ids: Vec<_> = mol.bonds().map(|(bid, b)| (bid, b.nodes)).collect();
    let index: std::collections::HashMap<AtomId, usize> = ids
        .iter()
        .copied()
        .enumerate()
        .map(|(i, a)| (a, i))
        .collect();
    for (bid, nodes) in bond_ids {
        let (a, b) = (index[&nodes[0]], index[&nodes[1]]);
        let t = by_pair[&(a.min(b), a.max(b))];
        mol.set_bond_prop(bid, BCC_BOND_TYPE, t)
            .expect("set bcc bond type");
    }
}

fn report(label: &str, failures: &[String], total: usize) {
    if failures.is_empty() {
        return;
    }
    panic!(
        "{label}: {}/{total} molecules disagree with antechamber\n{}",
        failures.len(),
        failures.join("\n")
    );
}

// ── L1: BCC bond-type perception ────────────────────────────────────────────
// (bond order, aromatic flag) -> BCC bond type.
// 7 = aromatic single, 8 = aromatic double, 9 = delocalized (carboxylate,
// nitro, ...). molrs must derive these the way antechamber's bondtype.c does.
#[test]
fn bcc_bond_types_match_antechamber() {
    let mut failures = Vec::new();
    for case in CASES {
        let (mol, ids) = build(case);
        let typed = match BCCAtomTypifier::bcc().typify(&mol) {
            Ok(t) => t,
            Err(e) => {
                failures.push(format!("  {:22} ERROR {e}", case.name));
                continue;
            }
        };
        let index: std::collections::HashMap<AtomId, usize> = ids
            .iter()
            .copied()
            .enumerate()
            .map(|(i, a)| (a, i))
            .collect();
        let want: std::collections::HashMap<(usize, usize), i32> = case
            .bcc_bond_types
            .iter()
            .map(|(i, j, t)| ((*i.min(j), *i.max(j)), *t))
            .collect();
        let mut wrong = Vec::new();
        for (_, bond) in typed.bonds() {
            let (a, b) = (index[&bond.nodes[0]], index[&bond.nodes[1]]);
            let key = (a.min(b), a.max(b));
            let got = bond.props.get(BCC_BOND_TYPE).and_then(|v| match v {
                molrs::system::molgraph::PropValue::Int(v) => Some(*v),
                molrs::system::molgraph::PropValue::F64(v) => Some(v.round() as i32),
                _ => None,
            });
            if got != Some(want[&key]) {
                wrong.push(format!("{a}-{b}: got {got:?} want {}", want[&key]));
            }
        }
        if !wrong.is_empty() {
            failures.push(format!(
                "  {:22} {} bonds wrong: {}",
                case.name,
                wrong.len(),
                wrong.join(", ")
            ));
        }
    }
    report("BCC bond typing", &failures, CASES.len());
}

// ── L2: BCC atom typing ─────────────────────────────────────────────────────
#[test]
fn bcc_atom_types_match_antechamber() {
    let mut failures = Vec::new();
    for case in CASES {
        let (mol, ids) = build(case);
        let typed = match BCCAtomTypifier::bcc().typify(&mol) {
            Ok(t) => t,
            Err(e) => {
                failures.push(format!("  {:22} ERROR {e}", case.name));
                continue;
            }
        };
        let mut wrong = Vec::new();
        for (k, (aid, want)) in ids.iter().zip(case.bcc_atom_types).enumerate() {
            let got = typed
                .get_atom(*aid)
                .unwrap()
                .get_str(keys::TYPE)
                .map(str::to_owned);
            if got.as_deref() != Some(*want) {
                wrong.push(format!("{k}{}: got {got:?} want {want}", case.elements[k]));
            }
        }
        if !wrong.is_empty() {
            failures.push(format!(
                "  {:22} {}/{} atoms wrong: {}",
                case.name,
                wrong.len(),
                case.elements.len(),
                wrong.join(", ")
            ));
        }
    }
    report("BCC atom typing", &failures, CASES.len());
}

// ── L3: correction application, given antechamber's own types ───────────────
// Isolates the BCCPARM.DAT lookup + application arithmetic from perception.
#[test]
fn bcc_corrections_match_antechamber_given_reference_types() {
    let table = BCCCorrectionTable::bcc().expect("load BCCPARM.DAT");
    let corrector = BCCCorrector::new(table);
    let mut failures = Vec::new();
    for case in CASES {
        let (mut mol, ids) = build(case);
        apply_reference_types(&mut mol, &ids, case);
        for (aid, q) in ids.iter().zip(case.am1_charges) {
            mol.set_atom(*aid, keys::CHARGE, *q)
                .expect("set am1 charge");
        }
        if let Err(e) = corrector.apply(&mut mol) {
            failures.push(format!("  {:22} ERROR {e}", case.name));
            continue;
        }
        let mut wrong = Vec::new();
        for (k, (aid, want)) in ids.iter().zip(case.bcc_charges).enumerate() {
            let got = mol.get_atom(*aid).unwrap().get_f64(keys::CHARGE).unwrap();
            if (got - want).abs() > CHARGE_TOL {
                wrong.push(format!("{k}{}: {got:+.4} vs {want:+.4}", case.elements[k]));
            }
        }
        if !wrong.is_empty() {
            failures.push(format!("  {:22} {}", case.name, wrong.join(", ")));
        }
    }
    report("BCC correction (reference types)", &failures, CASES.len());
}

// ── L4: full pipeline — the real gate ───────────────────────────────────────
//
// The push API in one line: a molecule and its AM1 base charges go in, the
// corrected charges come out. `correct` is a pure function — it does not mutate
// `mol`, it does not reach for a backend, and it returns the charges rather than
// writing them into a graph the caller then has to unpick.
#[test]
fn am1bcc_charges_match_antechamber_end_to_end() {
    let model = BccModel::new(BccParameterSet::Bcc).expect("build the BCC charge model");
    let mut failures = Vec::new();
    for case in CASES {
        let (mol, _) = build(case);
        let got = match model.correct(&mol, case.am1_charges) {
            Ok(q) => q,
            Err(e) => {
                failures.push(format!("  {:22} ERROR {e}", case.name));
                continue;
            }
        };
        assert_eq!(
            got.len(),
            case.elements.len(),
            "{}: one charge per atom",
            case.name
        );
        let mut worst = 0.0f64;
        let mut wrong = Vec::new();
        for (k, (q, want)) in got.iter().zip(case.bcc_charges).enumerate() {
            let d = (q - want).abs();
            worst = worst.max(d);
            if d > CHARGE_TOL {
                wrong.push(format!("{k}{}: {q:+.4} vs {want:+.4}", case.elements[k]));
            }
        }
        if !wrong.is_empty() {
            failures.push(format!(
                "  {:22} max|dq|={worst:.4}  {}",
                case.name,
                wrong.join(", ")
            ));
        }
    }
    report("AM1-BCC end-to-end", &failures, CASES.len());
}

// ── Charge conservation: BCC increments are pairwise antisymmetric, so the
// BCC stage must conserve total charge EXACTLY. antechamber does not
// renormalize (it carries the AM1 rounding residual straight through), so a
// molrs "normalize" step would be a divergence, not a fix.
#[test]
fn bcc_conserves_total_charge_exactly() {
    for case in CASES {
        let sum_am1: f64 = case.am1_charges.iter().sum();
        let sum_bcc: f64 = case.bcc_charges.iter().sum();
        assert!(
            (sum_am1 - sum_bcc).abs() < 1.0e-6,
            "{}: antechamber drifted total charge {sum_am1:+.6} -> {sum_bcc:+.6}",
            case.name
        );
    }
}
