//! XML reader for [`ForceField`] and [`MMFFParams`].
//!
//! Supports two XML layouts:
//!
//! **Generic** — style-based, maps directly to the [`ForceField`] API:
//! ```xml
//! <ForceField name="TIP3P">
//!   <BondStyle name="harmonic">
//!     <Type name="OW-HW" k0="450.0" r0="0.9572" />
//!   </BondStyle>
//! </ForceField>
//! ```
//!
//! **MMFF** — parameter-table format generated by `scripts/mmff_to_xml.py`. Only
//! the two sections MMFF actually resolves from type rows are tables; its bonded
//! terms are `ParamSource::PerInstance` styles (the typifier bakes their
//! parameters into Frame columns), so they are *declared* and carry no rows:
//! ```xml
//! <ForceField name="MMFF94">
//!   <BondStyle name="mmff_bond" />                       <!-- per-instance: no rows -->
//!   <VdWParams B="0.2" Beta="12.0" DARAD="0.8" DAEPS="0.5">
//!     <VdW type="1" alpha="1.05" n_eff="2.49" a_i="3.89" g_i="1.282" da="-" />
//!   </VdWParams>                                         <!-- a real 95-row table -->
//!   <ElectrostaticParams dielectric="1.0" delta="0.05" scale14="0.75" />
//!   ...
//! </ForceField>
//! ```

use std::collections::HashMap;

use super::{ForceField, PairType, Params, SpecialBonds, StyleDefs};
use crate::ff::potential::pair::mmff::encode_da;
use crate::ff::typifier::mmff::{MMFFAtomProp, MMFFParams};
use crate::ff::typifier::opls::{OplsTypeRow, OplsTypingMeta};

// ---------------------------------------------------------------------------
// Public API — ForceField
// ---------------------------------------------------------------------------

/// Read a [`ForceField`] from an XML file on disk.
pub fn read_forcefield_xml(path: &str) -> Result<ForceField, String> {
    let xml = std::fs::read_to_string(path).map_err(|e| format!("read {}: {}", path, e))?;
    read_forcefield_xml_str(&xml)
}

/// Parse a [`ForceField`] from an XML string.
pub fn read_forcefield_xml_str(xml: &str) -> Result<ForceField, String> {
    let doc = roxmltree::Document::parse(xml).map_err(|e| format!("XML parse error: {}", e))?;

    let root = doc.root_element();
    if root.tag_name().name() != "ForceField" {
        return Err(format!(
            "Root element must be <ForceField>, got <{}>",
            root.tag_name().name()
        ));
    }

    let name = root.attribute("name").unwrap_or("unnamed");
    let mut ff = ForceField::new(name);

    for child in root.children().filter(|n| n.is_element()) {
        match child.tag_name().name() {
            // ---- Generic format ----
            "BondStyle" => parse_generic_style(&mut ff, &child, "bond")?,
            "AngleStyle" => parse_generic_style(&mut ff, &child, "angle")?,
            "DihedralStyle" => parse_generic_style(&mut ff, &child, "dihedral")?,
            "ImproperStyle" => parse_generic_style(&mut ff, &child, "improper")?,
            "PairStyle" => parse_generic_pair_style(&mut ff, &child)?,

            // ---- MMFF format ----
            // MMFF's bond / angle / stretch-bend / torsion / out-of-plane styles
            // are declared through the generic `<BondStyle>` / `<AngleStyle>` / …
            // elements above, with no `<Type>` children: they are per-instance
            // styles and there is nothing for a row to hold. The five readers that
            // used to parse 4,065 rows of type-defs here are gone — no kernel ever
            // read one of them, and their only function was to satisfy an
            // empty-type-params guard that now asks the registry instead.
            "VdWParams" => parse_mmff_vdw(&mut ff, &child)?,
            "ElectrostaticParams" => parse_mmff_ele(&mut ff, &child)?,

            // Auxiliary MMFF sections (informational, not compiled)
            "AtomTypes"
            | "AtomProperties"
            | "EquivalenceTable"
            | "BondChargeIncrements"
            | "PartialBondChargeIncrements"
            | "DefaultStretchBend"
            | "EmpiricalBondRules" => {}

            _ => {} // Unknown section — skip silently
        }
    }

    Ok(ff)
}

// ---------------------------------------------------------------------------
// Public API — MMFFParams
// ---------------------------------------------------------------------------

/// Parse [`MMFFParams`] from an XML string.
pub fn read_mmff_params_xml_str(xml: &str) -> Result<MMFFParams, String> {
    let doc = roxmltree::Document::parse(xml).map_err(|e| format!("XML parse error: {}", e))?;

    let root = doc.root_element();
    if root.tag_name().name() != "ForceField" {
        return Err(format!(
            "Root element must be <ForceField>, got <{}>",
            root.tag_name().name()
        ));
    }

    let mut props = HashMap::new();

    for child in root.children().filter(|n| n.is_element()) {
        if child.tag_name().name() == "AtomProperties" {
            for prop_node in child
                .children()
                .filter(|n| n.is_element() && n.tag_name().name() == "Prop")
            {
                let p = parse_atom_prop(&prop_node)?;
                props.insert(p.type_id, p);
            }
        }
    }

    if props.is_empty() {
        return Err("No <AtomProperties> found in XML".to_string());
    }

    Ok(MMFFParams::new(props))
}

// ---------------------------------------------------------------------------
// Public API — OplsTypingMeta
// ---------------------------------------------------------------------------

/// Parse OPLS-AA typing metadata ([`OplsTypingMeta`]) from an XML string.
///
/// Reads each `<Type>` of the `<AtomTypes>` section, transcribing the typing
/// attributes the potential reader
/// ([`OplsXmlReader`](crate::ff::forcefield::readers::opls::OplsXmlReader))
/// drops: `class`, `def` (SMARTS), `overrides` (comma list), `priority`, and
/// `layer`. This is purely additive — it never touches the potential
/// `ForceField`; the two are read from the same XML but kept separate (mirroring
/// [`read_mmff_params_xml_str`]).
///
/// Rows with no `def` are still recorded (with `def = None`); they are legacy
/// types excluded from automatic SMARTS typing.
///
/// # Errors
///
/// Returns `Err` if the root element is not `<ForceField>`, a `<Type>` lacks the
/// required `name`/`class`, or `priority`/`layer` is present but non-integer.
pub fn read_opls_typing_xml_str(xml: &str) -> Result<OplsTypingMeta, String> {
    let doc = roxmltree::Document::parse(xml).map_err(|e| format!("XML parse error: {}", e))?;

    let root = doc.root_element();
    if root.tag_name().name() != "ForceField" {
        return Err(format!(
            "Root element must be <ForceField>, got <{}>",
            root.tag_name().name()
        ));
    }

    let mut meta = OplsTypingMeta::new();

    for child in root.children().filter(|n| n.is_element()) {
        if child.tag_name().name() != "AtomTypes" {
            continue;
        }
        for t in child
            .children()
            .filter(|n| n.is_element() && n.tag_name().name() == "Type")
        {
            let name = attr_str(&t, "name")?.to_owned();
            let class = attr_str(&t, "class")?.to_owned();
            let def = t.attribute("def").map(str::to_owned);
            let overrides = t
                .attribute("overrides")
                .map(parse_overrides)
                .unwrap_or_default();
            let priority = match t.attribute("priority") {
                None => None,
                Some(s) => Some(s.parse::<i64>().map_err(|_| {
                    format!(
                        "<Type name={:?}> attribute 'priority' is not an integer: {:?}",
                        name, s
                    )
                })?),
            };
            let layer = match t.attribute("layer") {
                None => 0,
                Some(s) => s.parse::<u32>().map_err(|_| {
                    format!(
                        "<Type name={:?}> attribute 'layer' is not an integer: {:?}",
                        name, s
                    )
                })?,
            };
            meta.insert(
                name,
                OplsTypeRow {
                    class,
                    def,
                    overrides,
                    priority,
                    layer,
                },
            );
        }
    }

    Ok(meta)
}

/// Split a comma-separated `overrides` attribute into trimmed, non-empty names.
fn parse_overrides(raw: &str) -> Vec<String> {
    raw.split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_owned)
        .collect()
}

// ---------------------------------------------------------------------------
// Attribute helpers
// ---------------------------------------------------------------------------

fn attr_str<'a>(node: &'a roxmltree::Node, name: &str) -> Result<&'a str, String> {
    node.attribute(name)
        .ok_or_else(|| format!("<{}> missing attribute '{}'", node.tag_name().name(), name))
}

fn attr_f64(node: &roxmltree::Node, name: &str) -> Result<f64, String> {
    let s = attr_str(node, name)?;
    s.parse::<f64>().map_err(|e| {
        format!(
            "<{}> attribute '{}' = {:?}: {}",
            node.tag_name().name(),
            name,
            s,
            e
        )
    })
}

fn attr_u32(node: &roxmltree::Node, name: &str) -> Result<u32, String> {
    let s = attr_str(node, name)?;
    s.parse::<u32>().map_err(|e| {
        format!(
            "<{}> attribute '{}' = {:?}: {}",
            node.tag_name().name(),
            name,
            s,
            e
        )
    })
}

fn opt_attr_f64(node: &roxmltree::Node, name: &str) -> Option<f64> {
    node.attribute(name).and_then(|s| s.parse::<f64>().ok())
}

fn children_named<'a>(
    parent: &'a roxmltree::Node<'a, 'a>,
    tag: &'a str,
) -> impl Iterator<Item = roxmltree::Node<'a, 'a>> {
    parent
        .children()
        .filter(move |n| n.is_element() && n.tag_name().name() == tag)
}

fn numeric_attrs<'a>(node: &'a roxmltree::Node, skip: &[&str]) -> Vec<(&'a str, f64)> {
    let mut result = Vec::new();
    for attr in node.attributes() {
        if skip.contains(&attr.name()) {
            continue;
        }
        if let Ok(v) = attr.value().parse::<f64>() {
            result.push((attr.name(), v));
        }
    }
    result
}

// ---------------------------------------------------------------------------
// MMFF atom-property parser
// ---------------------------------------------------------------------------

fn parse_atom_prop(node: &roxmltree::Node) -> Result<MMFFAtomProp, String> {
    Ok(MMFFAtomProp {
        type_id: attr_u32(node, "type")?,
        atno: attr_u32(node, "atno")?,
        crd: attr_u32(node, "crd")?,
        val: attr_u32(node, "val")?,
        pilp: attr_u32(node, "pilp")?,
        mltb: attr_u32(node, "mltb")?,
        arom: attr_u32(node, "arom")?,
        linh: attr_u32(node, "linh")?,
        sbmb: attr_u32(node, "sbmb")?,
    })
}

// ---------------------------------------------------------------------------
// Generic XML format
// ---------------------------------------------------------------------------

fn parse_generic_style(
    ff: &mut ForceField,
    node: &roxmltree::Node,
    category: &str,
) -> Result<(), String> {
    let style_name = attr_str(node, "name")?;

    let style = match category {
        "bond" => ff.def_bondstyle(style_name),
        "angle" => ff.def_anglestyle(style_name),
        "dihedral" => ff.def_dihedralstyle(style_name),
        "improper" => ff.def_improperstyle(style_name),
        _ => return Err(format!("unknown category: {}", category)),
    };

    for type_node in children_named(node, "Type") {
        let name = attr_str(&type_node, "name")?;
        let params = numeric_attrs(&type_node, &["name"]);
        style.def_type(name, &params);
    }

    Ok(())
}

fn parse_generic_pair_style(ff: &mut ForceField, node: &roxmltree::Node) -> Result<(), String> {
    let style_name = attr_str(node, "name")?;
    let style_params = numeric_attrs(node, &["name"]);

    let style = ff.def_pairstyle(style_name, &style_params);

    for type_node in children_named(node, "Type") {
        let name = attr_str(&type_node, "name")?;
        let params = numeric_attrs(&type_node, &["name"]);
        style.def_type(name, &params);
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// MMFF XML format
// ---------------------------------------------------------------------------

fn parse_mmff_vdw(ff: &mut ForceField, node: &roxmltree::Node) -> Result<(), String> {
    let mut style_params: Vec<(&str, f64)> = Vec::new();
    for attr_name in ["B", "Beta", "DARAD", "DAEPS"] {
        if let Some(v) = opt_attr_f64(node, attr_name) {
            style_params.push((attr_name, v));
        }
    }

    let style = ff.def_pairstyle("mmff_vdw", &style_params);
    let StyleDefs::Pair(types) = &mut style.defs else {
        unreachable!();
    };

    for vdw in children_named(node, "VdW") {
        let atype = attr_f64(&vdw, "type")?;
        let alpha = attr_f64(&vdw, "alpha")?;
        let n_eff = attr_f64(&vdw, "n_eff")?;
        let a_i = attr_f64(&vdw, "a_i")?;
        let g_i = attr_f64(&vdw, "g_i")?;
        // MMFF's `DA` column ("D" donor / "A" acceptor / "-" neither). It selects
        // the two hydrogen-bond corrections in the combining rule (donor R*
        // suppression, donor-acceptor R*/eps scaling) — dropping it silently
        // over-estimates the vdW energy of every H-bonding molecule (urea +0.59,
        // NMA +0.12 kcal/mol). Absent attribute => "-", MMFF's own default.
        let da = encode_da(vdw.attribute("da").unwrap_or("-"));

        let type_name = format!("{}", atype as u32);
        types.push(PairType {
            name: type_name.clone(),
            itom: type_name.clone(),
            jtom: type_name,
            params: Params::from_pairs(&[
                ("alpha", alpha),
                ("n_eff", n_eff),
                ("a_i", a_i),
                ("g_i", g_i),
                ("da", da),
                ("type", atype),
            ]),
        });
    }
    Ok(())
}

/// Parse `<ElectrostaticParams dielectric="1.0" delta="0.05" scale14="0.75"/>`
/// into the `pair/mmff_ele` style **and** the force field's 1-4 weights.
///
/// MMFF's buffered-Coulomb term
///
/// ```text
/// E = 332.0716 * qi*qj / (dielectric * (R + delta))
/// ```
///
/// has no per-type rows at all — the charges are per-atom and the typifier bakes
/// them onto the frame — so the style carries only these three scalars. That is
/// exactly why the term went missing: the kernel (`mmff_ele_ctor`) has been in the
/// registry since it was written, but no force field ever *defined* the style, so
/// no consumer of the documented `ForceField` API could compute electrostatics
/// (caffeine was off by 150 kcal/mol). Declaring it as a section keeps the
/// numbers in the data file, symmetric with `<VdWParams>`, rather than conjuring a
/// style out of literals inside the reader.
///
/// `scale14` also sets [`SpecialBonds`]: coulomb 1-4 is scaled by it (0.75) while
/// **vdW 1-4 is left unscaled (1.0)** — MMFF scales only electrostatics, and its
/// torsion parameters were fitted against unscaled 1-4 vdW. The 1-2 / 1-3 weights
/// stay at the default 0.0 (molrs excludes those pairs by omitting them from the
/// neighbour list).
fn parse_mmff_ele(ff: &mut ForceField, node: &roxmltree::Node) -> Result<(), String> {
    let dielectric = opt_attr_f64(node, "dielectric").unwrap_or(1.0);
    let delta = opt_attr_f64(node, "delta").unwrap_or(0.05);
    let scale14 = opt_attr_f64(node, "scale14").unwrap_or(1.0);

    ff.set_special_bonds(SpecialBonds {
        lj: [0.0, 0.0, 1.0],
        coul: [0.0, 0.0, scale14],
    });
    ff.def_pairstyle("mmff_ele", &[("dielectric", dielectric), ("delta", delta)]);
    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generic_bond_style() {
        let xml = r#"
        <ForceField name="test">
          <BondStyle name="harmonic">
            <Type name="CT-OH" k0="300.0" r0="1.4" />
            <Type name="CT-CT" k0="268.0" r0="1.529" />
          </BondStyle>
        </ForceField>
        "#;

        let ff = read_forcefield_xml_str(xml).unwrap();
        assert_eq!(ff.name, "test");
        assert_eq!(ff.get_bondtypes().len(), 2);

        let style = ff.get_style("bond", "harmonic").unwrap();
        let bt = style.get_bondtype("CT", "OH").unwrap();
        assert_eq!(bt.params.get("k0"), Some(300.0));
        assert_eq!(bt.params.get("r0"), Some(1.4));
    }

    #[test]
    fn test_generic_angle_style() {
        let xml = r#"
        <ForceField name="test">
          <AngleStyle name="harmonic">
            <Type name="HW-OW-HW" k0="55.0" theta0="104.52" />
          </AngleStyle>
        </ForceField>
        "#;

        let ff = read_forcefield_xml_str(xml).unwrap();
        let types = ff.get_angletypes();
        assert_eq!(types.len(), 1);
        assert_eq!(types[0].params.get("theta0"), Some(104.52));
    }

    #[test]
    fn test_generic_pair_style() {
        let xml = r#"
        <ForceField name="test">
          <PairStyle name="lj/cut" cutoff="10.0">
            <Type name="CT" epsilon="0.066" sigma="3.5" />
          </PairStyle>
        </ForceField>
        "#;

        let ff = read_forcefield_xml_str(xml).unwrap();
        let style = ff.get_style("pair", "lj/cut").unwrap();
        assert_eq!(style.params.get("cutoff"), Some(10.0));
        assert_eq!(ff.get_pairtypes().len(), 1);
    }

    #[test]
    fn test_generic_dihedral_style() {
        let xml = r#"
        <ForceField name="test">
          <DihedralStyle name="opls">
            <Type name="HC-CT-CT-HC" k1="0.0" k2="0.0" k3="0.3" />
          </DihedralStyle>
        </ForceField>
        "#;

        let ff = read_forcefield_xml_str(xml).unwrap();
        let styles = ff.get_styles("dihedral");
        assert_eq!(styles.len(), 1);
    }

    // The four unit tests that lived here drove the MMFF type-def readers —
    // `<BondStretchParams>`, `<AngleBendParams>`, `<TorsionParams>`,
    // `<OutOfPlaneParams>` — and asserted the rows they produced. Those readers,
    // and the 4,065 rows they parsed across the shipped parameter files, are
    // deleted: no kernel ever read one of them. MMFF's bonded styles are
    // `ParamSource::PerInstance` (their parameters are resolved per interaction by
    // the typifier and baked into Frame columns), so they are declared through the
    // generic `<BondStyle>` / `<AngleStyle>` / `<DihedralStyle>` / `<ImproperStyle>`
    // elements with no `<Type>` children — which `test_mmff_per_instance_styles`
    // below covers, and `tests/ff/potential/param_source.rs` covers at runtime.
    //
    // `<VdWParams>` is a real 95-row table and keeps its reader and its test.

    /// MMFF's per-instance styles are DECLARED, and carry no type rows.
    #[test]
    fn test_mmff_per_instance_styles() {
        let xml = r#"
        <ForceField name="MMFF94">
          <BondStyle name="mmff_bond" />
          <AngleStyle name="mmff_angle" />
          <AngleStyle name="mmff_stbn" />
          <DihedralStyle name="mmff_torsion" />
          <ImproperStyle name="mmff_oop" />
        </ForceField>
        "#;

        let ff = read_forcefield_xml_str(xml).unwrap();
        assert_eq!(ff.get_styles("bond").len(), 1);
        assert_eq!(ff.get_styles("angle").len(), 2);
        assert_eq!(ff.get_styles("dihedral")[0].name, "mmff_torsion");
        assert_eq!(ff.get_styles("improper")[0].name, "mmff_oop");

        // Declared, but table-free: every parameter comes from the Frame.
        assert!(ff.get_bondtypes().is_empty());
        assert!(ff.get_angletypes().is_empty());
        assert!(ff.get_dihedraltypes().is_empty());
        assert!(ff.get_impropertypes().is_empty());
    }

    #[test]
    fn test_mmff_vdw() {
        let xml = r#"
        <ForceField name="MMFF94">
          <VdWParams B="0.12" Beta="12.0" DARAD="0.8" DAEPS="0.5">
            <VdW type="1" alpha="1.050" n_eff="2.490" a_i="3.890" g_i="1.282" />
          </VdWParams>
        </ForceField>
        "#;

        let ff = read_forcefield_xml_str(xml).unwrap();
        let style = ff.get_style("pair", "mmff_vdw").unwrap();
        assert_eq!(style.params.get("B"), Some(0.12));
        assert_eq!(style.params.get("Beta"), Some(12.0));

        let types = ff.get_pairtypes();
        assert_eq!(types.len(), 1);
        assert_eq!(types[0].params.get("alpha"), Some(1.05));
    }

    #[test]
    fn test_invalid_root() {
        let xml = r#"<NotForceField name="test" />"#;
        let err = read_forcefield_xml_str(xml).unwrap_err();
        assert!(err.contains("Root element must be <ForceField>"));
    }

    #[test]
    fn test_missing_attribute() {
        let xml = r#"
        <ForceField name="test">
          <BondStyle>
            <Type name="A-B" k0="1.0" />
          </BondStyle>
        </ForceField>
        "#;
        let err = read_forcefield_xml_str(xml).unwrap_err();
        assert!(err.contains("missing attribute 'name'"));
    }

    /// The shipped parameter set: seven styles, and exactly one real table.
    #[test]
    fn test_full_mmff_xml() {
        let ff = read_forcefield_xml_str(molrs::data::MMFF94_XML).unwrap();
        assert_eq!(ff.name, "MMFF94");

        // All seven energy styles are defined — `pair/mmff_ele` included, whose
        // absence was a 150 kcal/mol hole on caffeine.
        for (category, name) in [
            ("bond", "mmff_bond"),
            ("angle", "mmff_angle"),
            ("angle", "mmff_stbn"),
            ("dihedral", "mmff_torsion"),
            ("improper", "mmff_oop"),
            ("pair", "mmff_vdw"),
            ("pair", "mmff_ele"),
        ] {
            assert!(
                ff.get_style(category, name).is_some(),
                "MMFF94 defines no {category}/{name} style"
            );
        }

        // The bonded styles are per-instance: zero type rows, by construction.
        assert!(ff.get_bondtypes().is_empty());
        assert!(ff.get_angletypes().is_empty());
        assert!(ff.get_dihedraltypes().is_empty());
        assert!(ff.get_impropertypes().is_empty());

        // vdW is the one genuine per-atom-type table: 95 types, 95 rows.
        assert_eq!(ff.get_pairtypes().len(), 95);
    }

    #[test]
    fn test_mmff_params_xml() {
        let params = read_mmff_params_xml_str(molrs::data::MMFF94_XML).unwrap();
        assert!(params.get_prop(1).is_some());
    }

    // --- OPLS typing metadata reader (edge cases; happy-path parse over the
    //     real oplsaa.xml lives in tests/ff/typifier/opls.rs) -----------------

    #[test]
    fn test_opls_typing_overrides_and_layer_defaults() {
        // A modern row with overrides + a legacy row with no `def`. (Inline
        // edge fixture: exercises overrides splitting + def=None + default layer.)
        let xml = r#"<ForceField name="OPLS-AA">
          <AtomTypes>
            <Type name="opls_135" class="CT" element="C" mass="12.011" def="[C;X4](C)(H)(H)H"/>
            <Type name="opls_146" class="HA" element="H" mass="1.008" def="[H][c]" overrides="opls_144, opls_140"/>
            <Type name="opls_001" class="opls_001" element="C" mass="12.011"/>
          </AtomTypes>
        </ForceField>"#;
        let meta = read_opls_typing_xml_str(xml).unwrap();

        let r135 = meta.get("opls_135").unwrap();
        assert_eq!(r135.class, "CT");
        assert_eq!(r135.def.as_deref(), Some("[C;X4](C)(H)(H)H"));
        assert!(r135.overrides.is_empty());
        assert_eq!(r135.layer, 0);
        assert_eq!(r135.priority, None);

        let r146 = meta.get("opls_146").unwrap();
        assert_eq!(
            r146.overrides,
            vec!["opls_144".to_string(), "opls_140".to_string()]
        );

        // Legacy row: no def.
        let r001 = meta.get("opls_001").unwrap();
        assert_eq!(r001.def, None);
    }

    #[test]
    fn test_opls_typing_explicit_priority_and_layer() {
        let xml = r#"<ForceField name="OPLS-AA">
          <AtomTypes>
            <Type name="opls_x" class="CT" def="[C]" priority="7" layer="2"/>
          </AtomTypes>
        </ForceField>"#;
        let meta = read_opls_typing_xml_str(xml).unwrap();
        let r = meta.get("opls_x").unwrap();
        assert_eq!(r.priority, Some(7));
        assert_eq!(r.layer, 2);
    }

    #[test]
    fn test_opls_typing_missing_class_errors() {
        let xml = r#"<ForceField name="OPLS-AA">
          <AtomTypes><Type name="opls_135" def="[C]"/></AtomTypes>
        </ForceField>"#;
        let err = read_opls_typing_xml_str(xml).unwrap_err();
        assert!(err.contains("class"), "err: {err}");
    }

    #[test]
    fn test_opls_typing_bad_priority_errors() {
        let xml = r#"<ForceField name="OPLS-AA">
          <AtomTypes><Type name="opls_135" class="CT" priority="high"/></AtomTypes>
        </ForceField>"#;
        let err = read_opls_typing_xml_str(xml).unwrap_err();
        assert!(err.contains("priority"), "err: {err}");
    }

    #[test]
    fn test_opls_typing_wrong_root_errors() {
        let err = read_opls_typing_xml_str(r#"<System name="x"/>"#).unwrap_err();
        assert!(err.contains("ForceField"), "err: {err}");
    }
}
