"""The 37-molecule AmberTools25 oracle — read from the Rust suite's ONE copy.

``molrs/tests/ff/typifier/antechamber_oracle.rs`` is generated by
``scripts/gen_am1bcc_oracle.py`` from a real ``antechamber`` run (AmberTools25):
37 molecules, each carrying the INPUT a molrs user actually has (element, xyz,
formal charge, bond order + aromatic flag) and the ORACLE antechamber produced
(``bcc`` / ``abcg2`` / ``gas`` charge columns, and seven ``-at`` atom-type
columns). The Rust suite pins the chemistry against it 37/37.

**This module parses that file. It does not copy it.**

Why parse rather than generate a second fixture: a hand-written — or even a
generated — Python copy of the same numbers is a second artefact that can drift
from the first, and a drifted oracle is an oracle that quietly tests nothing.
Guarding a copy needs a manifest hash *plus* a test that the hash is checked;
having no copy needs neither, because there is nothing to drift from. The Rust
file is the single source of truth for both suites, and regenerating it updates
both at once.

What the Python tests are therefore *for*: the chemistry is already pinned in
Rust, so what these tests prove is that the **binding** is faithful — that it
does not lose precision, transpose an array, drop a column, or wire a parameter
set to the wrong table. Every number they assert comes from this one file.

The tolerance, too: :data:`CHARGE_TOL` is read out of the Rust suite's own
``const CHARGE_TOL``, so the two suites cannot be loosened independently.
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Final, Mapping, Sequence

import molrs

# --------------------------------------------------------------------------- #
# Locating the Rust suite                                                      #
# --------------------------------------------------------------------------- #

_ORACLE_REL: Final[str] = "molrs/tests/ff/typifier/antechamber_oracle.rs"
_CHARGE_TESTS_REL: Final[str] = "molrs/tests/ff/charge/antechamber.rs"


def _repo_root() -> Path:
    """The molrs repository root — the first ancestor holding the Rust oracle."""
    here = Path(__file__).resolve()
    for ancestor in here.parents:
        if (ancestor / _ORACLE_REL).is_file():
            return ancestor
    raise RuntimeError(
        f"could not find '{_ORACLE_REL}' by walking up from {here}. The Python "
        "binding tests read the Rust suite's oracle directly; there is no second "
        "copy to fall back on."
    )


REPO_ROOT: Final[Path] = _repo_root()
ORACLE_RS: Final[Path] = REPO_ROOT / _ORACLE_REL


# --------------------------------------------------------------------------- #
# A very small reader for the generated Rust literal                          #
# --------------------------------------------------------------------------- #


def _balanced(text: str, start: int, opener: str, closer: str) -> int:
    """Index just past the delimiter that closes the one at ``start``.

    String-aware, so a brace or bracket inside a Rust string literal (a SMILES, a
    parmchk2 comment) cannot unbalance the scan.
    """
    depth = 0
    i = start
    in_str = False
    while i < len(text):
        ch = text[i]
        if in_str:
            if ch == "\\":
                i += 2
                continue
            if ch == '"':
                in_str = False
        elif ch == '"':
            in_str = True
        elif ch == opener:
            depth += 1
        elif ch == closer:
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    raise ValueError(f"unbalanced '{opener}' at offset {start}")


def _value_text(chunk: str, at: int) -> str:
    """The Rust literal that starts at ``at`` (after the field's colon)."""
    while chunk[at] in " \t&":
        at += 1
    if chunk[at] == "[":
        return chunk[at : _balanced(chunk, at, "[", "]")]
    if chunk[at] == '"':
        end = at + 1
        while chunk[end] != '"':
            end += 2 if chunk[end] == "\\" else 1
        return chunk[at : end + 1]
    end = at
    while chunk[end] not in ",\n":
        end += 1
    return chunk[at:end]


def _literal(chunk: str, field: str) -> object:
    """The value of ``field`` in one ``AntechamberCase`` block, as Python data."""
    match = re.search(rf"^\s*{field}:\s*", chunk, re.M)
    if match is None:
        raise ValueError(
            f"the oracle case has no field `{field}` — {ORACLE_RS} changed shape"
        )
    rust = _value_text(chunk, match.end())
    py = re.sub(r"&(?=\[)", "", rust)
    py = re.sub(r"\btrue\b", "True", py)
    py = re.sub(r"\bfalse\b", "False", py)
    return ast.literal_eval(py)


def _case_chunks(text: str) -> list[str]:
    """Each ``AntechamberCase { … }`` block of the ``CASES`` table."""
    marker = "pub const CASES: &[AntechamberCase] = &["
    at = text.find(marker)
    if at < 0:
        raise RuntimeError(f"{ORACLE_RS} has no `CASES` table — it changed shape")
    region = text[at + len(marker) :]

    chunks: list[str] = []
    for match in re.finditer(r"AntechamberCase\s*\{", region):
        brace = region.index("{", match.start())
        chunks.append(region[brace : _balanced(region, brace, "{", "}")])
    return chunks


# --------------------------------------------------------------------------- #
# The case                                                                     #
# --------------------------------------------------------------------------- #

#: Python parameter-set name -> the oracle's atom-type column.
#:
#: The names are antechamber's ``-at`` flags, which is how the acceptance contract
#: words them (``AtdTypifier(parameter_set="gaff")`` must reproduce
#: ``antechamber -at gaff``). The flag and the table it walks are spelled
#: differently — ``-at gaff`` reads ``ATOMTYPE_GFF.DEF``, and the oracle names its
#: columns after the TABLE — which is exactly the confusion a wrong-set binding
#: would hide in, so the mapping is written down once, here.
TYPE_COLUMNS: Final[Mapping[str, str]] = {
    "bcc": "bcc_atom_types",
    "abcg2": "abcg2_atom_types",
    "gas": "gas_atom_types",
    "gaff": "gff_atom_types",
    "gaff2": "gff2_atom_types",
    "amber": "amber_atom_types",
    "sybyl": "sybyl_atom_types",
}


@dataclass(frozen=True)
class Case:
    """One antechamber molecule: the input a user has, and the answers to match."""

    name: str
    smiles: str
    net_charge: int
    elements: tuple[str, ...]
    xyz: tuple[tuple[float, float, float], ...]
    formal_charges: tuple[int, ...]
    bonds: tuple[tuple[int, int, float, bool], ...]
    #: Raw sqm Mulliken charges — NOT averaged over the equivalence classes.
    am1_charges_raw: tuple[float, ...]
    #: The same charges after antechamber's `-eq 1` class-mean: what BCC consumes.
    am1_charges: tuple[float, ...]
    bcc_charges: tuple[float, ...]
    abcg2_charges: tuple[float, ...]
    gas_charges: tuple[float, ...]
    #: `(i, j, bcc_bond_type)` — 1/2/3 plain, 7/8 aromatic, 9 delocalized.
    bcc_bond_types: tuple[tuple[int, int, int], ...]
    #: Atom types per antechamber `-at` flag; see :data:`TYPE_COLUMNS`.
    atom_types: Mapping[str, tuple[str, ...]]

    @property
    def n_atoms(self) -> int:
        return len(self.elements)

    def charges(self, model: str) -> tuple[float, ...]:
        """The final charge column of ``model`` (`bcc` / `abcg2` / `gas`)."""
        return {
            "bcc": self.bcc_charges,
            "abcg2": self.abcg2_charges,
            "gas": self.gas_charges,
        }[model]


def _build_case(chunk: str) -> Case:
    def col(field: str) -> tuple[object, ...]:
        return tuple(_literal(chunk, field))  # type: ignore[arg-type]

    return Case(
        name=str(_literal(chunk, "name")),
        smiles=str(_literal(chunk, "smiles")),
        net_charge=int(_literal(chunk, "net_charge")),  # type: ignore[call-overload]
        elements=col("elements"),  # type: ignore[arg-type]
        xyz=tuple(tuple(row) for row in _literal(chunk, "xyz")),  # type: ignore[union-attr]
        formal_charges=col("formal_charges"),  # type: ignore[arg-type]
        bonds=col("bonds"),  # type: ignore[arg-type]
        am1_charges_raw=col("am1_charges_raw"),  # type: ignore[arg-type]
        am1_charges=col("am1_charges"),  # type: ignore[arg-type]
        bcc_charges=col("bcc_charges"),  # type: ignore[arg-type]
        abcg2_charges=col("abcg2_charges"),  # type: ignore[arg-type]
        gas_charges=col("gas_charges"),  # type: ignore[arg-type]
        bcc_bond_types=col("bcc_bond_types"),  # type: ignore[arg-type]
        atom_types={
            flag: tuple(_literal(chunk, column))  # type: ignore[arg-type]
            for flag, column in TYPE_COLUMNS.items()
        },
    )


def _load() -> tuple[Case, ...]:
    """Parse the oracle, and refuse to hand back a fixture that proves nothing."""
    text = ORACLE_RS.read_text()
    chunks = _case_chunks(text)
    cases = tuple(_build_case(chunk) for chunk in chunks)

    # A silent under-parse is the failure mode that would make every test below
    # pass while covering two molecules. Pin the count against the file, and the
    # file against the 37 the spec's evidence chain names.
    if len(cases) < 37:
        raise RuntimeError(
            f"parsed only {len(cases)} molecules from {ORACLE_RS}; the oracle has at "
            "least 37 and the parser must have lost some"
        )
    for case in cases:
        widths = {
            "elements": len(case.elements),
            "xyz": len(case.xyz),
            "formal_charges": len(case.formal_charges),
            "am1_charges_raw": len(case.am1_charges_raw),
            "am1_charges": len(case.am1_charges),
            "bcc_charges": len(case.bcc_charges),
            "abcg2_charges": len(case.abcg2_charges),
            "gas_charges": len(case.gas_charges),
            **{flag: len(types) for flag, types in case.atom_types.items()},
        }
        if len(set(widths.values())) != 1:
            raise RuntimeError(
                f"{case.name}: the parsed oracle columns disagree on the atom count "
                f"{widths} — the parser dropped or merged a column"
            )
        if len(case.bonds) != len(case.bcc_bond_types):
            raise RuntimeError(f"{case.name}: bond columns disagree in length")
    return cases


CASES: Final[tuple[Case, ...]] = _load()


def _charge_tol() -> float:
    """The Rust suite's own ``CHARGE_TOL``.

    Not restated here. antechamber prints 6 decimals and BCCPARM.DAT carries 4, so
    the number is a property of the oracle, not of a language binding — and two
    copies of it are two chances for one suite to be quietly loosened.
    """
    src = (REPO_ROOT / _CHARGE_TESTS_REL).read_text()
    match = re.search(r"const CHARGE_TOL: f64 = ([0-9.e+-]+);", src)
    if match is None:
        raise RuntimeError(f"{_CHARGE_TESTS_REL} no longer declares `const CHARGE_TOL`")
    return float(match.group(1))


#: Charge agreement with antechamber, as the Rust suite defines it (1e-4).
CHARGE_TOL: Final[float] = _charge_tol()


# --------------------------------------------------------------------------- #
# The molecule a user has                                                      #
# --------------------------------------------------------------------------- #


def build(case: Case) -> tuple[molrs.Atomistic, list[int]]:
    """The Python mirror of the Rust suite's ``oracle_mol::build_molecule``.

    Built from the INPUT half of the case only — element, coordinates, formal
    charge, bond order, aromatic flag. Never from antechamber's answers: a test
    that fed the typifier antechamber's own perceived bond types would be testing
    a molecule no molrs user has, and would go green on a perception bug.

    Returns the graph and the atom handles in oracle atom order, so an oracle
    column zips straight onto it — the same contract the Rust builder has, and the
    order every charge array comes back in.
    """
    mol = molrs.Atomistic()
    handles = [
        mol.add_atom(element, x, y, z)
        for element, (x, y, z) in zip(case.elements, case.xyz, strict=True)
    ]
    for handle, formal_charge in zip(handles, case.formal_charges, strict=True):
        mol.set(handle, "formal_charge", int(formal_charge))
    for i, j, order, aromatic in case.bonds:
        bond = mol.add_bond(handles[i], handles[j])
        mol.set_relation_prop("bonds", bond, molrs.keys.ORDER, float(order))
        if aromatic:
            mol.set_relation_prop("bonds", bond, "is_aromatic", True)
    return mol, handles


def atom_types(typed: molrs.Atomistic, handles: Sequence[int]) -> list[str | None]:
    """The `type` label of every atom of ``typed``, in oracle atom order."""
    return [typed.get(handle, molrs.keys.TYPE) for handle in handles]  # type: ignore[misc]


def report(label: str, failures: Sequence[str], total: int) -> None:
    """Fail with a per-molecule report, or return.

    The oracle is 37 molecules; a bare per-atom assert would report the first
    disagreement and hide the shape of the failure (one bad element vs one bad
    perception vs everything). The Rust suite reports the same way
    (``oracle_mol::report``), so a Python failure reads like its Rust twin.
    """
    if not failures:
        return
    raise AssertionError(
        f"{label}: {len(failures)}/{total} molecules disagree with antechamber\n"
        + "\n".join(failures)
    )
