"""Python-binding coverage for the native LAMMPS force-field reader.

The parsing/unit logic is exercised in Rust (``ff::forcefield::readers::lammps``);
these tests only assert the PyO3 surface — that ``read_lammps_forcefield`` /
``read_lammps_forcefield_str`` yield the rich Python :class:`ForceField` (with the
FFI capsule a consumer like molpack resolves) and that errors map to ``ValueError``.
"""

import math

import pytest

import molrs

# Values copied from a real GAFF2 PEO ``*.ff`` (the molpack-paper figure-5 melt).
_FF = """\
# LAMMPS force field generated by molrs
special_bonds lj 0.0 0.0 0.5 coul 0.0 0.0 0.833333
pair_style lj/cut/coul/long 10.0 10.0
pair_coeff c3 c3 0.107800 3.397710
pair_coeff oh oh 0.093000 3.242871

bond_style harmonic
bond_coeff c3-c3 228.890000 1.535400

angle_style harmonic
angle_coeff c3-c3-oh 76.790000 109.660000

dihedral_style fourier
dihedral_coeff c3-c3-oh-ho 1 0.060000 3 0.000000
"""


def test_read_lammps_forcefield_str_yields_python_forcefield():
    ff = molrs.ff.read_lammps_forcefield_str(_FF)
    # Rich Python ForceField (shadow), not the bare PyO3 core.
    assert type(ff).__module__ == "molrs.ff.forcefield"
    # The FFI capsule a consumer (molpack relaxer) resolves zero-copy.
    assert hasattr(ff, "_ffi_forcefield_capsule")


def test_lammps_units_pass_through_binding():
    ff = molrs.ff.read_lammps_forcefield_str(_FF)
    # LAMMPS harmonic K(=228.89) → molrs k = 2K = 457.78 (½k form); r0 unchanged.
    bond = ff.get_style("bond", "harmonic")
    bt = bond.get_type_by_name("c3-c3")
    assert bt.params["k"] == pytest.approx(457.78)
    assert bt.params["r0"] == pytest.approx(1.5354)
    # angle theta0 is normalized deg→rad at the reader boundary (commit 6aa9e51,
    # "angles internal-radians"); pair ε/σ pass through.
    angle = ff.get_style("angle", "harmonic")
    at = angle.get_type_by_name("c3-c3-oh")
    assert at.params["theta0"] == pytest.approx(math.radians(109.66))
    lj = ff.get_style("pair", "lj/cut")
    assert lj.get_type_by_name("c3").params["epsilon"] == pytest.approx(0.1078)


def test_read_lammps_forcefield_from_path(tmp_path):
    p = tmp_path / "melt.ff"
    p.write_text(_FF)
    ff = molrs.ff.read_lammps_forcefield(str(p))
    assert len(ff.get_style("dihedral", "fourier").types) == 1


def test_unknown_keyword_maps_to_value_error():
    with pytest.raises(ValueError):
        molrs.ff.read_lammps_forcefield_str("mystery_style foo\n")


def test_write_lammps_data_coeffs_collapses_reverse_dihedral_names():
    """Reverse bonded names share one type id → one coeff row, not two."""
    src = """\
special_bonds lj 0.0 0.0 0.5 coul 0.0 0.0 0.833333
pair_style lj/cut 10.0
pair_coeff c3 c3 0.107800 3.397710

dihedral_style fourier
dihedral_coeff h1-c3-c3-os 2 0.250000 1 0.000000 0.000000 3 0.000000
dihedral_coeff os-c3-c3-h1 2 0.250000 1 0.000000 0.000000 3 0.000000
"""
    ff = molrs.ff.read_lammps_forcefield_str(src)
    text = molrs.ff.write_lammps_data_coeffs(
        ff,
        type_ids={"c3": 1, "h1-c3-c3-os": 4, "os-c3-c3-h1": 4},
    )
    body = text.split("Dihedral Coeffs", 1)[1]
    ids = [
        int(line.split()[0])
        for line in body.splitlines()
        if line.strip() and line.split()[0].isdigit()
    ]
    assert ids == [4], text


def test_write_lammps_forcefield_skip_units():
    ff = molrs.ff.read_lammps_forcefield_str(_FF)
    text = molrs.ff.write_lammps_forcefield_str(ff, skip_pair_style=True, skip_units=True)
    assert "units " not in text
    assert "bond_style harmonic" in text
    assert "bond_coeff c3-c3" in text


def test_skip_pair_style_omits_special_bonds():
    """Coeff include must not inject Amber coul 1-4 = 1/1.2."""
    ff = molrs.ff.read_lammps_forcefield_str(_FF)
    text = molrs.ff.write_lammps_forcefield_str(ff, skip_pair_style=True, skip_units=True)
    assert "special_bonds" not in text
    assert "pair_coeff" in text
    full = molrs.ff.write_lammps_forcefield_str(ff)
    assert "special_bonds lj" in full
    assert "0.833333" in full


def test_write_lammps_forcefield_str_round_trip():
    """write_lammps_forcefield_str is the inverse of the reader (units + layout)."""
    ff = molrs.ff.read_lammps_forcefield_str(_FF)
    text = molrs.ff.write_lammps_forcefield_str(ff)
    assert "pair_style lj/cut/coul/cut" in text
    assert "hybrid" not in text
    assert "bond_coeff c3-c3 228.890000 1.535400" in text
    assert "angle_coeff c3-c3-oh 76.790000 109.660000" in text

    ff2 = molrs.ff.read_lammps_forcefield_str(text)
    bt = ff2.get_style("bond", "harmonic").get_type_by_name("c3-c3")
    assert bt.params["k"] == pytest.approx(457.78)
    at = ff2.get_style("angle", "harmonic").get_type_by_name("c3-c3-oh")
    assert at.params["theta0"] == pytest.approx(math.radians(109.66))


def test_write_lammps_forcefield_to_path(tmp_path):
    ff = molrs.ff.read_lammps_forcefield_str(_FF)
    out = tmp_path / "out.ff"
    molrs.ff.write_lammps_forcefield(str(out), ff)
    assert "bond_coeff c3-c3" in out.read_text()
