use std::fs;
use std::path::Path;

/// Declarations for functions generated by macros (invisible to cbindgen).
const MACRO_GENERATED_DECLS: &str = r#"
#ifdef __cplusplus
extern "C" {
#endif

/* --- Block column accessors (macro-generated) --- */
/* Function names use the type alias names: F, I, U.                       */
/* Default widths: F=float (f32), I=int32_t (i32), U=uint32_t (u32).       */
/* With feature flags f64/i64/u64: F=double, I=int64_t, U=uint64_t.        */

/* Zero-copy read */
enum MolrsStatus molrs_block_get_F(struct MolrsBlockHandle block, uint32_t col_key_id,
                                    const F **out_ptr, uintptr_t *out_len);
enum MolrsStatus molrs_block_get_I(struct MolrsBlockHandle block, uint32_t col_key_id,
                                    const int32_t **out_ptr, uintptr_t *out_len);
enum MolrsStatus molrs_block_get_U(struct MolrsBlockHandle block, uint32_t col_key_id,
                                    const uint32_t **out_ptr, uintptr_t *out_len);

/* Zero-copy write */
enum MolrsStatus molrs_block_get_F_mut(struct MolrsBlockHandle *block, uint32_t col_key_id,
                                        F **out_ptr, uintptr_t *out_len);
enum MolrsStatus molrs_block_get_I_mut(struct MolrsBlockHandle *block, uint32_t col_key_id,
                                        int32_t **out_ptr, uintptr_t *out_len);
enum MolrsStatus molrs_block_get_U_mut(struct MolrsBlockHandle *block, uint32_t col_key_id,
                                        uint32_t **out_ptr, uintptr_t *out_len);

/* Copy path */
enum MolrsStatus molrs_block_copy_F(struct MolrsBlockHandle block, uint32_t col_key_id,
                                     F *out_buf, uintptr_t buf_len);
enum MolrsStatus molrs_block_copy_I(struct MolrsBlockHandle block, uint32_t col_key_id,
                                     int32_t *out_buf, uintptr_t buf_len);
enum MolrsStatus molrs_block_copy_U(struct MolrsBlockHandle block, uint32_t col_key_id,
                                     uint32_t *out_buf, uintptr_t buf_len);

/* Insert (set) columns */
enum MolrsStatus molrs_block_set_F(struct MolrsBlockHandle *block, uint32_t col_key_id,
                                    const F *data, const uintptr_t *shape, uintptr_t ndim);
enum MolrsStatus molrs_block_set_I(struct MolrsBlockHandle *block, uint32_t col_key_id,
                                    const int32_t *data, const uintptr_t *shape, uintptr_t ndim);
enum MolrsStatus molrs_block_set_U(struct MolrsBlockHandle *block, uint32_t col_key_id,
                                    const uint32_t *data, const uintptr_t *shape, uintptr_t ndim);

#ifdef __cplusplus
}  // extern "C"
#endif
"#;

fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let header_path = format!("{crate_dir}/include/molrs.h");
    let config = cbindgen::Config::from_file("cbindgen.toml").unwrap_or_default();

    match cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
    {
        Ok(bindings) => {
            bindings.write_to_file(&header_path);

            // Append macro-generated declarations before the closing #endif
            let content = fs::read_to_string(&header_path).unwrap();
            let closing = "#endif  /* MOLRS_H */";
            if let Some(pos) = content.rfind(closing) {
                let patched = format!("{}{}{}", &content[..pos], MACRO_GENERATED_DECLS, closing);
                fs::write(&header_path, patched).unwrap();
            }
        }
        Err(cbindgen::Error::ParseSyntaxError { .. }) => {
            eprintln!("cargo:warning=cbindgen failed to parse; header not generated");
        }
        Err(e) => {
            // Don't fail the build if header already exists
            if Path::new(&header_path).exists() {
                eprintln!("cargo:warning=cbindgen error: {e:?}; using existing header");
            } else {
                panic!("cbindgen failed: {e:?}");
            }
        }
    }
}
