"""Trajectory analysis — ``molrs::compute``.

The Rust compute facade is flat, and so is this module: every analysis is
``molrs.compute.<Name>``. They come in three kinds:

* **Computes** read frames (and, where they need one, a neighbour table) and
  return a result object or a plain ``dict`` of arrays: structure (``RDF``,
  ``Cluster``, ``ClusterProperties``, ``CenterOfMass``, ``GyrationTensor``,
  ``InertiaTensor``, ``RadiusOfGyration``, ``LocalDensity``,
  ``GaussianDensity``, ``SpatialDistribution``, ``StaticStructureFactorDebye``,
  ``PMFTXY``, the ``*Distribution`` histograms, ``HBonds``, ``BondOrientationalOrder``,
  ``RadicalVoronoi`` / ``VoronoiIntegration``), order (``Steinhardt``,
  ``Nematic``, ``Hexatic``, ``SolidLiquid``, ``LegendreReorientation``),
  dynamics (``MSD``, ``Acf``, ``VanHove``, ``Persist``) and transport raw
  curves (``VACF``, ``EinsteinDiffusion``, ``GreenKuboDiffusion``,
  ``EinsteinConductivity``, ``GreenKuboConductivity``, ``DipoleRateCross``,
  ``DebyeRelaxation``, ``Onsager``), plus ``Dielectric``'s raw observables
  and ``Pca2`` / ``KMeans`` over descriptor rows.
* **Fits and transforms** turn a raw curve into the derived quantity:
  ``LinearFit``, ``CumulativeTrapezoid``, ``Plateau``, ``DebyeFit`` and the
  spectra (``PowerSpectrum``, ``IRSpectrum``, ``RamanSpectrum``,
  ``EinsteinHelfandSpectrum``, ``GreenKuboSpectrum``,
  ``DipoleRateCrossSpectrum``, ``DipoleAutocorrelationSpectrum``,
  ``VcdSpectrum``, ``RoaSpectrum``, ``ResonanceRamanSpectrum``). A raw
  compute never returns a fitted coefficient: the fit is the analyst's
  explicit choice.
* **Checks** judge a result: ``kramers_kronig``, ``conductivity_sum_rule``,
  ``route_agreement``.

:class:`Compute` is the one structural contract every compute class
satisfies — a :func:`typing.runtime_checkable` protocol with one method,
``compute``.
"""

from .._lib import (
    Acf,
    AcfResult,
    AngleDistribution,
    BondOrientationalOrder,
    CenterOfMass,
    CenterOfMassResult,
    Cluster,
    ClusterCenters,
    ClusterCentersResult,
    ClusterProperties,
    ClusterResult,
    CombinedDistribution,
    CombinedDistributionResult,
    CumulativeTrapezoid,
    DebyeFit,
    DebyeRelaxation,
    DensityGrid,
    DescriptorRow,
    Dielectric,
    DihedralDistribution,
    DipoleAutocorrelationSpectrum,
    DipoleRateCross,
    DipoleRateCrossSpectrum,
    DistanceDistribution,
    DistributionResult,
    EinsteinConductivity,
    EinsteinDiffusion,
    EinsteinHelfandSpectrum,
    GaussianDensity,
    GreenKuboConductivity,
    GreenKuboDiffusion,
    GreenKuboSpectrum,
    GyrationTensor,
    HBondCriterion,
    HBonds,
    HBondsResult,
    Hexatic,
    IRSpectrum,
    InertiaTensor,
    KMeans,
    KMeansResult,
    LegendreReorientation,
    LegendreReorientationResult,
    LinearFit,
    LocalDensity,
    MSD,
    MSDResult,
    MSDTimeSeries,
    MolecularMoments,
    Nematic,
    Onsager,
    PMFTXY,
    Pca2,
    PcaResult,
    Persist,
    Plateau,
    PowerSpectrum,
    RDF,
    RDFResult,
    RadicalVoronoi,
    RadiusOfGyration,
    RamanSpectrum,
    ResonanceRamanSpectrum,
    RoaSpectrum,
    SolidLiquid,
    SpatialDistribution,
    SpatialDistributionResult,
    StaticStructureFactorDebye,
    Steinhardt,
    VACF,
    VanHove,
    VanHoveResult,
    VcdSpectrum,
    VoronoiCells,
    VoronoiIntegration,
    conductivity_sum_rule,
    kramers_kronig,
    polarizability_finite_field,
    route_agreement,
    voronoi_domains,
    voronoi_voids,
)
from ._protocol import Compute

Compute.__module__ = __name__

__all__ = [
    "Compute",
    "Acf",
    "AcfResult",
    "AngleDistribution",
    "BondOrientationalOrder",
    "CenterOfMass",
    "CenterOfMassResult",
    "Cluster",
    "ClusterCenters",
    "ClusterCentersResult",
    "ClusterProperties",
    "ClusterResult",
    "CombinedDistribution",
    "CombinedDistributionResult",
    "CumulativeTrapezoid",
    "DebyeFit",
    "DebyeRelaxation",
    "DensityGrid",
    "DescriptorRow",
    "Dielectric",
    "DihedralDistribution",
    "DipoleAutocorrelationSpectrum",
    "DipoleRateCross",
    "DipoleRateCrossSpectrum",
    "DistanceDistribution",
    "DistributionResult",
    "EinsteinConductivity",
    "EinsteinDiffusion",
    "EinsteinHelfandSpectrum",
    "GaussianDensity",
    "GreenKuboConductivity",
    "GreenKuboDiffusion",
    "GreenKuboSpectrum",
    "GyrationTensor",
    "HBondCriterion",
    "HBonds",
    "HBondsResult",
    "Hexatic",
    "IRSpectrum",
    "InertiaTensor",
    "KMeans",
    "KMeansResult",
    "LegendreReorientation",
    "LegendreReorientationResult",
    "LinearFit",
    "LocalDensity",
    "MSD",
    "MSDResult",
    "MSDTimeSeries",
    "MolecularMoments",
    "Nematic",
    "Onsager",
    "PMFTXY",
    "Pca2",
    "PcaResult",
    "Persist",
    "Plateau",
    "PowerSpectrum",
    "RDF",
    "RDFResult",
    "RadicalVoronoi",
    "RadiusOfGyration",
    "RamanSpectrum",
    "ResonanceRamanSpectrum",
    "RoaSpectrum",
    "SolidLiquid",
    "SpatialDistribution",
    "SpatialDistributionResult",
    "StaticStructureFactorDebye",
    "Steinhardt",
    "VACF",
    "VanHove",
    "VanHoveResult",
    "VcdSpectrum",
    "VoronoiCells",
    "VoronoiIntegration",
    "conductivity_sum_rule",
    "kramers_kronig",
    "polarizability_finite_field",
    "route_agreement",
    "voronoi_domains",
    "voronoi_voids",
]
