"""Trajectory analysis — ``molrs::compute``.

The Rust compute facade is flat, and so is this module: every analysis is
``molrs.compute.<Name>``. They come in three kinds:

* **Computes** read frames (and, where they need one, a neighbour table) and
  return a result object or a plain ``dict`` of arrays: structure (``Rdf``,
  ``Cluster``, ``ClusterProperties``, ``CenterOfMass``, ``GyrationTensor``,
  ``InertiaTensor``, ``RadiusOfGyration``, ``LocalDensity``,
  ``GaussianDensity``, ``SpatialDistribution``, ``StaticStructureFactorDebye``,
  ``PmftXy``, ``DistributionFunction`` / ``CombinedDistribution``, ``HBonds``, ``BondOrientationalOrder``,
  ``RadicalVoronoi`` / ``VoronoiIntegration``), order (``Steinhardt``,
  ``Nematic``, ``Hexatic``, ``SolidLiquid``, ``LegendreReorientation``),
  dynamics (``Msd``, ``Acf``, ``VanHove``, ``pair_survival_tcf``) and transport raw
  curves (``Vacf``, ``EinsteinDiffusion``, ``GreenKuboDiffusion``,
  ``EinsteinConductivity``, ``GreenKuboConductivity``, ``DipoleRateCross``,
  ``DebyeRelaxation``, ``OnsagerCorrelation``), the dielectric raw
  observables (``dipole_moment``, ``current_density``,
  ``static_dielectric_constant``, ``decompose_current``), the Voronoi
  analyses (``VoronoiDomainAnalysis``, ``VoronoiVoidAnalysis``) and ``Pca`` /
  ``Kmeans`` over descriptor rows, and the kinetic readings of one state
  (``kinetic_energy``, ``kinetic_temperature``, ``center_of_mass_velocity``).
* **Fits and transforms** turn a raw curve into the derived quantity:
  ``LinearFit``, ``CumulativeTrapezoid``, ``Plateau``, ``DebyeFit`` and the
  spectra (``PowerSpectrum``, ``IrSpectrum``, ``RamanSpectrum``,
  ``EinsteinHelfandSpectrum``, ``GreenKuboSpectrum``,
  ``DipoleRateCrossSpectrum``, ``DipoleAutocorrelationSpectrum``,
  ``VcdSpectrum``, ``RoaSpectrum``, ``ResonanceRamanSpectrum``). A raw
  compute never returns a fitted coefficient: the fit is the analyst's
  explicit choice.
* **Checks** judge a result: ``KramersKronig``, ``ConductivitySumRule``,
  ``RouteAgreement`` (each ``.check(...)``).

Every name is the Rust name: ``molrs.compute.X`` is ``molrs::compute::X``.

:class:`Compute` is the one structural contract every compute class
satisfies — a :func:`typing.runtime_checkable` protocol with one method,
``compute``.
"""

from .._native import (
    Acf,
    AcfResult,
    BondOrientationalOrder,
    CenterOfMass,
    CenterOfMassResult,
    Cluster,
    ClusterCenters,
    ClusterCentersResult,
    ClusterProperties,
    ClusterResult,
    CombinedDistribution,
    CombinedDistributionResult,
    ConductivitySumRule,
    CumulativeTrapezoid,
    DebyeFit,
    DebyeRelaxation,
    DensityGrid,
    DescriptorRow,
    DipoleAutocorrelationSpectrum,
    DipoleRateCross,
    DipoleRateCrossSpectrum,
    DistributionFunction,
    DistributionResult,
    EinsteinConductivity,
    EinsteinDiffusion,
    EinsteinHelfandSpectrum,
    GaussianDensity,
    GreenKuboConductivity,
    GreenKuboDiffusion,
    GreenKuboSpectrum,
    GyrationTensor,
    HBondCriterion,
    HBonds,
    HBondsResult,
    Hexatic,
    InertiaTensor,
    IrSpectrum,
    Kmeans,
    KmeansResult,
    KramersKronig,
    LegendreReorientation,
    LegendreReorientationResult,
    LinearFit,
    LocalDensity,
    MolecularMoments,
    Msd,
    MsdResult,
    MsdTimeSeries,
    Nematic,
    OnsagerCorrelation,
    Pca,
    PcaResult,
    Plateau,
    PmftXy,
    PowerSpectrum,
    RadicalVoronoi,
    RadiusOfGyration,
    RamanSpectrum,
    Rdf,
    RdfResult,
    ResonanceRamanSpectrum,
    RoaSpectrum,
    RouteAgreement,
    SolidLiquid,
    SpatialDistribution,
    SpatialDistributionResult,
    StaticStructureFactorDebye,
    Steinhardt,
    Vacf,
    VanHove,
    VanHoveResult,
    VcdSpectrum,
    VoronoiCells,
    VoronoiDomainAnalysis,
    VoronoiIntegration,
    VoronoiVoidAnalysis,
    center_of_mass_velocity,
    current_density,
    decompose_current,
    dipole_moment,
    kinetic_energy,
    kinetic_temperature,
    pair_survival_tcf,
    polarizability_finite_field,
    static_dielectric_constant,
)
from ._protocol import Compute

Compute.__module__ = __name__

__all__ = [
    "Compute",
    "Acf",
    "AcfResult",
    "BondOrientationalOrder",
    "CenterOfMass",
    "CenterOfMassResult",
    "Cluster",
    "ClusterCenters",
    "ClusterCentersResult",
    "ClusterProperties",
    "ClusterResult",
    "CombinedDistribution",
    "CombinedDistributionResult",
    "ConductivitySumRule",
    "CumulativeTrapezoid",
    "DebyeFit",
    "DebyeRelaxation",
    "DensityGrid",
    "DescriptorRow",
    "DipoleAutocorrelationSpectrum",
    "DipoleRateCross",
    "DipoleRateCrossSpectrum",
    "DistributionFunction",
    "DistributionResult",
    "EinsteinConductivity",
    "EinsteinDiffusion",
    "EinsteinHelfandSpectrum",
    "GaussianDensity",
    "GreenKuboConductivity",
    "GreenKuboDiffusion",
    "GreenKuboSpectrum",
    "GyrationTensor",
    "HBondCriterion",
    "HBonds",
    "HBondsResult",
    "Hexatic",
    "InertiaTensor",
    "IrSpectrum",
    "Kmeans",
    "KmeansResult",
    "KramersKronig",
    "LegendreReorientation",
    "LegendreReorientationResult",
    "LinearFit",
    "LocalDensity",
    "MolecularMoments",
    "Msd",
    "MsdResult",
    "MsdTimeSeries",
    "Nematic",
    "OnsagerCorrelation",
    "Pca",
    "PcaResult",
    "Plateau",
    "PmftXy",
    "PowerSpectrum",
    "RadicalVoronoi",
    "RadiusOfGyration",
    "RamanSpectrum",
    "Rdf",
    "RdfResult",
    "ResonanceRamanSpectrum",
    "RoaSpectrum",
    "RouteAgreement",
    "SolidLiquid",
    "SpatialDistribution",
    "SpatialDistributionResult",
    "StaticStructureFactorDebye",
    "Steinhardt",
    "Vacf",
    "VanHove",
    "VanHoveResult",
    "VcdSpectrum",
    "VoronoiCells",
    "VoronoiDomainAnalysis",
    "VoronoiIntegration",
    "VoronoiVoidAnalysis",
    "center_of_mass_velocity",
    "current_density",
    "decompose_current",
    "dipole_moment",
    "kinetic_energy",
    "kinetic_temperature",
    "pair_survival_tcf",
    "polarizability_finite_field",
    "static_dielectric_constant",
]
