//! Antechamber atom-type definition rules — `ATOMTYPE_SYBYL.DEF`.
//!
//! DO NOT HAND-EDIT — regenerate with `scripts/gen_param_tables.py`, which emits
//! this table from AmberTools' own `.DAT` / `.DEF` files. That is where the table
//! came FROM; it is not what the table IS — this is ordinary source, not a build
//! artefact.
//!
//! Source: `$AMBERHOME/dat/antechamber/ATOMTYPE_SYBYL.DEF` (AmberTools).

use crate::ff::params::{
    AtdRule, AtdTable, AtomPattern, AtomProp, PatternAtom, PropConstraint, PropExpr, PropRelation,
    PropUnit, WildAtom, WildAtomSpec,
};

/// `WILDATOM XX C N O S P`
#[rustfmt::skip]
const WILD_XX: &[WildAtomSpec] = &[
    WildAtomSpec { z: 6, degree: None },
    WildAtomSpec { z: 7, degree: None },
    WildAtomSpec { z: 8, degree: None },
    WildAtomSpec { z: 16, degree: None },
    WildAtomSpec { z: 15, degree: None },
];

/// `WILDATOM XA O S`
#[rustfmt::skip]
const WILD_XA: &[WildAtomSpec] = &[
    WildAtomSpec { z: 8, degree: None },
    WildAtomSpec { z: 16, degree: None },
];

/// `WILDATOM XB N P`
#[rustfmt::skip]
const WILD_XB: &[WildAtomSpec] = &[
    WildAtomSpec { z: 7, degree: None },
    WildAtomSpec { z: 15, degree: None },
];

/// `WILDATOM XC F Cl Br I`
#[rustfmt::skip]
const WILD_XC: &[WildAtomSpec] = &[
    WildAtomSpec { z: 9, degree: None },
    WildAtomSpec { z: 17, degree: None },
    WildAtomSpec { z: 35, degree: None },
    WildAtomSpec { z: 53, degree: None },
];

/// `WILDATOM XD S P`
#[rustfmt::skip]
const WILD_XD: &[WildAtomSpec] = &[
    WildAtomSpec { z: 16, degree: None },
    WildAtomSpec { z: 15, degree: None },
];

/// The 5 `WILDATOM` aliases declared by `ATOMTYPE_SYBYL.DEF`.
#[rustfmt::skip]
pub const WILDATOMS: &[WildAtom] = &[
    WildAtom { name: "XX", specs: WILD_XX },
    WildAtom { name: "XA", specs: WILD_XA },
    WildAtom { name: "XB", specs: WILD_XB },
    WildAtom { name: "XC", specs: WILD_XC },
    WildAtom { name: "XD", specs: WILD_XD },
];

/// The 66 `ATD` rules of `ATOMTYPE_SYBYL.DEF`, in file order.
///
/// Order is significant: the FIRST rule that matches wins — which is why the
/// table's own last row is the constraint-free fall-through (`DU`, or `ANY` in
/// `ATOMTYPE_SYBYL.DEF`). It matches anything nothing above it matched, and
/// antechamber does reach it: `-at amber` types nitromethane's nitro oxygens
/// `DU`. It is a rule of the table, not a fallback the engine invents.
///
/// No rule here carries an `alternate`: `PARMCHK.DAT`'s `equivalent_flag`
/// column describes the GAFF atom-type namespace, and this file is not written
/// in it. Nothing in this table is ever renamed by the 2-colouring pass.
pub const RULES: &[AtdRule] = &[
    AtdRule {
        atom_type: "C.3",
        alternate: None,
        residue: "*",
        atomic_number: Some(6),
        degree: Some(4),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "C.cat",
        alternate: None,
        residue: "*",
        atomic_number: Some(6),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[
            AtomPattern {
                atom: PatternAtom::Element(7),
                degree: Some(3),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(7),
                degree: Some(3),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(7),
                degree: Some(3),
                property: None,
                label: None,
                children: &[],
            },
        ]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "C.ar",
        alternate: None,
        residue: "*",
        atomic_number: Some(6),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: Some(PropExpr {
            constraints: &[PropConstraint {
                units: &[PropUnit {
                    count: None,
                    prop: AtomProp::Ar1,
                    relation: None,
                }],
            }],
        }),
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "C.2",
        alternate: None,
        residue: "*",
        atomic_number: Some(6),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "C.1",
        alternate: None,
        residue: "*",
        atomic_number: Some(6),
        degree: Some(2),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "C.1",
        alternate: None,
        residue: "*",
        atomic_number: Some(6),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "H",
        alternate: None,
        residue: "*",
        atomic_number: Some(1),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "F",
        alternate: None,
        residue: "*",
        atomic_number: Some(9),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Cl",
        alternate: None,
        residue: "*",
        atomic_number: Some(17),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Br",
        alternate: None,
        residue: "*",
        atomic_number: Some(35),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "I",
        alternate: None,
        residue: "*",
        atomic_number: Some(53),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "P.3",
        alternate: None,
        residue: "*",
        atomic_number: Some(15),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "N.4",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(4),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "N.am",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(6),
            degree: Some(3),
            property: None,
            label: None,
            children: &[AtomPattern {
                atom: PatternAtom::Wild(WILD_XA),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            }],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "N.pl3",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
        ]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "N.pl3",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: Some(PropExpr {
            constraints: &[PropConstraint {
                units: &[
                    PropUnit {
                        count: None,
                        prop: AtomProp::Ar1,
                        relation: None,
                    },
                    PropUnit {
                        count: None,
                        prop: AtomProp::Ar2,
                        relation: None,
                    },
                    PropUnit {
                        count: None,
                        prop: AtomProp::Ar3,
                        relation: None,
                    },
                ],
            }],
        }),
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "N.3",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "N.ar",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(2),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: Some(PropExpr {
            constraints: &[PropConstraint {
                units: &[PropUnit {
                    count: None,
                    prop: AtomProp::Ar1,
                    relation: None,
                }],
            }],
        }),
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "N.2",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(2),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "N.1",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "O.co2",
        alternate: None,
        residue: "*",
        atomic_number: Some(8),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(6),
            degree: Some(3),
            property: None,
            label: None,
            children: &[AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            }],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "O.co2",
        alternate: None,
        residue: "*",
        atomic_number: Some(8),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(15),
            degree: None,
            property: None,
            label: None,
            children: &[AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            }],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "O.2",
        alternate: None,
        residue: "*",
        atomic_number: Some(8),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "O.3",
        alternate: None,
        residue: "*",
        atomic_number: Some(8),
        degree: Some(2),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "S.2",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "S.3",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: Some(2),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "S.o",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(8),
            degree: Some(1),
            property: Some(PropExpr {
                constraints: &[PropConstraint {
                    units: &[PropUnit {
                        count: None,
                        prop: AtomProp::DbStrict,
                        relation: Some(PropRelation::BondedToPrev),
                    }],
                }],
            }),
            label: None,
            children: &[],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "S.o2",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: Some(4),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: Some(PropExpr {
                    constraints: &[PropConstraint {
                        units: &[PropUnit {
                            count: None,
                            prop: AtomProp::DbStrict,
                            relation: Some(PropRelation::BondedToPrev),
                        }],
                    }],
                }),
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: Some(PropExpr {
                    constraints: &[PropConstraint {
                        units: &[PropUnit {
                            count: None,
                            prop: AtomProp::DbStrict,
                            relation: Some(PropRelation::BondedToPrev),
                        }],
                    }],
                }),
                label: None,
                children: &[],
            },
        ]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "S.3",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Li",
        alternate: None,
        residue: "*",
        atomic_number: Some(3),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Be",
        alternate: None,
        residue: "*",
        atomic_number: Some(4),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "B",
        alternate: None,
        residue: "*",
        atomic_number: Some(5),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Na",
        alternate: None,
        residue: "*",
        atomic_number: Some(11),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Mg",
        alternate: None,
        residue: "*",
        atomic_number: Some(12),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Al",
        alternate: None,
        residue: "*",
        atomic_number: Some(13),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Si",
        alternate: None,
        residue: "*",
        atomic_number: Some(14),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "K",
        alternate: None,
        residue: "*",
        atomic_number: Some(19),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Ca",
        alternate: None,
        residue: "*",
        atomic_number: Some(20),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Sr",
        alternate: None,
        residue: "*",
        atomic_number: Some(38),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Ba",
        alternate: None,
        residue: "*",
        atomic_number: Some(56),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Sc",
        alternate: None,
        residue: "*",
        atomic_number: Some(21),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Ti",
        alternate: None,
        residue: "*",
        atomic_number: Some(22),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "V",
        alternate: None,
        residue: "*",
        atomic_number: Some(23),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Cr",
        alternate: None,
        residue: "*",
        atomic_number: Some(24),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Mn",
        alternate: None,
        residue: "*",
        atomic_number: Some(25),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Fe",
        alternate: None,
        residue: "*",
        atomic_number: Some(26),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Co",
        alternate: None,
        residue: "*",
        atomic_number: Some(27),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Ni",
        alternate: None,
        residue: "*",
        atomic_number: Some(28),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Cu",
        alternate: None,
        residue: "*",
        atomic_number: Some(29),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Zn",
        alternate: None,
        residue: "*",
        atomic_number: Some(30),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Ga",
        alternate: None,
        residue: "*",
        atomic_number: Some(31),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Ge",
        alternate: None,
        residue: "*",
        atomic_number: Some(32),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "As",
        alternate: None,
        residue: "*",
        atomic_number: Some(33),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Se",
        alternate: None,
        residue: "*",
        atomic_number: Some(34),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Ru",
        alternate: None,
        residue: "*",
        atomic_number: Some(44),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Rh",
        alternate: None,
        residue: "*",
        atomic_number: Some(45),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Pd",
        alternate: None,
        residue: "*",
        atomic_number: Some(46),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Ag",
        alternate: None,
        residue: "*",
        atomic_number: Some(47),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Cd",
        alternate: None,
        residue: "*",
        atomic_number: Some(48),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Pt",
        alternate: None,
        residue: "*",
        atomic_number: Some(78),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Au",
        alternate: None,
        residue: "*",
        atomic_number: Some(79),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Hg",
        alternate: None,
        residue: "*",
        atomic_number: Some(80),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Tl",
        alternate: None,
        residue: "*",
        atomic_number: Some(81),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "Pb",
        alternate: None,
        residue: "*",
        atomic_number: Some(82),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "lp",
        alternate: None,
        residue: "*",
        atomic_number: Some(0),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "ANY",
        alternate: None,
        residue: "*",
        atomic_number: None,
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
];

/// `ATOMTYPE_SYBYL.DEF` as one typed table.
pub const ATOMTYPE_SYBYL: AtdTable = AtdTable {
    name: "ATOMTYPE_SYBYL.DEF",
    wildatoms: WILDATOMS,
    rules: RULES,
};
