//! Antechamber atom-type definition rules — `ATOMTYPE_GAS.DEF`.
//!
//! DO NOT HAND-EDIT — regenerate with `scripts/gen_param_tables.py`, which emits
//! this table from AmberTools' own `.DAT` / `.DEF` files. That is where the table
//! came FROM; it is not what the table IS — this is ordinary source, not a build
//! artefact.
//!
//! Source: `$AMBERHOME/dat/antechamber/ATOMTYPE_GAS.DEF` (AmberTools).

use crate::ff::params::{
    AtdRule, AtdTable, AtomPattern, AtomProp, PatternAtom, PropConstraint, PropExpr, PropUnit,
    WildAtom, WildAtomSpec,
};

/// `WILDATOM XX C N O S P`
#[rustfmt::skip]
const WILD_XX: &[WildAtomSpec] = &[
    WildAtomSpec { z: 6, degree: None },
    WildAtomSpec { z: 7, degree: None },
    WildAtomSpec { z: 8, degree: None },
    WildAtomSpec { z: 16, degree: None },
    WildAtomSpec { z: 15, degree: None },
];

/// `WILDATOM XA O S`
#[rustfmt::skip]
const WILD_XA: &[WildAtomSpec] = &[
    WildAtomSpec { z: 8, degree: None },
    WildAtomSpec { z: 16, degree: None },
];

/// `WILDATOM XB N P`
#[rustfmt::skip]
const WILD_XB: &[WildAtomSpec] = &[
    WildAtomSpec { z: 7, degree: None },
    WildAtomSpec { z: 15, degree: None },
];

/// `WILDATOM XC F Cl Br I`
#[rustfmt::skip]
const WILD_XC: &[WildAtomSpec] = &[
    WildAtomSpec { z: 9, degree: None },
    WildAtomSpec { z: 17, degree: None },
    WildAtomSpec { z: 35, degree: None },
    WildAtomSpec { z: 53, degree: None },
];

/// The 4 `WILDATOM` aliases declared by `ATOMTYPE_GAS.DEF`.
#[rustfmt::skip]
pub const WILDATOMS: &[WildAtom] = &[
    WildAtom { name: "XX", specs: WILD_XX },
    WildAtom { name: "XA", specs: WILD_XA },
    WildAtom { name: "XB", specs: WILD_XB },
    WildAtom { name: "XC", specs: WILD_XC },
];

/// The 47 `ATD` rules of `ATOMTYPE_GAS.DEF`, in file order.
///
/// Order is significant: the FIRST rule that matches wins — which is why the
/// table's own last row is the constraint-free fall-through (`DU`, or `ANY` in
/// `ATOMTYPE_SYBYL.DEF`). It matches anything nothing above it matched, and
/// antechamber does reach it: `-at amber` types nitromethane's nitro oxygens
/// `DU`. It is a rule of the table, not a fallback the engine invents.
///
/// No rule here carries an `alternate`: `PARMCHK.DAT`'s `equivalent_flag`
/// column describes the GAFF atom-type namespace, and this file is not written
/// in it. Nothing in this table is ever renamed by the 2-colouring pass.
pub const RULES: &[AtdRule] = &[
    AtdRule {
        atom_type: "c1",
        alternate: None,
        residue: "*",
        atomic_number: Some(6),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "c1",
        alternate: None,
        residue: "*",
        atomic_number: Some(6),
        degree: Some(2),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "cg",
        alternate: None,
        residue: "*",
        atomic_number: Some(6),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[
            AtomPattern {
                atom: PatternAtom::Element(7),
                degree: Some(3),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(7),
                degree: Some(3),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(7),
                degree: Some(3),
                property: None,
                label: None,
                children: &[],
            },
        ]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "c2",
        alternate: None,
        residue: "*",
        atomic_number: Some(6),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "c3",
        alternate: None,
        residue: "*",
        atomic_number: Some(6),
        degree: Some(4),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "h",
        alternate: None,
        residue: "*",
        atomic_number: Some(1),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "n1",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "n2",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(2),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "ng",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(6),
            degree: Some(3),
            property: None,
            label: None,
            children: &[
                AtomPattern {
                    atom: PatternAtom::Element(7),
                    degree: Some(3),
                    property: None,
                    label: None,
                    children: &[],
                },
                AtomPattern {
                    atom: PatternAtom::Element(7),
                    degree: Some(3),
                    property: None,
                    label: None,
                    children: &[],
                },
            ],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "na",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(6),
            degree: Some(3),
            property: None,
            label: None,
            children: &[AtomPattern {
                atom: PatternAtom::Wild(WILD_XA),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            }],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "na",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: Some(PropExpr {
            constraints: &[PropConstraint {
                units: &[
                    PropUnit {
                        count: None,
                        prop: AtomProp::Ar2,
                        relation: None,
                    },
                    PropUnit {
                        count: None,
                        prop: AtomProp::Ar3,
                        relation: None,
                    },
                ],
            }],
        }),
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "na",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Wild(WILD_XX),
            degree: None,
            property: Some(PropExpr {
                constraints: &[PropConstraint {
                    units: &[
                        PropUnit {
                            count: None,
                            prop: AtomProp::Ar1,
                            relation: None,
                        },
                        PropUnit {
                            count: None,
                            prop: AtomProp::Ar2,
                            relation: None,
                        },
                        PropUnit {
                            count: None,
                            prop: AtomProp::Ar3,
                            relation: None,
                        },
                    ],
                }],
            }),
            label: None,
            children: &[],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "na",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Wild(WILD_XX),
            degree: None,
            property: Some(PropExpr {
                constraints: &[PropConstraint {
                    units: &[PropUnit {
                        count: None,
                        prop: AtomProp::DbStrict,
                        relation: None,
                    }],
                }],
            }),
            label: None,
            children: &[],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "na",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
        ]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "na+",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: Some(PropExpr {
            constraints: &[PropConstraint {
                units: &[PropUnit {
                    count: None,
                    prop: AtomProp::Ar1,
                    relation: None,
                }],
            }],
        }),
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "na+",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: Some(PropExpr {
            constraints: &[PropConstraint {
                units: &[
                    PropUnit {
                        count: None,
                        prop: AtomProp::DbStrict,
                        relation: None,
                    },
                    PropUnit {
                        count: None,
                        prop: AtomProp::DbAny,
                        relation: None,
                    },
                ],
            }],
        }),
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "n3",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "n4",
        alternate: None,
        residue: "*",
        atomic_number: Some(7),
        degree: Some(4),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "f",
        alternate: None,
        residue: "*",
        atomic_number: Some(9),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "cl",
        alternate: None,
        residue: "*",
        atomic_number: Some(17),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "br",
        alternate: None,
        residue: "*",
        atomic_number: Some(35),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "i",
        alternate: None,
        residue: "*",
        atomic_number: Some(53),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "o-1",
        alternate: None,
        residue: "*",
        atomic_number: Some(8),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(6),
            degree: Some(4),
            property: None,
            label: None,
            children: &[],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "o-2",
        alternate: None,
        residue: "*",
        atomic_number: Some(8),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(6),
            degree: Some(3),
            property: None,
            label: None,
            children: &[AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            }],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "os",
        alternate: None,
        residue: "*",
        atomic_number: Some(8),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(16),
            degree: Some(4),
            property: None,
            label: None,
            children: &[],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "os",
        alternate: None,
        residue: "*",
        atomic_number: Some(8),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(16),
            degree: Some(3),
            property: None,
            label: None,
            children: &[],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "op#",
        alternate: None,
        residue: "*",
        atomic_number: Some(8),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(15),
            degree: Some(4),
            property: None,
            label: None,
            children: &[
                AtomPattern {
                    atom: PatternAtom::Element(8),
                    degree: Some(1),
                    property: None,
                    label: None,
                    children: &[],
                },
                AtomPattern {
                    atom: PatternAtom::Element(8),
                    degree: Some(1),
                    property: None,
                    label: None,
                    children: &[],
                },
                AtomPattern {
                    atom: PatternAtom::Element(8),
                    degree: Some(1),
                    property: None,
                    label: None,
                    children: &[],
                },
            ],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "op=",
        alternate: None,
        residue: "*",
        atomic_number: Some(8),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(15),
            degree: Some(4),
            property: None,
            label: None,
            children: &[
                AtomPattern {
                    atom: PatternAtom::Element(8),
                    degree: Some(1),
                    property: None,
                    label: None,
                    children: &[],
                },
                AtomPattern {
                    atom: PatternAtom::Element(8),
                    degree: Some(1),
                    property: None,
                    label: None,
                    children: &[],
                },
            ],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "op",
        alternate: None,
        residue: "*",
        atomic_number: Some(8),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(15),
            degree: Some(4),
            property: None,
            label: None,
            children: &[AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            }],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "o2",
        alternate: None,
        residue: "*",
        atomic_number: Some(8),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "o3",
        alternate: None,
        residue: "*",
        atomic_number: Some(8),
        degree: Some(2),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "s-1",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(6),
            degree: Some(4),
            property: None,
            label: None,
            children: &[],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "s2",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "s3",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: Some(2),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "so",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: Some(3),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(8),
            degree: Some(1),
            property: None,
            label: None,
            children: &[],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "so4",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: Some(4),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
        ]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "so3",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: Some(4),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
        ]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "so2",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: Some(4),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
        ]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "so1",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: Some(4),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[AtomPattern {
            atom: PatternAtom::Element(8),
            degree: Some(1),
            property: None,
            label: None,
            children: &[],
        }]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "s3",
        alternate: None,
        residue: "*",
        atomic_number: Some(16),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "p#",
        alternate: None,
        residue: "*",
        atomic_number: Some(15),
        degree: Some(4),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
        ]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "p=",
        alternate: None,
        residue: "*",
        atomic_number: Some(15),
        degree: Some(4),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
        ]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "pn",
        alternate: None,
        residue: "*",
        atomic_number: Some(15),
        degree: Some(4),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: Some(&[
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
            AtomPattern {
                atom: PatternAtom::Element(8),
                degree: Some(1),
                property: None,
                label: None,
                children: &[],
            },
        ]),
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "p",
        alternate: None,
        residue: "*",
        atomic_number: Some(15),
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "lp",
        alternate: None,
        residue: "*",
        atomic_number: Some(0),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "LP",
        alternate: None,
        residue: "*",
        atomic_number: Some(0),
        degree: Some(1),
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
    AtdRule {
        atom_type: "DU",
        alternate: None,
        residue: "*",
        atomic_number: None,
        degree: None,
        hydrogen_count: None,
        ewd_count: None,
        atom_property: None,
        environment: None,
        environment_bonds: None,
    },
];

/// `ATOMTYPE_GAS.DEF` as one typed table.
pub const ATOMTYPE_GAS: AtdTable = AtdTable {
    name: "ATOMTYPE_GAS.DEF",
    wildatoms: WILDATOMS,
    rules: RULES,
};
