//! The shared shape of every chunk-fed `*Stream` class — the WASM face of
//! `molrs::io::frame_index`.
//!
//! A stream is the one reader of each format it covers (XYZ, PDB, SDF,
//! LAMMPS data and dump, DCD, XTC, TRR); each lives in its format's module
//! and is generated by the [`impl_wasm_traj_stream`] macro below. A stream
//! is driven by a worker and owns:
//!
//! - a *reusable* WASM input buffer (`allocInputBuffer`) into which the
//!   worker writes a chunk of the source (e.g. `blob.slice(start, end)`),
//! - a chunk-boundary-safe `FrameIndexBuilder` from `molrs::io` that emits
//!   [`FrameOffset`] records as the source flows through it,
//! - a frame-by-frame parser that decodes a single byte range from the
//!   reusable buffer and returns it as a `Frame`.
//!
//! Formats differ only in *which* `FrameIndexBuilder` is constructed and
//! *which* `read_<fmt>_bytes` door decodes a frame.
//!
//! # JS lifetime contract
//!
//! The input-buffer pointer returned by `allocInputBuffer` lives inside WASM
//! linear memory. `WebAssembly.Memory` may grow on any wasm-bindgen call,
//! which detaches the previous `ArrayBuffer`. Therefore **callers MUST
//! re-derive `new Uint8Array(memory.buffer, ptr, len)` immediately before
//! writing and MUST NOT hold onto the pointer across other wasm calls.** The
//! `Frame` a parse returns is an owned handle; the caller frees it.

use molrs::io::frame_index::FrameOffset as RsFrameOffset;
use wasm_bindgen::prelude::*;

/// One frame's location inside the source byte stream.
///
/// `byteOffset` is the absolute byte position of the frame's first byte
/// inside the source (round-tripped through `f64`; the spec caps source
/// size at 1 TB which is well within `Number.MAX_SAFE_INTEGER`).
/// `byteLen` is `u32` — per-frame size never exceeds the worker chunk
/// size plus a small slack.
#[wasm_bindgen(js_name = FrameOffset)]
#[derive(Debug, Clone, Copy)]
pub struct FrameOffset {
    byte_offset: f64,
    byte_len: u32,
}

#[wasm_bindgen(js_class = FrameOffset)]
impl FrameOffset {
    /// Absolute byte offset of this frame inside the source (in bytes).
    #[wasm_bindgen(getter, js_name = byteOffset)]
    pub fn byte_offset(&self) -> f64 {
        self.byte_offset
    }

    /// Size of this frame's encoded byte range, in bytes.
    #[wasm_bindgen(getter, js_name = byteLen)]
    pub fn byte_len(&self) -> u32 {
        self.byte_len
    }
}

impl From<RsFrameOffset> for FrameOffset {
    fn from(e: RsFrameOffset) -> Self {
        // `byte_offset: u64 → f64` is exact for values ≤ 2^53; the
        // streaming protocol caps source size at 1 TB.
        Self {
            byte_offset: e.byte_offset as f64,
            byte_len: e.byte_len,
        }
    }
}

/// Generate a per-format `*Stream` class.
///
/// Each invocation emits a `#[wasm_bindgen]` struct (exported to JS under
/// its own name), a `#[wasm_bindgen]` impl block, and the same set of
/// JS-facing methods. Only two things vary between formats, both passed as
/// expressions: `indexer`, which builds the format's `FrameIndexBuilder`,
/// and `parse`, a non-capturing closure
/// `|bytes: &[u8], state: Option<&[u8]>| -> std::io::Result<molrs::core::Frame>`
/// that decodes one frame's byte range (only DCD consults `state`).
///
/// The calling module must have `wasm_bindgen::prelude::*` in scope.
macro_rules! impl_wasm_traj_stream {
    (
        name    = $name:ident,
        indexer = $indexer:expr,
        parse   = $parse:expr,
    ) => {
        #[wasm_bindgen(js_name = $name)]
        pub struct $name {
            indexer: Option<Box<dyn ::molrs::io::frame_index::FrameIndexBuilder>>,
            input_buf: Vec<u8>,
            decoder_state: Option<Vec<u8>>,
        }

        #[wasm_bindgen(js_class = $name)]
        impl $name {
            /// Create a new streaming reader. The reusable input buffer
            /// starts empty; call `allocInputBuffer` before feeding data.
            #[wasm_bindgen(constructor)]
            #[allow(clippy::new_without_default)]
            pub fn new() -> Self {
                let indexer: Box<dyn ::molrs::io::frame_index::FrameIndexBuilder> =
                    Box::new($indexer);
                Self {
                    indexer: Some(indexer),
                    input_buf: Vec::new(),
                    decoder_state: None,
                }
            }

            /// Resize the reusable input buffer so it can hold at least
            /// `len` bytes, and return the WASM linear-memory pointer to
            /// its first byte.
            ///
            /// CALLER MUST RE-DERIVE THIS POINTER AFTER ANY OTHER WASM CALL —
            /// `wasm.memory.buffer` may have been detached by a `memory.grow`.
            #[wasm_bindgen(js_name = allocInputBuffer)]
            pub fn alloc_input_buffer(&mut self, len: usize) -> *mut u8 {
                if self.input_buf.len() < len {
                    self.input_buf.resize(len, 0);
                }
                self.input_buf.as_mut_ptr()
            }

            /// Current capacity (in bytes) of the reusable input buffer.
            #[wasm_bindgen(js_name = inputCapacity)]
            pub fn input_capacity(&self) -> usize {
                self.input_buf.len()
            }

            /// Feed the first `len` bytes of the input buffer into the
            /// indexer at absolute source offset `globalOffset`. Returns
            /// any frame entries that became finalized as a result.
            ///
            /// `globalOffset` is round-tripped through `f64`; per the
            /// streaming protocol the source size is capped at 1 TB
            /// (well within `Number.MAX_SAFE_INTEGER`).
            #[wasm_bindgen(js_name = feedIndexChunk)]
            pub fn feed_index_chunk(
                &mut self,
                global_offset: f64,
                len: usize,
            ) -> Result<Vec<$crate::io::frame_index::FrameOffset>, JsValue> {
                if global_offset < 0.0 || !global_offset.is_finite() {
                    return Err(JsValue::from_str(
                        "feedIndexChunk: globalOffset must be a non-negative finite number",
                    ));
                }
                if len > self.input_buf.len() {
                    return Err(JsValue::from_str(&format!(
                        "feedIndexChunk: len {} exceeds input buffer capacity {}",
                        len,
                        self.input_buf.len()
                    )));
                }
                let indexer = self
                    .indexer
                    .as_mut()
                    .ok_or_else(|| JsValue::from_str("feedIndexChunk: indexer already finished"))?;
                indexer.feed(&self.input_buf[..len], global_offset as u64);
                if let Some(state) = indexer.decoder_state() {
                    self.decoder_state = Some(state);
                }
                Ok(indexer.drain().into_iter().map(Into::into).collect())
            }

            /// Tell the indexer the source length when the host already
            /// knows it (DCD layout probe). No-op for self-describing
            /// formats.
            #[wasm_bindgen(js_name = hintTotalBytes)]
            pub fn hint_total_bytes(&mut self, total: f64) {
                if total < 0.0 || !total.is_finite() {
                    return;
                }
                if let Some(indexer) = self.indexer.as_mut() {
                    indexer.hint_total_bytes(total as u64);
                    if let Some(state) = indexer.decoder_state() {
                        self.decoder_state = Some(state);
                    }
                }
            }

            /// Opaque decoder state (DCD header + optional fixed-atom seed).
            /// Empty when the format is self-describing.
            #[wasm_bindgen(js_name = decoderState)]
            pub fn decoder_state(&self) -> Option<Vec<u8>> {
                self.decoder_state.clone().or_else(|| {
                    self.indexer
                        .as_ref()
                        .and_then(|indexer| indexer.decoder_state())
                })
            }

            /// Install decoder state on a parse-only stream so it can
            /// decode frames while a sibling indexer is still scanning.
            #[wasm_bindgen(js_name = setDecoderState)]
            pub fn set_decoder_state(&mut self, bytes: Vec<u8>) {
                if !bytes.is_empty() {
                    self.decoder_state = Some(bytes);
                }
            }

            /// Signal end-of-stream; return any trailing frame entry. The
            /// indexer is consumed and further `feedIndexChunk` calls
            /// throw.
            #[wasm_bindgen(js_name = finishIndex)]
            pub fn finish_index(
                &mut self,
            ) -> Result<Vec<$crate::io::frame_index::FrameOffset>, JsValue> {
                // DCD layout may only resolve once the source length is
                // known. Hint with bytes_seen before we consume the
                // indexer so decoder_state is populated for nopbc files.
                if let Some(indexer) = self.indexer.as_mut() {
                    let seen = indexer.bytes_seen();
                    indexer.hint_total_bytes(seen);
                    if let Some(state) = indexer.decoder_state() {
                        self.decoder_state = Some(state);
                    }
                }
                let indexer = self
                    .indexer
                    .take()
                    .ok_or_else(|| JsValue::from_str("finishIndex: indexer already finished"))?;
                let trailing = indexer
                    .finish()
                    .map_err(|e| JsValue::from_str(&format!("finishIndex: {}", e)))?;
                Ok(trailing.into_iter().map(Into::into).collect())
            }

            /// Decode the byte range `[offset, offset + len)` from the
            /// reusable input buffer as a single frame and return it.
            ///
            /// The returned `Frame` owns its data (the caller frees it);
            /// the input buffer may be overwritten as soon as this returns.
            #[wasm_bindgen(js_name = parseRangeInInput)]
            pub fn parse_range_in_input(
                &mut self,
                offset: usize,
                len: usize,
            ) -> Result<$crate::core::frame::Frame, JsValue> {
                let end = offset.checked_add(len).ok_or_else(|| {
                    JsValue::from_str("parseRangeInInput: offset + len overflowed usize")
                })?;
                if end > self.input_buf.len() {
                    return Err(JsValue::from_str(&format!(
                        "parseRangeInInput: range {}..{} exceeds input buffer length {}",
                        offset,
                        end,
                        self.input_buf.len()
                    )));
                }
                let bytes = &self.input_buf[offset..end];
                // Only DCD's `parse` consults the decoder state. Other
                // formats ignore it, so a stray `setDecoderState` cannot
                // wrap XTC/TRR bytes in DCD magic.
                let parse: fn(&[u8], Option<&[u8]>) -> std::io::Result<::molrs::core::Frame> =
                    $parse;
                let frame = parse(bytes, self.decoder_state.as_deref())
                    .map_err(|e| JsValue::from_str(&format!("parse error: {}", e)))?;
                $crate::core::frame::Frame::from_rs(frame)
            }
        }
    };
}

/// Copy `bytes` into a stream's input buffer in one chunk, index it, and
/// return every frame entry.
#[cfg(test)]
macro_rules! index_whole {
    ($stream:expr, $bytes:expr) => {{
        let bytes: &[u8] = $bytes;
        let p = $stream.alloc_input_buffer(bytes.len());
        // SAFETY: the buffer was just sized to `bytes.len()` and the
        // stream is borrowed exclusively here.
        unsafe {
            std::ptr::copy_nonoverlapping(bytes.as_ptr(), p, bytes.len());
        }
        let mut all = $stream.feed_index_chunk(0.0, bytes.len()).expect("feed");
        all.extend($stream.finish_index().expect("finish"));
        all
    }};
}

#[cfg(test)]
mod tests {
    use crate::io::lammps::LammpsDumpStream;
    use wasm_bindgen_test::*;

    /// Calling parse_range_in_input on an out-of-bounds range must error
    /// rather than panic.
    #[wasm_bindgen_test]
    fn parse_range_in_input_validates_bounds() {
        let mut stream = LammpsDumpStream::new();
        stream.alloc_input_buffer(8);
        let res = stream.parse_range_in_input(4, 100);
        assert!(res.is_err(), "expected bounds error");
    }
}
