//! Streaming readers for the WASM API — the one reader of every format they
//! cover (XYZ, PDB, SDF, LAMMPS data and dump, DCD, XTC, TRR).
//!
//! Implements Phase 1 / Task #4 of the streaming-trajectory spec
//! (see `molvis/docs/specs/streaming-trajectory.md`). The whole-content
//! readers of [`super::reader`] cover only the formats with no stream. These
//! classes are designed to be driven by a worker that owns:
//!
//! - a *reusable* WASM input buffer ([`allocInputBuffer`](
//!   `LAMMPSTrajStream::alloc_input_buffer`)) into which the worker
//!   writes a chunk of the source (e.g. `blob.slice(start, end)`),
//! - a chunk-boundary-safe `FrameIndexBuilder` from `molrs-io` that emits
//!   [`FrameIndexEntry`] records as the source flows through it,
//! - a frame-by-frame parser that decodes a single byte range from the
//!   reusable buffer and returns it as a [`Frame`].
//!
//! Eight wasm classes share this exact shape — `LAMMPSTrajStream`,
//! `XYZStream`, `PDBStream`, `LAMMPSStream`,
//! `SDFStream`, `DCDStream`, `XTCStream`, `TRRStream` —
//! so they are generated by the [`impl_wasm_traj_stream`] macro below.
//! Each only differs in *which* `FrameIndexBuilder` is constructed and
//! *which* `parse_frame_bytes` free function is invoked.
//!
//! # JS lifetime contract
//!
//! The input-buffer pointer returned by
//! [`allocInputBuffer`](`LAMMPSTrajStream::alloc_input_buffer`) lives
//! inside WASM linear memory. `WebAssembly.Memory` may grow on any
//! wasm-bindgen call, which detaches the previous `ArrayBuffer`. Therefore
//! **callers MUST re-derive `new Uint8Array(memory.buffer, ptr, len)`
//! immediately before writing and MUST NOT hold onto the pointer across
//! other wasm calls.** The [`Frame`] a parse returns is an owned handle; the
//! caller frees it.

use molrs::io::streaming::{FrameIndexBuilder, FrameIndexEntry as RsFrameIndexEntry};
use wasm_bindgen::prelude::*;

use crate::core::frame::Frame;

// Per-format builders + parsers. We re-import each format's
// `parse_frame_bytes` under a local alias so the macro can dispatch.
use molrs::io::data::lammps_data::{
    LammpsDataIndexBuilder, parse_frame_bytes as parse_lammps_data_frame_bytes,
};
use molrs::io::data::pdb::{PdbIndexBuilder, parse_frame_bytes as parse_pdb_frame_bytes};
use molrs::io::data::sdf::{SdfIndexBuilder, parse_frame_bytes as parse_sdf_frame_bytes};
use molrs::io::data::xyz::{XyzIndexBuilder, parse_frame_bytes as parse_xyz_frame_bytes};
use molrs::io::trajectory::dcd::{
    DcdIndexBuilder, parse_frame_bytes as parse_dcd_frame_bytes, parse_frame_with_decoder_context,
};
use molrs::io::trajectory::lammps_dump::{
    LammpsDumpIndexBuilder, parse_frame_bytes as parse_lammps_dump_frame_bytes,
};
use molrs::io::trajectory::trr::{TrrIndexBuilder, parse_frame_bytes as parse_trr_frame_bytes};
use molrs::io::trajectory::xtc::{XtcIndexBuilder, parse_frame_bytes as parse_xtc_frame_bytes};

fn parse_dump_stream(bytes: &[u8], _ctx: Option<&[u8]>) -> std::io::Result<molrs::core::Frame> {
    parse_lammps_dump_frame_bytes(bytes)
}
fn parse_xyz_stream(bytes: &[u8], _ctx: Option<&[u8]>) -> std::io::Result<molrs::core::Frame> {
    parse_xyz_frame_bytes(bytes)
}
fn parse_pdb_stream(bytes: &[u8], _ctx: Option<&[u8]>) -> std::io::Result<molrs::core::Frame> {
    parse_pdb_frame_bytes(bytes)
}
fn parse_lammps_data_stream(
    bytes: &[u8],
    _ctx: Option<&[u8]>,
) -> std::io::Result<molrs::core::Frame> {
    parse_lammps_data_frame_bytes(bytes)
}
fn parse_sdf_stream(bytes: &[u8], _ctx: Option<&[u8]>) -> std::io::Result<molrs::core::Frame> {
    parse_sdf_frame_bytes(bytes)
}
fn parse_dcd_stream(bytes: &[u8], ctx: Option<&[u8]>) -> std::io::Result<molrs::core::Frame> {
    match ctx {
        Some(context) => parse_frame_with_decoder_context(context, bytes),
        None => parse_dcd_frame_bytes(bytes),
    }
}
fn parse_xtc_stream(bytes: &[u8], _ctx: Option<&[u8]>) -> std::io::Result<molrs::core::Frame> {
    parse_xtc_frame_bytes(bytes)
}
fn parse_trr_stream(bytes: &[u8], _ctx: Option<&[u8]>) -> std::io::Result<molrs::core::Frame> {
    parse_trr_frame_bytes(bytes)
}

// ---------------------------------------------------------------------------
// FrameIndexEntry exposed to JS
// ---------------------------------------------------------------------------

/// One frame's location inside the source byte stream.
///
/// `byteOffset` is the absolute byte position of the frame's first byte
/// inside the source (round-tripped through `f64`; the spec caps source
/// size at 1 TB which is well within `Number.MAX_SAFE_INTEGER`).
/// `byteLen` is `u32` — per-frame size never exceeds the worker chunk
/// size plus a small slack.
#[wasm_bindgen(js_name = FrameIndexEntry)]
#[derive(Debug, Clone, Copy)]
pub struct FrameIndexEntry {
    byte_offset: f64,
    byte_len: u32,
}

#[wasm_bindgen(js_class = FrameIndexEntry)]
impl FrameIndexEntry {
    /// Absolute byte offset of this frame inside the source (in bytes).
    #[wasm_bindgen(getter, js_name = byteOffset)]
    pub fn byte_offset(&self) -> f64 {
        self.byte_offset
    }

    /// Size of this frame's encoded byte range, in bytes.
    #[wasm_bindgen(getter, js_name = byteLen)]
    pub fn byte_len(&self) -> u32 {
        self.byte_len
    }
}

impl From<RsFrameIndexEntry> for FrameIndexEntry {
    fn from(e: RsFrameIndexEntry) -> Self {
        // `byte_offset: u64 → f64` is exact for values ≤ 2^53; the
        // streaming protocol caps source size at 1 TB.
        Self {
            byte_offset: e.byte_offset as f64,
            byte_len: e.byte_len,
        }
    }
}

// ---------------------------------------------------------------------------
// Macro: generate per-format streaming class
// ---------------------------------------------------------------------------

/// Generate a per-format `*Stream` class.
///
/// Each invocation emits a `#[wasm_bindgen]` struct, a `#[wasm_bindgen]`
/// impl block, and the same set of JS-facing methods. The only thing that
/// varies between formats is the indexer constructor and the
/// `parse_frame_bytes` free function — both passed in as expressions.
macro_rules! impl_wasm_traj_stream {
    (
        struct_name = $struct:ident,
        js_name     = $js:ident,
        new_indexer = $new_indexer:expr,
        parse_fn    = $parse_fn:path,
    ) => {
        #[wasm_bindgen(js_name = $js)]
        pub struct $struct {
            indexer: Option<Box<dyn FrameIndexBuilder>>,
            input_buf: Vec<u8>,
            decoder_ctx: Option<Vec<u8>>,
        }

        #[wasm_bindgen(js_class = $js)]
        impl $struct {
            /// Create a new streaming reader. The reusable input buffer
            /// starts empty; call [`allocInputBuffer`] before feeding data.
            #[wasm_bindgen(constructor)]
            #[allow(clippy::new_without_default)]
            pub fn new() -> Self {
                let indexer: Box<dyn FrameIndexBuilder> = Box::new($new_indexer);
                Self {
                    indexer: Some(indexer),
                    input_buf: Vec::new(),
                    decoder_ctx: None,
                }
            }

            /// Resize the reusable input buffer so it can hold at least
            /// `len` bytes, and return the WASM linear-memory pointer to
            /// its first byte.
            ///
            /// CALLER MUST RE-DERIVE THIS POINTER AFTER ANY OTHER WASM CALL —
            /// `wasm.memory.buffer` may have been detached by a `memory.grow`.
            #[wasm_bindgen(js_name = allocInputBuffer)]
            pub fn alloc_input_buffer(&mut self, len: usize) -> *mut u8 {
                if self.input_buf.len() < len {
                    self.input_buf.resize(len, 0);
                }
                self.input_buf.as_mut_ptr()
            }

            /// Current capacity (in bytes) of the reusable input buffer.
            #[wasm_bindgen(js_name = inputCapacity)]
            pub fn input_capacity(&self) -> usize {
                self.input_buf.len()
            }

            /// Feed the first `len` bytes of the input buffer into the
            /// indexer at absolute source offset `globalOffset`. Returns
            /// any frame entries that became finalized as a result.
            ///
            /// `globalOffset` is round-tripped through `f64`; per the
            /// streaming protocol the source size is capped at 1 TB
            /// (well within `Number.MAX_SAFE_INTEGER`).
            #[wasm_bindgen(js_name = feedIndexChunk)]
            pub fn feed_index_chunk(
                &mut self,
                global_offset: f64,
                len: usize,
            ) -> Result<Vec<FrameIndexEntry>, JsValue> {
                if global_offset < 0.0 || !global_offset.is_finite() {
                    return Err(JsValue::from_str(
                        "feedIndexChunk: globalOffset must be a non-negative finite number",
                    ));
                }
                if len > self.input_buf.len() {
                    return Err(JsValue::from_str(&format!(
                        "feedIndexChunk: len {} exceeds input buffer capacity {}",
                        len,
                        self.input_buf.len()
                    )));
                }
                let indexer = self
                    .indexer
                    .as_mut()
                    .ok_or_else(|| JsValue::from_str("feedIndexChunk: indexer already finished"))?;
                indexer.feed(&self.input_buf[..len], global_offset as u64);
                if let Some(ctx) = indexer.decoder_context() {
                    self.decoder_ctx = Some(ctx);
                }
                Ok(indexer.drain().into_iter().map(Into::into).collect())
            }

            /// Tell the indexer the source length when the host already
            /// knows it (DCD layout probe). No-op for self-describing
            /// formats.
            #[wasm_bindgen(js_name = hintTotalBytes)]
            pub fn hint_total_bytes(&mut self, total: f64) {
                if total < 0.0 || !total.is_finite() {
                    return;
                }
                if let Some(indexer) = self.indexer.as_mut() {
                    indexer.hint_total_bytes(total as u64);
                    if let Some(ctx) = indexer.decoder_context() {
                        self.decoder_ctx = Some(ctx);
                    }
                }
            }

            /// Opaque decoder state (DCD header + optional fixed-atom seed).
            /// Empty when the format is self-describing.
            #[wasm_bindgen(js_name = decoderContext)]
            pub fn decoder_context(&self) -> Option<Vec<u8>> {
                self.decoder_ctx.clone().or_else(|| {
                    self.indexer
                        .as_ref()
                        .and_then(|indexer| indexer.decoder_context())
                })
            }

            /// Install decoder state on a parse-only stream so it can
            /// decode frames while a sibling indexer is still scanning.
            #[wasm_bindgen(js_name = setDecoderContext)]
            pub fn set_decoder_context(&mut self, bytes: Vec<u8>) {
                if !bytes.is_empty() {
                    self.decoder_ctx = Some(bytes);
                }
            }

            /// Signal end-of-stream; return any trailing frame entry. The
            /// indexer is consumed and further `feedIndexChunk` calls
            /// throw.
            #[wasm_bindgen(js_name = finishIndex)]
            pub fn finish_index(&mut self) -> Result<Vec<FrameIndexEntry>, JsValue> {
                // DCD layout may only resolve once the source length is
                // known. Hint with bytes_seen before we consume the
                // indexer so decoder_context is populated for nopbc files.
                if let Some(indexer) = self.indexer.as_mut() {
                    let seen = indexer.bytes_seen();
                    indexer.hint_total_bytes(seen);
                    if let Some(ctx) = indexer.decoder_context() {
                        self.decoder_ctx = Some(ctx);
                    }
                }
                let indexer = self
                    .indexer
                    .take()
                    .ok_or_else(|| JsValue::from_str("finishIndex: indexer already finished"))?;
                let trailing = indexer
                    .finish()
                    .map_err(|e| JsValue::from_str(&format!("finishIndex: {}", e)))?;
                Ok(trailing.into_iter().map(Into::into).collect())
            }

            /// Decode the byte range `[offset, offset + len)` from the
            /// reusable input buffer as a single frame and return it.
            ///
            /// The returned [`Frame`] owns its data (the caller frees it);
            /// the input buffer may be overwritten as soon as this returns.
            #[wasm_bindgen(js_name = parseRangeInInput)]
            pub fn parse_range_in_input(
                &mut self,
                offset: usize,
                len: usize,
            ) -> Result<Frame, JsValue> {
                let end = offset.checked_add(len).ok_or_else(|| {
                    JsValue::from_str("parseRangeInInput: offset + len overflowed usize")
                })?;
                if end > self.input_buf.len() {
                    return Err(JsValue::from_str(&format!(
                        "parseRangeInInput: range {}..{} exceeds input buffer length {}",
                        offset,
                        end,
                        self.input_buf.len()
                    )));
                }
                let bytes = &self.input_buf[offset..end];
                // DCD is the only format whose `parse_fn` consults decoder
                // context. Other formats ignore it so a stray
                // `setDecoderContext` cannot wrap XTC/TRR bytes in DCD magic
                // (and never copies the frame just to prepend a prefix).
                let frame = $parse_fn(bytes, self.decoder_ctx.as_deref())
                    .map_err(|e| JsValue::from_str(&format!("parse error: {}", e)))?;
                Frame::from_rs(frame)
            }
        }
    };
}

// ---------------------------------------------------------------------------
// Per-format instantiations
// ---------------------------------------------------------------------------

impl_wasm_traj_stream! {
    struct_name = LAMMPSTrajStream,
    js_name     = LAMMPSTrajStream,
    new_indexer = LammpsDumpIndexBuilder::new(),
    parse_fn    = parse_dump_stream,
}

impl_wasm_traj_stream! {
    struct_name = XYZStream,
    js_name     = XYZStream,
    new_indexer = XyzIndexBuilder::new(),
    parse_fn    = parse_xyz_stream,
}

impl_wasm_traj_stream! {
    struct_name = PDBStream,
    js_name     = PDBStream,
    new_indexer = PdbIndexBuilder::new(),
    parse_fn    = parse_pdb_stream,
}

impl_wasm_traj_stream! {
    struct_name = LAMMPSStream,
    js_name     = LAMMPSStream,
    new_indexer = LammpsDataIndexBuilder::new(),
    parse_fn    = parse_lammps_data_stream,
}

impl_wasm_traj_stream! {
    struct_name = SDFStream,
    js_name     = SDFStream,
    new_indexer = SdfIndexBuilder::new(),
    parse_fn    = parse_sdf_stream,
}

impl_wasm_traj_stream! {
    struct_name = DCDStream,
    js_name     = DCDStream,
    new_indexer = DcdIndexBuilder::new(),
    parse_fn    = parse_dcd_stream,
}

impl_wasm_traj_stream! {
    struct_name = XTCStream,
    js_name     = XTCStream,
    new_indexer = XtcIndexBuilder::new(),
    parse_fn    = parse_xtc_stream,
}

impl_wasm_traj_stream! {
    struct_name = TRRStream,
    js_name     = TRRStream,
    new_indexer = TrrIndexBuilder::new(),
    parse_fn    = parse_trr_stream,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use wasm_bindgen_test::*;

    /// Two-frame LAMMPS dump (matches the smallest fixture in molrs-io tests).
    const LAMMPS_DUMP: &str = "ITEM: TIMESTEP\n0\n\
ITEM: NUMBER OF ATOMS\n2\n\
ITEM: BOX BOUNDS pp pp pp\n0 10\n0 10\n0 10\n\
ITEM: ATOMS id type x y z\n\
1 1 0.0 0.0 0.0\n\
2 1 1.0 1.0 1.0\n\
ITEM: TIMESTEP\n1\n\
ITEM: NUMBER OF ATOMS\n2\n\
ITEM: BOX BOUNDS pp pp pp\n0 10\n0 10\n0 10\n\
ITEM: ATOMS id type x y z\n\
1 1 0.5 0.5 0.5\n\
2 1 1.5 1.5 1.5\n";

    /// Smoke test for the LAMMPS dump streaming class: feed → finish →
    /// parse the second frame → the returned Frame carries its data.
    #[wasm_bindgen_test]
    fn lammps_dump_stream_indexes_and_parses_two_frames() {
        let mut stream = LAMMPSTrajStream::new();
        let bytes = LAMMPS_DUMP.as_bytes();
        let cap = stream.alloc_input_buffer(bytes.len());
        assert!(!cap.is_null());
        // SAFETY: we just allocated this buffer at `len = bytes.len()`,
        // and we hold &mut self exclusively through this scope.
        unsafe {
            std::ptr::copy_nonoverlapping(bytes.as_ptr(), cap, bytes.len());
        }
        let entries = stream
            .feed_index_chunk(0.0, bytes.len())
            .expect("feed_index_chunk");
        let trailing = stream.finish_index().expect("finish_index");
        let mut all = entries;
        all.extend(trailing);
        assert_eq!(all.len(), 2, "expected exactly 2 frames in the fixture");

        // Decode frame 1 into a Frame: the dump's own column order, its
        // rows, and its box.
        let f1 = &all[1];
        let frame = stream
            .parse_range_in_input(f1.byte_offset() as usize, f1.byte_len() as usize)
            .expect("parse_range_in_input");
        assert_eq!(frame.keys(), vec!["atoms".to_string()]);
        let atoms = frame.get("atoms").expect("atoms block");
        let keys = atoms.keys().expect("keys");
        // The dump's `type` column is read as the canonical `type_id`.
        assert_eq!(keys, ["id", "type_id", "x", "y", "z"]);
        assert_eq!(atoms.nrows().expect("nrows"), 2);
        let x: js_sys::Float64Array =
            wasm_bindgen::JsCast::unchecked_into(JsValue::from(atoms.get("x", None).expect("x")));
        assert_eq!(x.to_vec(), vec![0.5, 1.5]);
        assert!(frame.get_box().is_some(), "the dump's box bounds survive");
    }

    /// Indexing the same fixture in many small chunks must produce the
    /// same entries as a single-shot feed.
    #[wasm_bindgen_test]
    fn lammps_dump_stream_chunked_index_matches_single_shot() {
        let bytes = LAMMPS_DUMP.as_bytes();

        // Single-shot.
        let mut s1 = LAMMPSTrajStream::new();
        let p1 = s1.alloc_input_buffer(bytes.len());
        unsafe {
            std::ptr::copy_nonoverlapping(bytes.as_ptr(), p1, bytes.len());
        }
        let mut all1 = s1.feed_index_chunk(0.0, bytes.len()).expect("feed");
        all1.extend(s1.finish_index().expect("finish"));

        // 17-byte chunks — small enough to split lines, frames, and
        // ITEM headers across the boundary.
        let mut s2 = LAMMPSTrajStream::new();
        let mut all2: Vec<FrameIndexEntry> = Vec::new();
        let chunk_size = 17usize;
        let mut offset = 0usize;
        while offset < bytes.len() {
            let len = (bytes.len() - offset).min(chunk_size);
            let p = s2.alloc_input_buffer(len);
            unsafe {
                std::ptr::copy_nonoverlapping(bytes[offset..offset + len].as_ptr(), p, len);
            }
            let entries = s2.feed_index_chunk(offset as f64, len).expect("feed");
            all2.extend(entries);
            offset += len;
        }
        all2.extend(s2.finish_index().expect("finish"));

        assert_eq!(all1.len(), all2.len(), "frame count mismatch");
        for (a, b) in all1.iter().zip(all2.iter()) {
            assert_eq!(a.byte_offset(), b.byte_offset());
            assert_eq!(a.byte_len(), b.byte_len());
        }
    }

    /// Owned `f64` column `key` of `block`.
    fn float_col(block: &crate::core::Block, key: &str) -> js_sys::Float64Array {
        wasm_bindgen::JsCast::unchecked_into(JsValue::from(block.get(key, None).expect(key)))
    }

    /// Copy `bytes` into a stream's input buffer in one chunk and index it.
    macro_rules! index_whole {
        ($stream:expr, $bytes:expr) => {{
            let bytes: &[u8] = $bytes;
            let p = $stream.alloc_input_buffer(bytes.len());
            // SAFETY: the buffer was just sized to `bytes.len()` and the
            // stream is borrowed exclusively here.
            unsafe {
                std::ptr::copy_nonoverlapping(bytes.as_ptr(), p, bytes.len());
            }
            let mut all = $stream.feed_index_chunk(0.0, bytes.len()).expect("feed");
            all.extend($stream.finish_index().expect("finish"));
            all
        }};
    }

    /// A PDB file is read through `PDBStream`, its one reader.
    #[wasm_bindgen_test]
    fn pdb_stream_reads_the_atoms() {
        let pdb = "ATOM      1  C   MOL     1       1.000   2.000   3.000  1.00  0.00           C\n\
ATOM      2  N   MOL     1       4.000   5.000   6.000  1.00  0.00           N\n\
END\n";
        let mut stream = PDBStream::new();
        let entries = index_whole!(stream, pdb.as_bytes());
        assert_eq!(entries.len(), 1);
        let e = &entries[0];
        let frame = stream
            .parse_range_in_input(e.byte_offset() as usize, e.byte_len() as usize)
            .expect("parse");
        let x = float_col(&frame.get("atoms").expect("atoms"), "x");
        assert_eq!(x.to_vec(), vec![1.0, 4.0]);
    }

    /// A LAMMPS data file is one frame of `LAMMPSStream`.
    #[wasm_bindgen_test]
    fn lammps_data_stream_reads_one_frame() {
        let data = "LAMMPS data\n\n\
                    2 atoms\n1 atom types\n\n\
                    0.0 10.0 xlo xhi\n0.0 10.0 ylo yhi\n0.0 10.0 zlo zhi\n\n\
                    Atoms\n\n\
                    1 1 1.0 2.0 3.0\n2 1 4.0 5.0 6.0\n";
        let mut stream = LAMMPSStream::new();
        let entries = index_whole!(stream, data.as_bytes());
        assert_eq!(entries.len(), 1);
        let e = &entries[0];
        let frame = stream
            .parse_range_in_input(e.byte_offset() as usize, e.byte_len() as usize)
            .expect("parse");
        let x = float_col(&frame.get("atoms").expect("atoms"), "x");
        assert_eq!(x.to_vec(), vec![1.0, 4.0]);
    }

    /// Calling parse_range_in_input on an out-of-bounds range must error
    /// rather than panic.
    #[wasm_bindgen_test]
    fn parse_range_in_input_validates_bounds() {
        let mut stream = LAMMPSTrajStream::new();
        stream.alloc_input_buffer(8);
        let res = stream.parse_range_in_input(4, 100);
        assert!(res.is_err(), "expected bounds error");
    }
}
