//! GROMACS `.top` / `.itp` force-field writer.
//!
//! Inverse of [`crate::ff::forcefield::readers::gromacs::GromacsTopFfReader`]:
//! molrs store units (Å, kcal/mol, radians) → GROMACS file units (nm, kJ/mol,
//! degrees) at this boundary only.
//!
//! Output layout matches the historical molpy `GromacsForceFieldWriter`:
//! `[ atoms ]` / `[ bonds ]` / `[ angles ]` / `[ dihedrals ]` / `[ pairs ]`
//! with 1-based atom-type indices for bonded rows (reader convention).

use super::ForceFieldWriter;
use crate::ff::forcefield::{ForceField, StyleDefs};

const KJ_PER_KCAL: f64 = 4.184;
const NM_TO_ANGSTROM: f64 = 10.0;

/// Writer for GROMACS topology force-field tables.
#[derive(Debug, Clone)]
pub struct GromacsTopFfWriter {
    /// Decimal places for floating coefficients.
    pub precision: usize,
}

impl Default for GromacsTopFfWriter {
    fn default() -> Self {
        Self { precision: 6 }
    }
}

impl GromacsTopFfWriter {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn with_precision(mut self, precision: usize) -> Self {
        self.precision = precision;
        self
    }

    fn fmt_f(&self, v: f64) -> String {
        format!("{:.*}", self.precision, v)
    }
}

impl ForceFieldWriter for GromacsTopFfWriter {
    fn write_str(&self, ff: &ForceField) -> Result<String, String> {
        let mut out = String::from("; Generated by molrs\n\n");

        // Collect atom types in style order (may contain duplicate names — match reader).
        let mut atom_names: Vec<String> = Vec::new();
        let mut atom_meta: Vec<std::collections::HashMap<String, String>> = Vec::new();
        for style in ff.get_styles("atom") {
            let StyleDefs::Atom(types) = &style.defs else {
                continue;
            };
            for t in types {
                atom_names.push(t.name.clone());
                let mut m = std::collections::HashMap::new();
                for (k, v) in t.params.iter_strings() {
                    m.insert(k.to_string(), v.to_string());
                }
                for (k, v) in t.params.iter() {
                    m.entry(k.to_string()).or_insert_with(|| self.fmt_f(v));
                }
                atom_meta.push(m);
            }
        }

        // name → first 1-based index (for bonded endpoint lookup by AtomType name)
        let mut name_to_idx: std::collections::HashMap<String, usize> =
            std::collections::HashMap::new();
        for (i, n) in atom_names.iter().enumerate() {
            name_to_idx.entry(n.clone()).or_insert(i + 1);
        }

        if !atom_names.is_empty() {
            out.push_str("[ atoms ]\n");
            out.push_str("; nr  name  resnr  residu  atom  cgnr  charge  mass\n");
            for (idx, (name, meta)) in atom_names.iter().zip(atom_meta.iter()).enumerate() {
                let nr = meta
                    .get("nr")
                    .cloned()
                    .unwrap_or_else(|| (idx + 1).to_string());
                let resnr = meta.get("resnr").cloned().unwrap_or_else(|| "0".into());
                let residu = meta.get("residu").cloned().unwrap_or_else(|| "LIG".into());
                let atom = meta.get("atom").cloned().unwrap_or_else(|| name.clone());
                let cgnr = meta.get("cgnr").cloned().unwrap_or_else(|| "1".into());
                let charge = meta
                    .get("charge")
                    .cloned()
                    .unwrap_or_else(|| self.fmt_f(0.0));
                let mass = meta.get("mass").cloned().unwrap_or_else(|| self.fmt_f(0.0));
                out.push_str(&format!(
                    "  {nr:>4}  {name:<5} {resnr:>5}  {residu:<5} {atom:<5} {cgnr:>4}  {charge}  {mass}\n"
                ));
            }
            out.push('\n');
        }

        // Bonds
        let mut any_bond = false;
        for style in ff.get_styles("bond") {
            let StyleDefs::Bond(types) = &style.defs else {
                continue;
            };
            if types.is_empty() {
                continue;
            }
            if !any_bond {
                out.push_str("[ bonds ]\n");
                out.push_str("; i  j  func  params...\n");
                any_bond = true;
            }
            let style_name = if style.name.is_empty() {
                "harmonic"
            } else {
                style.name.as_str()
            };
            let funct = bond_funct(style_name);
            let param_keys = bond_param_keys(style_name);
            for bt in types {
                let i = *name_to_idx.get(&bt.itom).unwrap_or(&0);
                let j = *name_to_idx.get(&bt.jtom).unwrap_or(&0);
                let params = format_params(self, &bt.params, param_keys, UnitKind::Bond);
                out.push_str(&format!("  {i}  {j}  {funct}  {params}\n"));
            }
        }
        if any_bond {
            out.push('\n');
        }

        // Angles
        let mut any_angle = false;
        for style in ff.get_styles("angle") {
            let StyleDefs::Angle(types) = &style.defs else {
                continue;
            };
            if types.is_empty() {
                continue;
            }
            if !any_angle {
                out.push_str("[ angles ]\n");
                out.push_str("; i  j  k  func  params...\n");
                any_angle = true;
            }
            let style_name = if style.name.is_empty() {
                "harmonic"
            } else {
                style.name.as_str()
            };
            let funct = angle_funct(style_name);
            let param_keys = angle_param_keys(style_name);
            for at in types {
                let i = *name_to_idx.get(&at.itom).unwrap_or(&0);
                let j = *name_to_idx.get(&at.jtom).unwrap_or(&0);
                let k = *name_to_idx.get(&at.ktom).unwrap_or(&0);
                let params = format_params(self, &at.params, param_keys, UnitKind::Angle);
                out.push_str(&format!("  {i}  {j}  {k}  {funct}  {params}\n"));
            }
        }
        if any_angle {
            out.push('\n');
        }

        // Dihedrals
        let mut any_dih = false;
        for style in ff.get_styles("dihedral") {
            let StyleDefs::Dihedral(types) = &style.defs else {
                continue;
            };
            if types.is_empty() {
                continue;
            }
            if !any_dih {
                out.push_str("[ dihedrals ]\n");
                out.push_str("; i  j  k  l  func  params...\n");
                any_dih = true;
            }
            let style_name = if style.name.is_empty() {
                "harmonic"
            } else {
                style.name.as_str()
            };
            let funct = dihedral_funct(style_name);
            let param_keys = dihedral_param_keys(style_name);
            for dt in types {
                let i = *name_to_idx.get(&dt.itom).unwrap_or(&0);
                let j = *name_to_idx.get(&dt.jtom).unwrap_or(&0);
                let k = *name_to_idx.get(&dt.ktom).unwrap_or(&0);
                let l = *name_to_idx.get(&dt.ltom).unwrap_or(&0);
                let params = format_params(self, &dt.params, param_keys, UnitKind::None);
                out.push_str(&format!("  {i}  {j}  {k}  {l}  {funct}  {params}\n"));
            }
        }
        if any_dih {
            out.push('\n');
        }

        // Pairs
        let mut any_pair = false;
        for style in ff.get_styles("pair") {
            let StyleDefs::Pair(types) = &style.defs else {
                continue;
            };
            if types.is_empty() {
                continue;
            }
            if !any_pair {
                out.push_str("[ pairs ]\n");
                out.push_str("; i  j  func  params...\n");
                any_pair = true;
            }
            let style_name = if style.name.is_empty() {
                "lj12-6"
            } else {
                style.name.as_str()
            };
            let funct = pair_funct(style_name);
            let param_keys = pair_param_keys(style_name);
            for pt in types {
                let i = *name_to_idx.get(&pt.itom).unwrap_or(&0);
                let j = *name_to_idx.get(&pt.jtom).unwrap_or(&0);
                let params = format_params(self, &pt.params, param_keys, UnitKind::None);
                out.push_str(&format!("  {i}  {j}  {funct}  {params}\n"));
            }
        }
        if any_pair {
            out.push('\n');
        }

        Ok(out)
    }
}

/// Convenience free function.
pub fn write_gromacs_top_ff(path: &str, ff: &ForceField, precision: usize) -> Result<(), String> {
    GromacsTopFfWriter::new()
        .with_precision(precision)
        .write(ff, path)
}

pub fn write_gromacs_top_ff_str(ff: &ForceField, precision: usize) -> Result<String, String> {
    GromacsTopFfWriter::new()
        .with_precision(precision)
        .write_str(ff)
}

// ---------------------------------------------------------------------------
// Funct maps + unit inverse
// ---------------------------------------------------------------------------

#[derive(Clone, Copy)]
enum UnitKind {
    Bond,
    Angle,
    None,
}

fn bond_funct(style: &str) -> &'static str {
    match style {
        "harmonic" | "" => "1",
        "G96" => "2",
        "morse" => "3",
        "cubic" => "4",
        _ => "1",
    }
}

fn angle_funct(style: &str) -> &'static str {
    match style {
        "harmonic" | "" => "1",
        "G96" => "2",
        "quartic" => "3",
        "ub" => "4",
        _ => "1",
    }
}

fn dihedral_funct(style: &str) -> &'static str {
    match style {
        "periodic" => "1",
        "rb" => "2",
        "harmonic" | "" => "3",
        _ => "1",
    }
}

fn pair_funct(style: &str) -> &'static str {
    match style {
        "lj12-6" | "" => "1",
        "buckingham" => "2",
        _ => "1",
    }
}

fn bond_param_keys(style: &str) -> &'static [&'static str] {
    match style {
        "morse" => &["r0", "De", "alpha"],
        "cubic" => &["r0", "k2", "k3", "k4"],
        _ => &["r0", "k"],
    }
}

fn angle_param_keys(style: &str) -> &'static [&'static str] {
    match style {
        "quartic" => &["c0", "c1", "c2", "c3"],
        "ub" => &["theta0", "k", "r0", "k_ub"],
        _ => &["theta0", "k"],
    }
}

fn dihedral_param_keys(style: &str) -> &'static [&'static str] {
    match style {
        "periodic" => &["phi0", "k", "n"],
        "rb" => &["c0", "c1", "c2", "c3", "c4", "c5"],
        _ => &["psi0", "k"],
    }
}

fn pair_param_keys(style: &str) -> &'static [&'static str] {
    match style {
        "buckingham" => &["A", "B", "C"],
        _ => &["c6", "c12"],
    }
}

fn format_params(
    w: &GromacsTopFfWriter,
    params: &crate::ff::forcefield::Params,
    keys: &[&str],
    kind: UnitKind,
) -> String {
    let mut parts = Vec::new();
    for key in keys {
        let v = params.get(key).unwrap_or(0.0);
        let file_v = match (kind, *key) {
            (UnitKind::Bond, "r0") => v / NM_TO_ANGSTROM,
            (UnitKind::Bond, "k" | "k2") => v * (KJ_PER_KCAL * NM_TO_ANGSTROM * NM_TO_ANGSTROM),
            (UnitKind::Bond, "k3") => v * (KJ_PER_KCAL * NM_TO_ANGSTROM.powi(3)),
            (UnitKind::Bond, "k4") => v * (KJ_PER_KCAL * NM_TO_ANGSTROM.powi(4)),
            (UnitKind::Bond, "De") => v * KJ_PER_KCAL,
            (UnitKind::Bond, "alpha") => v * NM_TO_ANGSTROM,
            (UnitKind::Angle, "theta0") => v.to_degrees(),
            (UnitKind::Angle, "k") => v * KJ_PER_KCAL,
            (UnitKind::Angle, "r0") => v / NM_TO_ANGSTROM,
            (UnitKind::Angle, "k_ub") => v * (KJ_PER_KCAL * NM_TO_ANGSTROM * NM_TO_ANGSTROM),
            _ => v,
        };
        parts.push(w.fmt_f(file_v));
    }
    parts.join("  ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ff::forcefield::ForceField;

    #[test]
    fn empty_ff_writes_header() {
        let ff = ForceField::new("x");
        let s = GromacsTopFfWriter::new().write_str(&ff).unwrap();
        assert!(s.contains("Generated by molrs"));
    }

    #[test]
    fn atom_and_bond_roundtrip_shape() {
        let mut ff = ForceField::new("gmx");
        {
            let st = ff.def_atomstyle("full");
            st.def_atomtype("opls_135", &[]);
            st.def_atomtype("opls_140", &[]);
        }
        {
            let st = ff.def_bondstyle("");
            st.def_bondtype(
                "opls_135",
                "opls_140",
                &[("r0", 1.09), ("k", 300.0)], // molrs units
            );
        }
        let s = GromacsTopFfWriter::new().write_str(&ff).unwrap();
        assert!(s.contains("[ atoms ]"));
        assert!(s.contains("[ bonds ]"));
        assert!(s.contains("opls_135"));
    }
}
