//! GROMACS `.top` / `.itp` force-field writer.
//!
//! Inverse of [`crate::ff::forcefield::readers::gromacs::GromacsTopFfReader`]:
//! molrs store units (Å, kcal/mol, radians) → GROMACS file units (nm, kJ/mol,
//! degrees) at this boundary only.
//!
//! Output layout: `[ defaults ]`, then `[ atomtypes ]` for every atom type
//! that carries parameters, then — as the historical molpy
//! `GromacsForceFieldWriter` did — `[ atoms ]` / `[ bonds ]` / `[ angles ]` /
//! `[ dihedrals ]` / `[ pairs ]` with 1-based atom-type indices for bonded rows
//! (reader convention).
//!
//! - `[ atomtypes ]` is `name [bond_type] [at.num] mass charge ptype V W`: the
//!   6-, 7- or 8-column form by which of `bond_type` / `atomic_number` the type
//!   carries, `at.num` as a bare integer, V = σ ÷ 10 (nm) and W = ε × 4.184
//!   (kJ/mol). A type with none of `mass charge ptype sigma epsilon` gets no
//!   row; a type with some but not all of them is `Err` naming the type and
//!   the missing keys — nothing is fabricated.
//! - `[ atoms ]` is an index table built from the atom-type names alone. Its
//!   `charge` / `mass` come from the type's numeric params when present; every
//!   other per-atom field (`resnr` `0`, `residu` `LIG`, `cgnr` `1`, and
//!   `charge` / `mass` `0.0` otherwise) is a placeholder, because a force field
//!   holds no per-atom data.
//!
//! # Whole-FF serialization, not coefficient writing
//!
//! molrs has two kinds of force-field writer. This one is **whole-FF
//! serialization**: it writes every type the [`ForceField`] holds, as a
//! force-field file, and takes no type labels. **Coefficient writing**
//! ([`super::lammps::LammpsFfWriter`], LAMMPS only) answers "which coefficients
//! does this system's data file need" and is keyed by the system's
//! `TypeLabels`.

use super::ForceFieldWriter;
use crate::ff::forcefield::{AtomType, ForceField, StyleDefs};

const KJ_PER_KCAL: f64 = 4.184;
const NM_TO_ANGSTROM: f64 = 10.0;

/// Writer for GROMACS topology force-field tables.
#[derive(Debug, Clone)]
pub struct GromacsTopFfWriter {
    /// Decimal places for floating coefficients.
    pub precision: usize,
}

impl Default for GromacsTopFfWriter {
    fn default() -> Self {
        Self { precision: 6 }
    }
}

impl GromacsTopFfWriter {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn with_precision(mut self, precision: usize) -> Self {
        self.precision = precision;
        self
    }

    fn fmt_f(&self, v: f64) -> String {
        format!("{:.*}", self.precision, v)
    }

    /// The `[ atomtypes ]` line of `t` in file units, `None` for a type that
    /// carries none of the five row keys, `Err` for one that carries some.
    fn atomtypes_row(&self, t: &AtomType) -> Result<Option<String>, String> {
        let p = &t.params;
        let (mass, charge, ptype, sigma, epsilon) = (
            p.get("mass"),
            p.get("charge"),
            p.get_str("ptype"),
            p.get("sigma"),
            p.get("epsilon"),
        );
        let present = [
            ("mass", mass.is_some()),
            ("charge", charge.is_some()),
            ("ptype", ptype.is_some()),
            ("sigma", sigma.is_some()),
            ("epsilon", epsilon.is_some()),
        ];
        let missing: Vec<&str> = present
            .iter()
            .filter(|(_, has)| !has)
            .map(|(key, _)| *key)
            .collect();
        if missing.len() == present.len() {
            return Ok(None);
        }
        let (Some(mass), Some(charge), Some(ptype), Some(sigma), Some(epsilon)) =
            (mass, charge, ptype, sigma, epsilon)
        else {
            return Err(format!(
                "atom type '{}' cannot be written to [ atomtypes ]: missing {}",
                t.name,
                missing.join(", ")
            ));
        };

        let mut cols = vec![t.name.clone()];
        if let Some(bond_type) = p.get_str("bond_type") {
            cols.push(bond_type.to_owned());
        }
        if let Some(z) = p.get("atomic_number") {
            if z.fract() != 0.0 || !z.is_finite() {
                return Err(format!(
                    "atom type '{}': atomic_number {z} is not an integer",
                    t.name
                ));
            }
            cols.push(format!("{}", z as i64));
        }
        cols.extend([
            self.fmt_f(mass),
            self.fmt_f(charge),
            ptype.to_owned(),
            self.fmt_f(sigma / NM_TO_ANGSTROM),
            self.fmt_f(epsilon * KJ_PER_KCAL),
        ]);
        Ok(Some(format!("  {}\n", cols.join("  "))))
    }
}

impl ForceFieldWriter for GromacsTopFfWriter {
    fn write_str(&self, ff: &ForceField) -> Result<String, String> {
        let mut out = String::from("; Generated by molrs\n\n");
        let sb = ff.special_bonds();
        out.push_str("[ defaults ]\n");
        out.push_str("; nbfunc  comb-rule  gen-pairs  fudgeLJ  fudgeQQ\n");
        out.push_str(&format!(
            "1  2  yes  {}  {}\n\n",
            self.fmt_f(sb.lj_14()),
            self.fmt_f(sb.coul_14()),
        ));

        // Atom types in style order: the `[ atomtypes ]` rows, and the
        // `[ atoms ]` index table the bonded rows point into.
        let atom_types: Vec<&AtomType> = ff.get_atomtypes();

        let mut atomtype_rows = Vec::new();
        for t in &atom_types {
            if let Some(row) = self.atomtypes_row(t)? {
                atomtype_rows.push(row);
            }
        }
        if !atomtype_rows.is_empty() {
            out.push_str("[ atomtypes ]\n");
            out.push_str("; name  [bond_type]  [at.num]  mass  charge  ptype  sigma  epsilon\n");
            for row in atomtype_rows {
                out.push_str(&row);
            }
            out.push('\n');
        }

        // name → first 1-based index (for bonded endpoint lookup by AtomType name)
        let mut name_to_idx: std::collections::HashMap<&str, usize> =
            std::collections::HashMap::new();
        for (i, t) in atom_types.iter().enumerate() {
            name_to_idx.entry(t.name.as_str()).or_insert(i + 1);
        }

        if !atom_types.is_empty() {
            out.push_str("[ atoms ]\n");
            out.push_str("; nr  name  resnr  residu  atom  cgnr  charge  mass\n");
            for (idx, t) in atom_types.iter().enumerate() {
                let nr = idx + 1;
                let name = &t.name;
                let charge = self.fmt_f(t.params.get("charge").unwrap_or(0.0));
                let mass = self.fmt_f(t.params.get("mass").unwrap_or(0.0));
                out.push_str(&format!(
                    "  {nr:>4}  {name:<5} {:>5}  {:<5} {name:<5} {:>4}  {charge}  {mass}\n",
                    0, "LIG", 1
                ));
            }
            out.push('\n');
        }

        // Bonds
        let mut any_bond = false;
        for style in ff.get_styles("bond") {
            let StyleDefs::Bond(types) = style.defs() else {
                continue;
            };
            if types.is_empty() {
                continue;
            }
            if !any_bond {
                out.push_str("[ bonds ]\n");
                out.push_str("; i  j  func  params...\n");
                any_bond = true;
            }
            let style_name = if style.name().is_empty() {
                "harmonic"
            } else {
                style.name()
            };
            let funct = bond_funct(style_name);
            let param_keys = bond_param_keys(style_name);
            for bt in types {
                let i = *name_to_idx.get(bt.itom.as_str()).unwrap_or(&0);
                let j = *name_to_idx.get(bt.jtom.as_str()).unwrap_or(&0);
                let params = format_params(self, &bt.params, param_keys, UnitKind::Bond);
                out.push_str(&format!("  {i}  {j}  {funct}  {params}\n"));
            }
        }
        if any_bond {
            out.push('\n');
        }

        // Angles
        let mut any_angle = false;
        for style in ff.get_styles("angle") {
            let StyleDefs::Angle(types) = style.defs() else {
                continue;
            };
            if types.is_empty() {
                continue;
            }
            if !any_angle {
                out.push_str("[ angles ]\n");
                out.push_str("; i  j  k  func  params...\n");
                any_angle = true;
            }
            let style_name = if style.name().is_empty() {
                "harmonic"
            } else {
                style.name()
            };
            let funct = angle_funct(style_name);
            let param_keys = angle_param_keys(style_name);
            for at in types {
                let i = *name_to_idx.get(at.itom.as_str()).unwrap_or(&0);
                let j = *name_to_idx.get(at.jtom.as_str()).unwrap_or(&0);
                let k = *name_to_idx.get(at.ktom.as_str()).unwrap_or(&0);
                let params = format_params(self, &at.params, param_keys, UnitKind::Angle);
                out.push_str(&format!("  {i}  {j}  {k}  {funct}  {params}\n"));
            }
        }
        if any_angle {
            out.push('\n');
        }

        // Dihedrals
        let mut any_dih = false;
        for style in ff.get_styles("dihedral") {
            let StyleDefs::Dihedral(types) = style.defs() else {
                continue;
            };
            if types.is_empty() {
                continue;
            }
            if !any_dih {
                out.push_str("[ dihedrals ]\n");
                out.push_str("; i  j  k  l  func  params...\n");
                any_dih = true;
            }
            let style_name = if style.name().is_empty() {
                "harmonic"
            } else {
                style.name()
            };
            let funct = dihedral_funct(style_name);
            let param_keys = dihedral_param_keys(style_name);
            for dt in types {
                let i = *name_to_idx.get(dt.itom.as_str()).unwrap_or(&0);
                let j = *name_to_idx.get(dt.jtom.as_str()).unwrap_or(&0);
                let k = *name_to_idx.get(dt.ktom.as_str()).unwrap_or(&0);
                let l = *name_to_idx.get(dt.ltom.as_str()).unwrap_or(&0);
                let params = format_params(self, &dt.params, param_keys, UnitKind::Dihedral);
                out.push_str(&format!("  {i}  {j}  {k}  {l}  {funct}  {params}\n"));
            }
        }
        if any_dih {
            out.push('\n');
        }

        // Pairs
        let mut any_pair = false;
        for style in ff.get_styles("pair") {
            let StyleDefs::Pair(types) = style.defs() else {
                continue;
            };
            if types.is_empty() {
                continue;
            }
            if !any_pair {
                out.push_str("[ pairs ]\n");
                out.push_str("; i  j  func  params...\n");
                any_pair = true;
            }
            let style_name = if style.name().is_empty() {
                "lj12-6"
            } else {
                style.name()
            };
            let funct = pair_funct(style_name);
            let param_keys = pair_param_keys(style_name);
            for pt in types {
                let i = *name_to_idx.get(pt.itom.as_str()).unwrap_or(&0);
                let j = *name_to_idx.get(pt.jtom.as_str()).unwrap_or(&0);
                let params = format_params(self, &pt.params, param_keys, UnitKind::Pair);
                out.push_str(&format!("  {i}  {j}  {funct}  {params}\n"));
            }
        }
        if any_pair {
            out.push('\n');
        }

        Ok(out)
    }
}

/// Convenience free function.
pub fn write_gromacs_top_ff(path: &str, ff: &ForceField, precision: usize) -> Result<(), String> {
    GromacsTopFfWriter::new()
        .with_precision(precision)
        .write(ff, path)
}

pub fn write_gromacs_top_ff_str(ff: &ForceField, precision: usize) -> Result<String, String> {
    GromacsTopFfWriter::new()
        .with_precision(precision)
        .write_str(ff)
}

// ---------------------------------------------------------------------------
// Funct maps + unit inverse
// ---------------------------------------------------------------------------

#[derive(Clone, Copy)]
enum UnitKind {
    Bond,
    Angle,
    Dihedral,
    Pair,
}

fn bond_funct(style: &str) -> &'static str {
    match style {
        "harmonic" | "" => "1",
        "G96" => "2",
        "morse" => "3",
        "cubic" => "4",
        _ => "1",
    }
}

fn angle_funct(style: &str) -> &'static str {
    match style {
        "harmonic" | "" => "1",
        "G96" => "2",
        "quartic" => "3",
        "ub" => "4",
        _ => "1",
    }
}

fn dihedral_funct(style: &str) -> &'static str {
    match style {
        "periodic" => "1",
        "rb" => "2",
        "harmonic" | "" => "3",
        _ => "1",
    }
}

fn pair_funct(style: &str) -> &'static str {
    match style {
        "lj12-6" | "" => "1",
        "buckingham" => "2",
        _ => "1",
    }
}

fn bond_param_keys(style: &str) -> &'static [&'static str] {
    match style {
        "morse" => &["r0", "De", "alpha"],
        "cubic" => &["r0", "k2", "k3", "k4"],
        _ => &["r0", "k"],
    }
}

fn angle_param_keys(style: &str) -> &'static [&'static str] {
    match style {
        "quartic" => &["c0", "c1", "c2", "c3"],
        "ub" => &["theta0", "k", "r0", "k_ub"],
        _ => &["theta0", "k"],
    }
}

fn dihedral_param_keys(style: &str) -> &'static [&'static str] {
    match style {
        "periodic" => &["phase", "k", "periodicity"],
        "rb" => &["c0", "c1", "c2", "c3", "c4", "c5"],
        _ => &["psi0", "k"],
    }
}

fn pair_param_keys(style: &str) -> &'static [&'static str] {
    match style {
        "buckingham" => &["a", "rho", "c"],
        _ => &["c6", "c12"],
    }
}

fn format_params(
    w: &GromacsTopFfWriter,
    params: &crate::ff::forcefield::Params,
    keys: &[&str],
    kind: UnitKind,
) -> String {
    let mut parts = Vec::new();
    for key in keys {
        let v = params.get(key).unwrap_or(0.0);
        let file_v = match (kind, *key) {
            (UnitKind::Bond, "r0") => v / NM_TO_ANGSTROM,
            (UnitKind::Bond, "k" | "k2") => v * (KJ_PER_KCAL * NM_TO_ANGSTROM * NM_TO_ANGSTROM),
            (UnitKind::Bond, "k3") => v * (KJ_PER_KCAL * NM_TO_ANGSTROM.powi(3)),
            (UnitKind::Bond, "k4") => v * (KJ_PER_KCAL * NM_TO_ANGSTROM.powi(4)),
            (UnitKind::Bond, "De") => v * KJ_PER_KCAL,
            (UnitKind::Bond, "alpha") => v * NM_TO_ANGSTROM,
            (UnitKind::Angle, "theta0") => v.to_degrees(),
            (UnitKind::Angle, "k") => v * KJ_PER_KCAL,
            (UnitKind::Angle, "r0") => v / NM_TO_ANGSTROM,
            (UnitKind::Angle, "k_ub") => v * (KJ_PER_KCAL * NM_TO_ANGSTROM * NM_TO_ANGSTROM),
            // Canonical torsions store the phase in radians and barriers in
            // kcal/mol; the GROMACS file wants degrees and kJ/mol.
            (UnitKind::Dihedral, "phase" | "psi0") => v.to_degrees(),
            (UnitKind::Dihedral, "k" | "c0" | "c1" | "c2" | "c3" | "c4" | "c5") => v * KJ_PER_KCAL,
            // GROMACS buckingham writes `a b c6` with b = 1/rho in 1/nm.
            (UnitKind::Pair, "a") => v * KJ_PER_KCAL,
            (UnitKind::Pair, "rho") => {
                if v == 0.0 {
                    0.0
                } else {
                    NM_TO_ANGSTROM / v
                }
            }
            (UnitKind::Pair, "c" | "c6") => v * KJ_PER_KCAL / NM_TO_ANGSTROM.powi(6),
            (UnitKind::Pair, "c12") => v * KJ_PER_KCAL / NM_TO_ANGSTROM.powi(12),
            _ => v,
        };
        parts.push(w.fmt_f(file_v));
    }
    parts.join("  ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ff::forcefield::{ForceField, Params};

    #[test]
    fn empty_ff_writes_header() {
        let ff = ForceField::new("x");
        let s = GromacsTopFfWriter::new().write_str(&ff).unwrap();
        assert!(s.contains("Generated by molrs"));
    }

    #[test]
    fn atom_and_bond_roundtrip_shape() {
        let mut ff = ForceField::new("gmx");
        ff.def_style("atom", "full", Params::new())
            .unwrap()
            .def_type("opls_135", Params::new())
            .unwrap()
            .def_type("opls_140", Params::new())
            .unwrap();
        ff.def_style("bond", "", Params::new())
            .unwrap()
            .def_type(
                "opls_135-opls_140",
                Params::from_pairs(&[("r0", 1.09), ("k", 300.0)]), // molrs units
            )
            .unwrap();
        let s = GromacsTopFfWriter::new().write_str(&ff).unwrap();
        assert!(s.contains("[ atoms ]"));
        assert!(s.contains("[ bonds ]"));
        assert!(s.contains("opls_135"));
    }

    // -- [ atomtypes ] ---------------------------------------------------------

    /// An `opls_135`-like type in molrs units: σ = 3.5 Å, ε = 0.066 kcal/mol.
    fn molrs_unit_params() -> Params {
        let mut p = Params::from_pairs(&[
            ("mass", 12.011),
            ("charge", -0.18),
            ("sigma", 3.5),
            ("epsilon", 0.066),
        ]);
        p.set_str("ptype", "A");
        p
    }

    fn ff_with_atom_type(name: &str, params: Params) -> ForceField {
        let mut ff = ForceField::new("gmx");
        ff.def_style("atom", "full", Params::new())
            .unwrap()
            .def_type(name, params)
            .unwrap();
        ff
    }

    /// The whitespace-split data rows of `[ atomtypes ]` (comments skipped).
    fn atomtypes_rows(text: &str) -> Vec<Vec<&str>> {
        let mut rows = Vec::new();
        let mut inside = false;
        for line in text.lines() {
            let t = line.trim();
            if t.starts_with('[') {
                inside = t == "[ atomtypes ]";
                continue;
            }
            if inside && !t.is_empty() && !t.starts_with(';') {
                rows.push(t.split_whitespace().collect());
            }
        }
        rows
    }

    fn row_for<'a>(rows: &'a [Vec<&'a str>], name: &str) -> &'a [&'a str] {
        rows.iter()
            .find(|r| r[0] == name)
            .unwrap_or_else(|| panic!("no [ atomtypes ] row for {name}: {rows:?}"))
    }

    fn number(token: &str) -> f64 {
        token
            .parse()
            .unwrap_or_else(|e| panic!("{token:?} is not a number: {e}"))
    }

    /// 6-column form `name mass charge ptype V W`. Hand inversion:
    /// V = 3.5 Å ÷ 10 = 0.35 nm; W = 0.066 kcal/mol × 4.184 = 0.276144 kJ/mol.
    #[test]
    fn atomtypes_row_is_written_in_file_units() {
        let ff = ff_with_atom_type("opls_135", molrs_unit_params());
        let text = GromacsTopFfWriter::new().write_str(&ff).unwrap();
        let rows = atomtypes_rows(&text);
        let row = row_for(&rows, "opls_135");

        assert_eq!(row.len(), 6, "{row:?}");
        assert!((number(row[1]) - 12.011).abs() < 1e-9);
        assert!((number(row[2]) - -0.18).abs() < 1e-9);
        assert_eq!(row[3], "A");
        assert!((number(row[4]) - 0.35).abs() < 1e-9);
        assert!((number(row[5]) - 0.276144).abs() < 1e-9);
    }

    /// `bond_type` alone gives the 7-column form `name bond_type mass …`.
    #[test]
    fn atomtypes_row_with_a_bond_type_has_seven_columns() {
        let mut params = molrs_unit_params();
        params.set_str("bond_type", "CT");
        let ff = ff_with_atom_type("opls_135", params);
        let text = GromacsTopFfWriter::new().write_str(&ff).unwrap();
        let rows = atomtypes_rows(&text);
        let row = row_for(&rows, "opls_135");

        assert_eq!(row.len(), 7, "{row:?}");
        assert_eq!(row[1], "CT");
        assert!((number(row[2]) - 12.011).abs() < 1e-9);
    }

    /// `bond_type` and `atomic_number` give the 8-column form
    /// `name bond_type at.num mass charge ptype V W`, `at.num` an integer.
    #[test]
    fn atomtypes_row_with_bond_type_and_atomic_number_has_eight_columns() {
        let mut params = molrs_unit_params();
        params.set_str("bond_type", "CT");
        params.set("atomic_number", 6.0);
        let ff = ff_with_atom_type("opls_135", params);
        let text = GromacsTopFfWriter::new().write_str(&ff).unwrap();
        let rows = atomtypes_rows(&text);
        let row = row_for(&rows, "opls_135");

        assert_eq!(row.len(), 8, "{row:?}");
        assert_eq!(row[1], "CT");
        assert_eq!(row[2], "6");
        assert_eq!(row[5], "A");
    }

    /// A type with no params is referenced, not parameterised: no row.
    #[test]
    fn atom_type_without_params_gets_no_atomtypes_row() {
        let ff = ff_with_atom_type("opls_140", Params::new());
        let text = GromacsTopFfWriter::new().write_str(&ff).unwrap();
        assert!(
            atomtypes_rows(&text).iter().all(|r| r[0] != "opls_140"),
            "{text}"
        );
    }

    /// Some but not all of `mass charge ptype sigma epsilon`: `Err` naming the
    /// type and the missing keys, never a fabricated zero.
    #[test]
    fn partially_parameterised_atom_type_is_an_error() {
        let ff = ff_with_atom_type(
            "opls_135",
            Params::from_pairs(&[("mass", 12.011), ("charge", -0.18)]),
        );
        let err = GromacsTopFfWriter::new()
            .write_str(&ff)
            .expect_err("a partial atom type must not be written");
        for needle in ["opls_135", "ptype", "sigma", "epsilon"] {
            assert!(err.contains(needle), "error should name `{needle}`: {err}");
        }
    }
}
